package autocomplete

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/iw2rmb/ploy/internal/clitree"
)

// GenerateAll returns shell completion scripts keyed by shell name.
func GenerateAll() map[string]string {
	nodes := clitree.Tree()
	return map[string]string{
		"bash": GenerateBash(nodes),
		"zsh":  GenerateZsh(nodes),
		"fish": GenerateFish(nodes),
	}
}

// GenerateBash renders the bash completion script for the CLI command tree.
func GenerateBash(nodes []clitree.Node) string {
	var buf bytes.Buffer
	children := buildChildren(nodes)
	buf.WriteString("# Code generated by internal/autocomplete. DO NOT EDIT.\n")
	buf.WriteString("# See docs/design/cli-command-tree/README.md for command definitions.\n\n")
	buf.WriteString("_ploy_completions() {\n")
	buf.WriteString("    local cur\n")
	buf.WriteString("    COMPREPLY=()\n")
	buf.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	buf.WriteString("    if [[ $COMP_CWORD -eq 1 ]]; then\n")
	buf.WriteString(fmt.Sprintf("        COMPREPLY=( $(compgen -W \"%s\" -- \"$cur\") )\n", strings.Join(topLevelNames(nodes), " ")))
	buf.WriteString("        return 0\n")
	buf.WriteString("    fi\n\n")
	buf.WriteString("    case \"${COMP_WORDS[1]}\" in\n")
	for _, node := range nodes {
		buf.WriteString(fmt.Sprintf("    %s)\n", bashCaseLabel(node.Name)))
		if len(node.Subcommands) > 0 {
			buf.WriteString("        if [[ $COMP_CWORD -eq 2 ]]; then\n")
			buf.WriteString(fmt.Sprintf("            COMPREPLY=( $(compgen -W \"%s\" -- \"$cur\") )\n", strings.Join(childNames(node.Subcommands), " ")))
			buf.WriteString("            return 0\n")
			buf.WriteString("        fi\n")
			for _, child := range node.Subcommands {
				grand, ok := children[joinPath(node.Name, child.Name)]
				if !ok || len(grand) == 0 {
					continue
				}
				buf.WriteString(fmt.Sprintf("        if [[ $COMP_CWORD -eq 3 && \"${COMP_WORDS[2]}\" == \"%s\" ]]; then\n", child.Name))
				buf.WriteString(fmt.Sprintf("            COMPREPLY=( $(compgen -W \"%s\" -- \"$cur\") )\n", strings.Join(childNames(grand), " ")))
				buf.WriteString("            return 0\n")
				buf.WriteString("        fi\n")
			}
		}
		buf.WriteString("        ;;\n")
	}
	buf.WriteString("    esac\n")
	buf.WriteString("}\n")
	buf.WriteString("complete -F _ploy_completions ploy\n")
	return buf.String()
}

// GenerateZsh renders the zsh completion script for the CLI command tree.
func GenerateZsh(nodes []clitree.Node) string {
	var buf bytes.Buffer
	children := buildChildren(nodes)
	buf.WriteString("#compdef ploy\n\n")
	buf.WriteString("_ploy() {\n")
	buf.WriteString("    local state ret=1\n")
	buf.WriteString("    local -a commands\n")
	buf.WriteString("    _arguments -C \\\n")
	buf.WriteString("        '1:command:->cmds' \\\n")
	buf.WriteString("        '2:subcommand:->subs' \\\n")
	buf.WriteString("        '3:subcommand:->third' && ret=0 || ret=$?\n")
	buf.WriteString("    case $state in\n")
	buf.WriteString("        cmds)\n")
	buf.WriteString("            commands=()\n")
	for _, entry := range nodePairs(nodes) {
		buf.WriteString(fmt.Sprintf("            commands+=(\"%s\")\n", entry))
	}
	buf.WriteString("            _describe 'command' commands && ret=0\n")
	buf.WriteString("            ;;\n")
	buf.WriteString("        subs)\n")
	buf.WriteString("            case $words[2] in\n")
	for _, node := range nodes {
		if len(node.Subcommands) == 0 {
			continue
		}
		buf.WriteString(fmt.Sprintf("                %s)\n", zshCaseLabel(node.Name)))
		buf.WriteString("                    commands=()\n")
		for _, entry := range nodePairs(node.Subcommands) {
			buf.WriteString(fmt.Sprintf("                    commands+=(\"%s\")\n", entry))
		}
		buf.WriteString(fmt.Sprintf("                    _describe '%s command' commands && ret=0\n", node.Name))
		buf.WriteString("                    ;;\n")
	}
	buf.WriteString("            esac\n")
	buf.WriteString("            ;;\n")
	buf.WriteString("        third)\n")
	buf.WriteString("            case $words[2] in\n")
	for _, node := range nodes {
		if len(node.Subcommands) == 0 {
			continue
		}
		var needsCase bool
		for _, child := range node.Subcommands {
			grand, ok := children[joinPath(node.Name, child.Name)]
			if !ok || len(grand) == 0 {
				continue
			}
			if !needsCase {
				buf.WriteString(fmt.Sprintf("                %s)\n", zshCaseLabel(node.Name)))
				buf.WriteString("                    case $words[3] in\n")
				needsCase = true
			}
			buf.WriteString(fmt.Sprintf("                        %s)\n", zshCaseLabel(child.Name)))
			buf.WriteString("                            commands=()\n")
			for _, entry := range nodePairs(grand) {
				buf.WriteString(fmt.Sprintf("                            commands+=(\"%s\")\n", entry))
			}
			buf.WriteString(fmt.Sprintf("                            _describe '%s %s command' commands && ret=0\n", node.Name, child.Name))
			buf.WriteString("                            ;;\n")
		}
		if needsCase {
			buf.WriteString("                    esac\n")
			buf.WriteString("                    ;;\n")
		}
	}
	buf.WriteString("            esac\n")
	buf.WriteString("            ;;\n")
	buf.WriteString("    esac\n")
	buf.WriteString("    return ret\n")
	buf.WriteString("}\n\n")
	buf.WriteString("_ploy \"$@\"\n")
	return buf.String()
}

// GenerateFish renders the fish completion script for the CLI command tree.
func GenerateFish(nodes []clitree.Node) string {
	var buf bytes.Buffer
	children := buildChildren(nodes)
	buf.WriteString("# Autogenerated by internal/autocomplete.\n")
	buf.WriteString("# See docs/design/cli-command-tree/README.md for command definitions.\n")
	for _, node := range nodes {
		buf.WriteString(fmt.Sprintf("complete -c ploy -n \"__fish_use_subcommand\" -a '%s' -d '%s'\n", node.Name, escapeDescription(nodeDescription(node))))
	}
	for _, node := range nodes {
		if len(node.Subcommands) == 0 {
			continue
		}
		condition := fmt.Sprintf("__fish_seen_subcommand_from %s", node.Name)
		for _, child := range node.Subcommands {
			buf.WriteString(fmt.Sprintf("complete -c ploy -n \"%s\" -a '%s' -d '%s'\n", condition, child.Name, escapeDescription(nodeDescription(child))))
			grand, ok := children[joinPath(node.Name, child.Name)]
			if !ok || len(grand) == 0 {
				continue
			}
			grandCond := fmt.Sprintf("%s; and __fish_seen_subcommand_from %s", condition, child.Name)
			for _, gc := range grand {
				buf.WriteString(fmt.Sprintf("complete -c ploy -n \"%s\" -a '%s' -d '%s'\n", grandCond, gc.Name, escapeDescription(nodeDescription(gc))))
			}
		}
	}
	return buf.String()
}

// buildChildren creates a map of command path to child nodes.
func buildChildren(nodes []clitree.Node) map[string][]clitree.Node {
	result := make(map[string][]clitree.Node)
	var walk func(path []string, items []clitree.Node)
	walk = func(path []string, items []clitree.Node) {
		key := strings.Join(path, " ")
		if _, exists := result[key]; !exists {
			result[key] = make([]clitree.Node, 0, len(items))
		}
		for _, item := range items {
			result[key] = append(result[key], item)
			if len(item.Subcommands) > 0 {
				walk(append(path, item.Name), item.Subcommands)
			}
		}
	}
	walk(nil, nodes)
	return result
}

// childNames extracts subcommand names preserving order.
func childNames(nodes []clitree.Node) []string {
	names := make([]string, 0, len(nodes))
	for _, node := range nodes {
		names = append(names, node.Name)
	}
	return names
}

// nodePairs renders name:description pairs for zsh completion.
func nodePairs(nodes []clitree.Node) []string {
	pairs := make([]string, 0, len(nodes))
	for _, node := range nodes {
		desc := escapeDescription(nodeDescription(node))
		pairs = append(pairs, fmt.Sprintf("%s:%s", node.Name, desc))
	}
	return pairs
}

// topLevelNames returns the ordered list of top-level command names.
func topLevelNames(nodes []clitree.Node) []string {
	names := make([]string, 0, len(nodes))
	for _, node := range nodes {
		names = append(names, node.Name)
	}
	return names
}

// escapeDescription ensures descriptions avoid single quotes in shell scripts.
func escapeDescription(desc string) string {
	return strings.ReplaceAll(desc, "'", "\\'")
}

// joinPath concatenates command segments for map lookups.
func joinPath(parts ...string) string {
	return strings.Join(parts, " ")
}

// nodeDescription combines synopsis and description when both are present.
func nodeDescription(node clitree.Node) string {
	switch {
	case node.Synopsis != "" && node.Description != "":
		return node.Synopsis + " - " + node.Description
	case node.Description != "":
		return node.Description
	default:
		return node.Synopsis
	}
}

// bashCaseLabel quotes names for bash case statements.
func bashCaseLabel(name string) string {
	return fmt.Sprintf("\"%s\"", name)
}

// zshCaseLabel quotes names for zsh case statements.
func zshCaseLabel(name string) string {
	return fmt.Sprintf("'%s'", name)
}
