checks = [
  "all",
  "-ST1005",  # error strings should not be capitalized
  "-ST1000",  # package comment (relaxed for small packages)
  "-U1000"    # allow temporary unused code during stubs
]

ignore = []
