FROM docker-hosted.artifactory.tcsbank.ru/sec-base-images/ubuntu-noble-java-17-cicd:latest

LABEL org.opencontainers.image.title="java-base-temurin-jdk17" \
    org.opencontainers.image.description="Ploy Java base lane: Temurin JDK 17" \
    org.opencontainers.image.source="https://github.com/iw2rmb/ploy" \
    org.opencontainers.image.licenses="MIT"

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8
