---
all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  children:
    linux_hosts:
      hosts:
        ploy-dev:
          ansible_host: "{{ target_host | default('localhost') }}"
          ansible_port: "{{ target_port | default(22) }}"
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_os_family: "Debian"
