---
all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
  children:
    linux_hosts:
      hosts:
        ploy-dev:
          ansible_host: "{{ target_host | default('localhost') }}"
          ansible_port: "{{ target_port | default(22) }}"
          ansible_python_interpreter: /usr/bin/python3
      vars:
        ansible_os_family: "Debian"
        
    freebsd_vms:
      hosts:
        freebsd-dev:
          ansible_host: "{{ freebsd_host | default('192.168.100.10') }}"
          ansible_port: "{{ freebsd_port | default(22) }}"
          ansible_python_interpreter: /usr/local/bin/python3
      vars:
        ansible_os_family: "FreeBSD"