# Code generated by internal/autocomplete. DO NOT EDIT.
# See docs/design/cli-command-tree/README.md for command definitions.

_ploy_completions() {
    local cur
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "mod mods jobs artifact registry upload report cluster config environment manifest knowledge-base help" -- "$cur") )
        return 0
    fi

    case "${COMP_WORDS[1]}" in
    "mod")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "run cancel resume inspect artifacts" -- "$cur") )
            return 0
        fi
        ;;
    "mods")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "logs" -- "$cur") )
            return 0
        fi
        ;;
    "jobs")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "follow ls inspect retry" -- "$cur") )
            return 0
        fi
        ;;
    "artifact")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "push pull status rm" -- "$cur") )
            return 0
        fi
        ;;
    "registry")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "push-blob get-blob rm-blob put-manifest get-manifest rm-manifest tags" -- "$cur") )
            return 0
        fi
        ;;
    "upload")
        ;;
    "report")
        ;;
    "cluster")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "add connect list cert" -- "$cur") )
            return 0
        fi
        if [[ $COMP_CWORD -eq 3 && "${COMP_WORDS[2]}" == "cert" ]]; then
            COMPREPLY=( $(compgen -W "status" -- "$cur") )
            return 0
        fi
        ;;
    "config")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "gitlab" -- "$cur") )
            return 0
        fi
        if [[ $COMP_CWORD -eq 3 && "${COMP_WORDS[2]}" == "gitlab" ]]; then
            COMPREPLY=( $(compgen -W "show set validate status rotate" -- "$cur") )
            return 0
        fi
        ;;
    "environment")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "materialize" -- "$cur") )
            return 0
        fi
        ;;
    "manifest")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "schema validate" -- "$cur") )
            return 0
        fi
        ;;
    "knowledge-base")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "ingest evaluate" -- "$cur") )
            return 0
        fi
        ;;
    "help")
        if [[ $COMP_CWORD -eq 2 ]]; then
            COMPREPLY=( $(compgen -W "mod mods jobs artifact registry upload report cluster config environment manifest knowledge-base" -- "$cur") )
            return 0
        fi
        ;;
    esac
}
complete -F _ploy_completions ploy
