package mods

import (
	"os"
	"os/exec"
	"path/filepath"
)

// pruneGeneratedDockerfiles removes autogenerated Dockerfile pairs that should not be committed.
func pruneGeneratedDockerfiles(repoPath string) {
	if repoPath == "" {
		return
	}
	names := []string{"build.Dockerfile", "deploy.Dockerfile"}
	for _, name := range names {
		abs := filepath.Join(repoPath, name)
		if _, err := os.Stat(abs); err == nil {
			_ = os.Remove(abs)
		}
		cmd := exec.Command("git", "rm", "-f", "--cached", name)
		cmd.Dir = repoPath
		_ = cmd.Run()
	}
}
