package mods

import (
	"bytes"
	"text/template"
)

// Template for MR description
const mrDescriptionTmpl = `## Mods Workflow: {{.WorkflowID}}

**Branch:** {{.BranchName}}
{{- if .BuildVersion }}
**Build Version:** {{.BuildVersion}}
{{- end }}
**Duration:** {{.Duration}}

## Applied Transformations
{{- if .Steps }}
{{- range .Steps }}
- ✅ {{.StepID}}: {{.Message}}
{{- end }}
{{- else }}
- (no transformation steps recorded)
{{- end }}

{{- if .Healing.Enabled }}
## Self-Healing Applied
- Plan ID: {{.Healing.PlanID}}
{{- if .Healing.WinnerID }}
- Winning Strategy: {{.Healing.WinnerID}}
{{- end }}
- Attempts: {{.Healing.Attempts}}
{{- end }}

---
🤖 This MR was generated by Ploy Mods
📝 Labels: ploy, tfl
`

type mrStep struct {
	StepID  string
	Message string
}

type mrHealing struct {
	Enabled  bool
	PlanID   string
	WinnerID string
	Attempts int
}

type mrData struct {
	WorkflowID   string
	BranchName   string
	BuildVersion string
	Duration     string
	Steps        []mrStep
	Healing      mrHealing
}

func renderMRDescription(r *ModRunner, result *ModResult) string {
	var steps []mrStep
	for _, s := range result.StepResults {
		if s.StepID == "mr" || !s.Success {
			continue
		}
		steps = append(steps, mrStep{StepID: s.StepID, Message: s.Message})
	}
	hd := mrHealing{}
	if result.HealingSummary != nil && result.HealingSummary.Enabled {
		hd.Enabled = true
		hd.PlanID = result.HealingSummary.PlanID
		hd.Attempts = result.HealingSummary.AttemptsCount
		if result.HealingSummary.Winner != nil {
			hd.WinnerID = result.HealingSummary.Winner.ID
		}
	}
	data := mrData{
		WorkflowID:   r.config.ID,
		BranchName:   result.BranchName,
		BuildVersion: result.BuildVersion,
		Duration:     result.Duration.String(),
		Steps:        steps,
		Healing:      hd,
	}
	tmpl := template.Must(template.New("mr").Parse(mrDescriptionTmpl))
	var buf bytes.Buffer
	_ = tmpl.Execute(&buf, data)
	return buf.String()
}
