// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actions.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const claimRunRepoAction = `-- name: ClaimRunRepoAction :one
WITH eligible AS (
  SELECT a.id, n.id AS node_id
  FROM nodes n
  JOIN run_repo_actions a ON TRUE
  JOIN runs r ON r.id = a.run_id
  WHERE n.id = $1
    AND $1::TEXT != ''
    AND a.status = 'Queued'
    AND a.node_id IS NULL
    AND r.status = 'Finished'
  ORDER BY a.run_id ASC, a.repo_id ASC, a.attempt ASC, a.id ASC
  FOR UPDATE OF a SKIP LOCKED
  LIMIT 1
)
UPDATE run_repo_actions a
SET status = 'Running',
    node_id = eligible.node_id,
    started_at = now()
FROM eligible
WHERE a.id = eligible.id
RETURNING a.id, a.run_id, a.repo_id, a.attempt, a.action_type, a.status, a.node_id, a.started_at, a.finished_at, a.duration_ms, a.meta, a.created_at
`

func (q *Queries) ClaimRunRepoAction(ctx context.Context, nodeID types.NodeID) (RunRepoAction, error) {
	row := q.db.QueryRow(ctx, claimRunRepoAction, nodeID)
	var i RunRepoAction
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.Attempt,
		&i.ActionType,
		&i.Status,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const createRunRepoAction = `-- name: CreateRunRepoAction :one
INSERT INTO run_repo_actions (
  id,
  run_id,
  repo_id,
  attempt,
  action_type,
  status,
  meta
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, run_id, repo_id, attempt, action_type, status, node_id, started_at, finished_at, duration_ms, meta, created_at
`

type CreateRunRepoActionParams struct {
	ID         types.JobID     `json:"id"`
	RunID      types.RunID     `json:"run_id"`
	RepoID     types.RepoID    `json:"repo_id"`
	Attempt    int32           `json:"attempt"`
	ActionType string          `json:"action_type"`
	Status     types.JobStatus `json:"status"`
	Meta       []byte          `json:"meta"`
}

func (q *Queries) CreateRunRepoAction(ctx context.Context, arg CreateRunRepoActionParams) (RunRepoAction, error) {
	row := q.db.QueryRow(ctx, createRunRepoAction,
		arg.ID,
		arg.RunID,
		arg.RepoID,
		arg.Attempt,
		arg.ActionType,
		arg.Status,
		arg.Meta,
	)
	var i RunRepoAction
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.Attempt,
		&i.ActionType,
		&i.Status,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getRunRepoAction = `-- name: GetRunRepoAction :one
SELECT id, run_id, repo_id, attempt, action_type, status, node_id, started_at, finished_at, duration_ms, meta, created_at
FROM run_repo_actions
WHERE id = $1
`

func (q *Queries) GetRunRepoAction(ctx context.Context, id types.JobID) (RunRepoAction, error) {
	row := q.db.QueryRow(ctx, getRunRepoAction, id)
	var i RunRepoAction
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.Attempt,
		&i.ActionType,
		&i.Status,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getRunRepoActionByKey = `-- name: GetRunRepoActionByKey :one
SELECT id, run_id, repo_id, attempt, action_type, status, node_id, started_at, finished_at, duration_ms, meta, created_at
FROM run_repo_actions
WHERE run_id = $1
  AND repo_id = $2
  AND attempt = $3
  AND action_type = $4
`

type GetRunRepoActionByKeyParams struct {
	RunID      types.RunID  `json:"run_id"`
	RepoID     types.RepoID `json:"repo_id"`
	Attempt    int32        `json:"attempt"`
	ActionType string       `json:"action_type"`
}

func (q *Queries) GetRunRepoActionByKey(ctx context.Context, arg GetRunRepoActionByKeyParams) (RunRepoAction, error) {
	row := q.db.QueryRow(ctx, getRunRepoActionByKey,
		arg.RunID,
		arg.RepoID,
		arg.Attempt,
		arg.ActionType,
	)
	var i RunRepoAction
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.Attempt,
		&i.ActionType,
		&i.Status,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listRunRepoActionsByRunRepoAttempt = `-- name: ListRunRepoActionsByRunRepoAttempt :many
SELECT id, run_id, repo_id, attempt, action_type, status, node_id, started_at, finished_at, duration_ms, meta, created_at
FROM run_repo_actions
WHERE run_id = $1
  AND repo_id = $2
  AND attempt = $3
ORDER BY id ASC
`

type ListRunRepoActionsByRunRepoAttemptParams struct {
	RunID   types.RunID  `json:"run_id"`
	RepoID  types.RepoID `json:"repo_id"`
	Attempt int32        `json:"attempt"`
}

func (q *Queries) ListRunRepoActionsByRunRepoAttempt(ctx context.Context, arg ListRunRepoActionsByRunRepoAttemptParams) ([]RunRepoAction, error) {
	rows, err := q.db.Query(ctx, listRunRepoActionsByRunRepoAttempt, arg.RunID, arg.RepoID, arg.Attempt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunRepoAction{}
	for rows.Next() {
		var i RunRepoAction
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RepoID,
			&i.Attempt,
			&i.ActionType,
			&i.Status,
			&i.NodeID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunRepoActionCompletion = `-- name: UpdateRunRepoActionCompletion :exec
UPDATE run_repo_actions
SET status = $2,
    finished_at = now(),
    duration_ms = COALESCE(EXTRACT(EPOCH FROM (now() - started_at)) * 1000, 0)::BIGINT,
    meta = $3
WHERE id = $1
`

type UpdateRunRepoActionCompletionParams struct {
	ID     types.JobID     `json:"id"`
	Status types.JobStatus `json:"status"`
	Meta   []byte          `json:"meta"`
}

func (q *Queries) UpdateRunRepoActionCompletion(ctx context.Context, arg UpdateRunRepoActionCompletionParams) error {
	_, err := q.db.Exec(ctx, updateRunRepoActionCompletion, arg.ID, arg.Status, arg.Meta)
	return err
}
