// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifact_bundles.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifactBundle = `-- name: CreateArtifactBundle :one
INSERT INTO artifact_bundles (run_id, job_id, name, bundle_size, cid, digest)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, job_id, name, bundle_size, object_key, cid, digest, created_at
`

type CreateArtifactBundleParams struct {
	RunID      types.RunID  `json:"run_id"`
	JobID      *types.JobID `json:"job_id"`
	Name       *string      `json:"name"`
	BundleSize int64        `json:"bundle_size"`
	Cid        *string      `json:"cid"`
	Digest     *string      `json:"digest"`
}

// Creates a new artifact bundle metadata. Blob data is stored in object storage.
// Bundles are grouped at the job level only (build_id removed).
func (q *Queries) CreateArtifactBundle(ctx context.Context, arg CreateArtifactBundleParams) (ArtifactBundle, error) {
	row := q.db.QueryRow(ctx, createArtifactBundle,
		arg.RunID,
		arg.JobID,
		arg.Name,
		arg.BundleSize,
		arg.Cid,
		arg.Digest,
	)
	var i ArtifactBundle
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobID,
		&i.Name,
		&i.BundleSize,
		&i.ObjectKey,
		&i.Cid,
		&i.Digest,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArtifactBundle = `-- name: DeleteArtifactBundle :exec
DELETE FROM artifact_bundles
WHERE id = $1
`

func (q *Queries) DeleteArtifactBundle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtifactBundle, id)
	return err
}

const deleteArtifactBundlesOlderThan = `-- name: DeleteArtifactBundlesOlderThan :exec
DELETE FROM artifact_bundles
WHERE created_at < $1
`

func (q *Queries) DeleteArtifactBundlesOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteArtifactBundlesOlderThan, createdAt)
	return err
}

const getArtifactBundle = `-- name: GetArtifactBundle :one
SELECT id, run_id, job_id, name, bundle_size, object_key, cid, digest, created_at FROM artifact_bundles
WHERE id = $1
`

// Returns artifact bundle metadata including object_key for object-storage retrieval.
func (q *Queries) GetArtifactBundle(ctx context.Context, id pgtype.UUID) (ArtifactBundle, error) {
	row := q.db.QueryRow(ctx, getArtifactBundle, id)
	var i ArtifactBundle
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobID,
		&i.Name,
		&i.BundleSize,
		&i.ObjectKey,
		&i.Cid,
		&i.Digest,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactBundlesByCID = `-- name: ListArtifactBundlesByCID :many
SELECT id, run_id, job_id, name, bundle_size, object_key, cid, digest, created_at FROM artifact_bundles
WHERE cid = $1
  AND ($2::boolean OR NOT $2::boolean)
ORDER BY created_at DESC, id DESC
`

type ListArtifactBundlesByCIDParams struct {
	Cid          *string `json:"cid"`
	MetadataOnly bool    `json:"metadata_only"`
}

// Returns artifact bundle metadata including object_key for object-storage retrieval.
func (q *Queries) ListArtifactBundlesByCID(ctx context.Context, arg ListArtifactBundlesByCIDParams) ([]ArtifactBundle, error) {
	rows, err := q.db.Query(ctx, listArtifactBundlesByCID, arg.Cid, arg.MetadataOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactBundle{}
	for rows.Next() {
		var i ArtifactBundle
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobID,
			&i.Name,
			&i.BundleSize,
			&i.ObjectKey,
			&i.Cid,
			&i.Digest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactBundlesByRun = `-- name: ListArtifactBundlesByRun :many
SELECT id, run_id, job_id, name, bundle_size, object_key, cid, digest, created_at FROM artifact_bundles
WHERE run_id = $1
  AND ($2::boolean OR NOT $2::boolean)
ORDER BY created_at DESC, id DESC
`

type ListArtifactBundlesByRunParams struct {
	RunID        types.RunID `json:"run_id"`
	MetadataOnly bool        `json:"metadata_only"`
}

// Returns artifact bundle metadata including object_key for object-storage retrieval.
func (q *Queries) ListArtifactBundlesByRun(ctx context.Context, arg ListArtifactBundlesByRunParams) ([]ArtifactBundle, error) {
	rows, err := q.db.Query(ctx, listArtifactBundlesByRun, arg.RunID, arg.MetadataOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactBundle{}
	for rows.Next() {
		var i ArtifactBundle
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobID,
			&i.Name,
			&i.BundleSize,
			&i.ObjectKey,
			&i.Cid,
			&i.Digest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactBundlesByRunAndJob = `-- name: ListArtifactBundlesByRunAndJob :many
SELECT id, run_id, job_id, name, bundle_size, object_key, cid, digest, created_at FROM artifact_bundles
WHERE run_id = $1 AND job_id = $2
  AND ($3::boolean OR NOT $3::boolean)
ORDER BY created_at DESC, id DESC
`

type ListArtifactBundlesByRunAndJobParams struct {
	RunID        types.RunID  `json:"run_id"`
	JobID        *types.JobID `json:"job_id"`
	MetadataOnly bool         `json:"metadata_only"`
}

// Returns artifact bundle metadata including object_key for object-storage retrieval.
func (q *Queries) ListArtifactBundlesByRunAndJob(ctx context.Context, arg ListArtifactBundlesByRunAndJobParams) ([]ArtifactBundle, error) {
	rows, err := q.db.Query(ctx, listArtifactBundlesByRunAndJob, arg.RunID, arg.JobID, arg.MetadataOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactBundle{}
	for rows.Next() {
		var i ArtifactBundle
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobID,
			&i.Name,
			&i.BundleSize,
			&i.ObjectKey,
			&i.Cid,
			&i.Digest,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
