// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifact_bundles.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifactBundle = `-- name: CreateArtifactBundle :one
INSERT INTO artifact_bundles (run_id, stage_id, build_id, name, bundle, cid, digest)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, run_id, stage_id, build_id, name, bundle, created_at, cid, digest
`

type CreateArtifactBundleParams struct {
	RunID   pgtype.UUID `json:"run_id"`
	StageID pgtype.UUID `json:"stage_id"`
	BuildID pgtype.UUID `json:"build_id"`
	Name    *string     `json:"name"`
	Bundle  []byte      `json:"bundle"`
	Cid     *string     `json:"cid"`
	Digest  *string     `json:"digest"`
}

func (q *Queries) CreateArtifactBundle(ctx context.Context, arg CreateArtifactBundleParams) (ArtifactBundle, error) {
	row := q.db.QueryRow(ctx, createArtifactBundle,
		arg.RunID,
		arg.StageID,
		arg.BuildID,
		arg.Name,
		arg.Bundle,
		arg.Cid,
		arg.Digest,
	)
	var i ArtifactBundle
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageID,
		&i.BuildID,
		&i.Name,
		&i.Bundle,
		&i.CreatedAt,
		&i.Cid,
		&i.Digest,
	)
	return i, err
}

const deleteArtifactBundle = `-- name: DeleteArtifactBundle :exec
DELETE FROM artifact_bundles
WHERE id = $1
`

func (q *Queries) DeleteArtifactBundle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtifactBundle, id)
	return err
}

const deleteArtifactBundlesOlderThan = `-- name: DeleteArtifactBundlesOlderThan :exec
DELETE FROM artifact_bundles
WHERE created_at < $1
`

func (q *Queries) DeleteArtifactBundlesOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteArtifactBundlesOlderThan, createdAt)
	return err
}

const getArtifactBundle = `-- name: GetArtifactBundle :one
SELECT id, run_id, stage_id, build_id, name, bundle, created_at, cid, digest FROM artifact_bundles
WHERE id = $1
`

func (q *Queries) GetArtifactBundle(ctx context.Context, id pgtype.UUID) (ArtifactBundle, error) {
	row := q.db.QueryRow(ctx, getArtifactBundle, id)
	var i ArtifactBundle
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageID,
		&i.BuildID,
		&i.Name,
		&i.Bundle,
		&i.CreatedAt,
		&i.Cid,
		&i.Digest,
	)
	return i, err
}

const listArtifactBundlesByCID = `-- name: ListArtifactBundlesByCID :many
SELECT id, run_id, stage_id, build_id, name, bundle, created_at, cid, digest FROM artifact_bundles
WHERE cid = $1
ORDER BY created_at DESC
`

func (q *Queries) ListArtifactBundlesByCID(ctx context.Context, cid *string) ([]ArtifactBundle, error) {
	rows, err := q.db.Query(ctx, listArtifactBundlesByCID, cid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactBundle{}
	for rows.Next() {
		var i ArtifactBundle
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageID,
			&i.BuildID,
			&i.Name,
			&i.Bundle,
			&i.CreatedAt,
			&i.Cid,
			&i.Digest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactBundlesByRun = `-- name: ListArtifactBundlesByRun :many
SELECT id, run_id, stage_id, build_id, name, bundle, created_at, cid, digest FROM artifact_bundles
WHERE run_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListArtifactBundlesByRun(ctx context.Context, runID pgtype.UUID) ([]ArtifactBundle, error) {
	rows, err := q.db.Query(ctx, listArtifactBundlesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactBundle{}
	for rows.Next() {
		var i ArtifactBundle
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageID,
			&i.BuildID,
			&i.Name,
			&i.Bundle,
			&i.CreatedAt,
			&i.Cid,
			&i.Digest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactBundlesByRunAndStage = `-- name: ListArtifactBundlesByRunAndStage :many
SELECT id, run_id, stage_id, build_id, name, bundle, created_at, cid, digest FROM artifact_bundles
WHERE run_id = $1 AND stage_id = $2
ORDER BY created_at DESC
`

type ListArtifactBundlesByRunAndStageParams struct {
	RunID   pgtype.UUID `json:"run_id"`
	StageID pgtype.UUID `json:"stage_id"`
}

func (q *Queries) ListArtifactBundlesByRunAndStage(ctx context.Context, arg ListArtifactBundlesByRunAndStageParams) ([]ArtifactBundle, error) {
	rows, err := q.db.Query(ctx, listArtifactBundlesByRunAndStage, arg.RunID, arg.StageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactBundle{}
	for rows.Next() {
		var i ArtifactBundle
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageID,
			&i.BuildID,
			&i.Name,
			&i.Bundle,
			&i.CreatedAt,
			&i.Cid,
			&i.Digest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
