// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cluster.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCluster = `-- name: CreateCluster :one
INSERT INTO cluster (id, created_at)
VALUES ($1, $2)
RETURNING id, created_at
`

type CreateClusterParams struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster, arg.ID, arg.CreatedAt)
	var i Cluster
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getCluster = `-- name: GetCluster :one
SELECT id, created_at FROM cluster LIMIT 1
`

func (q *Queries) GetCluster(ctx context.Context) (Cluster, error) {
	row := q.db.QueryRow(ctx, getCluster)
	var i Cluster
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
