// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config_env.sql

package store

import (
	"context"
)

const deleteGlobalEnv = `-- name: DeleteGlobalEnv :exec
DELETE FROM config_env
WHERE key = $1
`

// Removes an environment entry by key.
// No-op if the key does not exist (exec returns no error).
func (q *Queries) DeleteGlobalEnv(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteGlobalEnv, key)
	return err
}

const getGlobalEnv = `-- name: GetGlobalEnv :one
SELECT key, value, scope, secret, updated_at
FROM config_env
WHERE key = $1
`

// Retrieves a single environment entry by key.
// Returns pgx.ErrNoRows if the key does not exist.
func (q *Queries) GetGlobalEnv(ctx context.Context, key string) (ConfigEnv, error) {
	row := q.db.QueryRow(ctx, getGlobalEnv, key)
	var i ConfigEnv
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Scope,
		&i.Secret,
		&i.UpdatedAt,
	)
	return i, err
}

const listGlobalEnv = `-- name: ListGlobalEnv :many

SELECT key, value, scope, secret, updated_at
FROM config_env
ORDER BY key ASC
`

// config_env.sql — CRUD queries for global environment variables (config_env table).
// Provides ListGlobalEnv, GetGlobalEnv, UpsertGlobalEnv, DeleteGlobalEnv.
// Returns all global environment entries, ordered by key for consistent iteration.
// Used by ConfigHolder initialization and HTTP list endpoint.
func (q *Queries) ListGlobalEnv(ctx context.Context) ([]ConfigEnv, error) {
	rows, err := q.db.Query(ctx, listGlobalEnv)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigEnv{}
	for rows.Next() {
		var i ConfigEnv
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Scope,
			&i.Secret,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGlobalEnv = `-- name: UpsertGlobalEnv :exec
INSERT INTO config_env (key, value, scope, secret, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (key) DO UPDATE SET
  value      = EXCLUDED.value,
  scope      = EXCLUDED.scope,
  secret     = EXCLUDED.secret,
  updated_at = now()
`

type UpsertGlobalEnvParams struct {
	Key    string `json:"key"`
	Value  string `json:"value"`
	Scope  string `json:"scope"`
	Secret bool   `json:"secret"`
}

// Inserts or updates an environment entry (upsert on primary key 'key').
// Updates value, scope, secret, and refreshes updated_at on conflict.
// This ensures idempotent set operations from the CLI or API.
func (q *Queries) UpsertGlobalEnv(ctx context.Context, arg UpsertGlobalEnvParams) error {
	_, err := q.db.Exec(ctx, upsertGlobalEnv,
		arg.Key,
		arg.Value,
		arg.Scope,
		arg.Secret,
	)
	return err
}
