// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config_in.sql

package store

import (
	"context"
)

const deleteConfigIn = `-- name: DeleteConfigIn :exec
DELETE FROM config_in
WHERE dst = $1 AND section = $2
`

type DeleteConfigInParams struct {
	Dst     string `json:"dst"`
	Section string `json:"section"`
}

// Removes an in entry by dst and section.
func (q *Queries) DeleteConfigIn(ctx context.Context, arg DeleteConfigInParams) error {
	_, err := q.db.Exec(ctx, deleteConfigIn, arg.Dst, arg.Section)
	return err
}

const deleteConfigInBySection = `-- name: DeleteConfigInBySection :exec
DELETE FROM config_in
WHERE section = $1
`

// Removes all in entries for a section.
func (q *Queries) DeleteConfigInBySection(ctx context.Context, section string) error {
	_, err := q.db.Exec(ctx, deleteConfigInBySection, section)
	return err
}

const listConfigIn = `-- name: ListConfigIn :many

SELECT entry, dst, section, updated_at
FROM config_in
ORDER BY section ASC, dst ASC
`

// config_in.sql — CRUD queries for global in mount entries (config_in table).
// Provides ListConfigIn, UpsertConfigIn, DeleteConfigIn, DeleteConfigInBySection.
// Returns all in entries ordered by section then dst for deterministic iteration.
func (q *Queries) ListConfigIn(ctx context.Context) ([]ConfigIn, error) {
	rows, err := q.db.Query(ctx, listConfigIn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigIn{}
	for rows.Next() {
		var i ConfigIn
		if err := rows.Scan(
			&i.Entry,
			&i.Dst,
			&i.Section,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigInBySection = `-- name: ListConfigInBySection :many
SELECT entry, dst, section, updated_at
FROM config_in
WHERE section = $1
ORDER BY dst ASC
`

// Returns in entries for a specific section ordered by dst.
func (q *Queries) ListConfigInBySection(ctx context.Context, section string) ([]ConfigIn, error) {
	rows, err := q.db.Query(ctx, listConfigInBySection, section)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigIn{}
	for rows.Next() {
		var i ConfigIn
		if err := rows.Scan(
			&i.Entry,
			&i.Dst,
			&i.Section,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfigIn = `-- name: UpsertConfigIn :exec
INSERT INTO config_in (entry, dst, section, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (dst, section) DO UPDATE SET
  entry      = EXCLUDED.entry,
  updated_at = now()
`

type UpsertConfigInParams struct {
	Entry   string `json:"entry"`
	Dst     string `json:"dst"`
	Section string `json:"section"`
}

// Inserts or updates an in entry (upsert on composite key (dst, section)).
// Refreshes entry and updated_at on conflict (entry may change if hash changes).
func (q *Queries) UpsertConfigIn(ctx context.Context, arg UpsertConfigInParams) error {
	_, err := q.db.Exec(ctx, upsertConfigIn, arg.Entry, arg.Dst, arg.Section)
	return err
}
