// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config_bundle_map.sql

package store

import (
	"context"
)

const listConfigBundleMap = `-- name: ListConfigBundleMap :many

SELECT hash, bundle_id, updated_at
FROM config_bundle_map
ORDER BY hash ASC
`

// config_bundle_map.sql — read queries for global bundle map entries (config_bundle_map table).
// Provides ListConfigBundleMap.
// Returns all bundle map entries ordered by hash for deterministic iteration.
func (q *Queries) ListConfigBundleMap(ctx context.Context) ([]ConfigBundleMap, error) {
	rows, err := q.db.Query(ctx, listConfigBundleMap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigBundleMap{}
	for rows.Next() {
		var i ConfigBundleMap
		if err := rows.Scan(&i.Hash, &i.BundleID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
