// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config_home.sql

package store

import (
	"context"
)

const deleteConfigHome = `-- name: DeleteConfigHome :exec
DELETE FROM config_home
WHERE dst = $1 AND section = $2
`

type DeleteConfigHomeParams struct {
	Dst     string `json:"dst"`
	Section string `json:"section"`
}

// Removes a home entry by dst and section.
func (q *Queries) DeleteConfigHome(ctx context.Context, arg DeleteConfigHomeParams) error {
	_, err := q.db.Exec(ctx, deleteConfigHome, arg.Dst, arg.Section)
	return err
}

const deleteConfigHomeBySection = `-- name: DeleteConfigHomeBySection :exec
DELETE FROM config_home
WHERE section = $1
`

// Removes all home entries for a section.
func (q *Queries) DeleteConfigHomeBySection(ctx context.Context, section string) error {
	_, err := q.db.Exec(ctx, deleteConfigHomeBySection, section)
	return err
}

const listConfigHome = `-- name: ListConfigHome :many

SELECT entry, dst, section, updated_at
FROM config_home
ORDER BY section ASC, dst ASC
`

// config_home.sql — CRUD queries for global home mount entries (config_home table).
// Provides ListConfigHome, UpsertConfigHome, DeleteConfigHome, DeleteConfigHomeBySection.
// Returns all home entries ordered by section then dst for deterministic iteration.
func (q *Queries) ListConfigHome(ctx context.Context) ([]ConfigHome, error) {
	rows, err := q.db.Query(ctx, listConfigHome)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigHome{}
	for rows.Next() {
		var i ConfigHome
		if err := rows.Scan(
			&i.Entry,
			&i.Dst,
			&i.Section,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigHomeBySection = `-- name: ListConfigHomeBySection :many
SELECT entry, dst, section, updated_at
FROM config_home
WHERE section = $1
ORDER BY dst ASC
`

// Returns home entries for a specific section ordered by dst.
func (q *Queries) ListConfigHomeBySection(ctx context.Context, section string) ([]ConfigHome, error) {
	rows, err := q.db.Query(ctx, listConfigHomeBySection, section)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigHome{}
	for rows.Next() {
		var i ConfigHome
		if err := rows.Scan(
			&i.Entry,
			&i.Dst,
			&i.Section,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfigHome = `-- name: UpsertConfigHome :exec
INSERT INTO config_home (entry, dst, section, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (dst, section) DO UPDATE SET
  entry      = EXCLUDED.entry,
  updated_at = now()
`

type UpsertConfigHomeParams struct {
	Entry   string `json:"entry"`
	Dst     string `json:"dst"`
	Section string `json:"section"`
}

// Inserts or updates a home entry (upsert on composite key (dst, section)).
// Refreshes entry and updated_at on conflict (entry may change if hash or ro flag changes).
func (q *Queries) UpsertConfigHome(ctx context.Context, arg UpsertConfigHomeParams) error {
	_, err := q.db.Exec(ctx, upsertConfigHome, arg.Entry, arg.Dst, arg.Section)
	return err
}
