// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config_in.sql

package store

import (
	"context"
)

const listConfigIn = `-- name: ListConfigIn :many

SELECT entry, dst, section, updated_at
FROM config_in
ORDER BY section ASC, dst ASC
`

// config_in.sql — read queries for global in mount entries (config_in table).
// Provides ListConfigIn.
// Returns all in entries ordered by section then dst for deterministic iteration.
func (q *Queries) ListConfigIn(ctx context.Context) ([]ConfigIn, error) {
	rows, err := q.db.Query(ctx, listConfigIn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigIn{}
	for rows.Next() {
		var i ConfigIn
		if err := rows.Scan(
			&i.Entry,
			&i.Dst,
			&i.Section,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
