// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diffs.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDiff = `-- name: CreateDiff :one
INSERT INTO diffs (run_id, job_id, patch_size, summary)
VALUES ($1, $2, $3, $4)
RETURNING id, run_id, job_id, patch_size, object_key, summary, created_at
`

type CreateDiffParams struct {
	RunID     types.RunID  `json:"run_id"`
	JobID     *types.JobID `json:"job_id"`
	PatchSize int64        `json:"patch_size"`
	Summary   []byte       `json:"summary"`
}

// Creates a new diff entry associated with a job. Blob data is stored in object storage.
func (q *Queries) CreateDiff(ctx context.Context, arg CreateDiffParams) (Diff, error) {
	row := q.db.QueryRow(ctx, createDiff,
		arg.RunID,
		arg.JobID,
		arg.PatchSize,
		arg.Summary,
	)
	var i Diff
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobID,
		&i.PatchSize,
		&i.ObjectKey,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDiff = `-- name: DeleteDiff :exec
DELETE FROM diffs
WHERE id = $1
`

func (q *Queries) DeleteDiff(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDiff, id)
	return err
}

const deleteDiffsOlderThan = `-- name: DeleteDiffsOlderThan :exec
DELETE FROM diffs
WHERE created_at < $1
`

func (q *Queries) DeleteDiffsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteDiffsOlderThan, createdAt)
	return err
}

const getLatestDiffByJob = `-- name: GetLatestDiffByJob :one
SELECT id, run_id, job_id, patch_size, object_key, summary, created_at
FROM diffs
WHERE job_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestDiffByJob(ctx context.Context, jobID *types.JobID) (Diff, error) {
	row := q.db.QueryRow(ctx, getLatestDiffByJob, jobID)
	var i Diff
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobID,
		&i.PatchSize,
		&i.ObjectKey,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const listDiffsByRun = `-- name: ListDiffsByRun :many
SELECT
  id,
  run_id,
  job_id,
  patch_size,
  object_key,
  summary,
  created_at
FROM diffs
WHERE run_id = $1
ORDER BY created_at ASC, id ASC
`

// Returns diff metadata for a run.
func (q *Queries) ListDiffsByRun(ctx context.Context, runID types.RunID) ([]Diff, error) {
	rows, err := q.db.Query(ctx, listDiffsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Diff{}
	for rows.Next() {
		var i Diff
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobID,
			&i.PatchSize,
			&i.ObjectKey,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
