// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diffs.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDiff = `-- name: CreateDiff :one
INSERT INTO diffs (run_id, job_id, patch_size, summary)
VALUES ($1, $2, $3, $4)
RETURNING id, run_id, job_id, patch_size, object_key, summary, created_at
`

type CreateDiffParams struct {
	RunID     types.RunID  `json:"run_id"`
	JobID     *types.JobID `json:"job_id"`
	PatchSize int64        `json:"patch_size"`
	Summary   []byte       `json:"summary"`
}

// Creates a new diff entry associated with a job. Blob data is stored in object storage.
// Ordering is determined by the job's step_index.
func (q *Queries) CreateDiff(ctx context.Context, arg CreateDiffParams) (Diff, error) {
	row := q.db.QueryRow(ctx, createDiff,
		arg.RunID,
		arg.JobID,
		arg.PatchSize,
		arg.Summary,
	)
	var i Diff
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobID,
		&i.PatchSize,
		&i.ObjectKey,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDiff = `-- name: DeleteDiff :exec
DELETE FROM diffs
WHERE id = $1
`

func (q *Queries) DeleteDiff(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDiff, id)
	return err
}

const deleteDiffsOlderThan = `-- name: DeleteDiffsOlderThan :exec
DELETE FROM diffs
WHERE created_at < $1
`

func (q *Queries) DeleteDiffsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteDiffsOlderThan, createdAt)
	return err
}

const getDiff = `-- name: GetDiff :one
SELECT id, run_id, job_id, patch_size, object_key, summary, created_at FROM diffs
WHERE id = $1
`

// Returns diff metadata including object_key for object-storage retrieval.
func (q *Queries) GetDiff(ctx context.Context, id pgtype.UUID) (Diff, error) {
	row := q.db.QueryRow(ctx, getDiff, id)
	var i Diff
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobID,
		&i.PatchSize,
		&i.ObjectKey,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const listDiffsBeforeStep = `-- name: ListDiffsBeforeStep :many
SELECT d.id, d.run_id, d.job_id, d.patch_size, d.object_key, d.summary, d.created_at FROM diffs d
INNER JOIN jobs j ON d.job_id = j.id
WHERE d.run_id = $1
  AND j.step_index <= $2
ORDER BY j.step_index ASC, d.created_at ASC, d.id ASC
`

type ListDiffsBeforeStepParams struct {
	RunID     types.RunID     `json:"run_id"`
	StepIndex types.StepIndex `json:"step_index"`
}

// Returns all diffs for a run up to (and including) the specified step_index.
// Used for workspace rehydration: apply all diffs from jobs with step_index <= k to build workspace for step k+1.
// Excludes diffs without associated jobs (NULL job_id) to avoid applying orphan diffs during rehydration.
func (q *Queries) ListDiffsBeforeStep(ctx context.Context, arg ListDiffsBeforeStepParams) ([]Diff, error) {
	rows, err := q.db.Query(ctx, listDiffsBeforeStep, arg.RunID, arg.StepIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Diff{}
	for rows.Next() {
		var i Diff
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobID,
			&i.PatchSize,
			&i.ObjectKey,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiffsByRunRepo = `-- name: ListDiffsByRunRepo :many
SELECT d.id, d.run_id, d.job_id, d.patch_size, d.object_key, d.summary, d.created_at FROM diffs d
JOIN jobs j ON j.id = d.job_id
WHERE d.run_id = $1 AND j.repo_id = $2
ORDER BY j.step_index ASC, d.created_at ASC, d.id ASC
`

type ListDiffsByRunRepoParams struct {
	RunID  types.RunID     `json:"run_id"`
	RepoID types.ModRepoID `json:"repo_id"`
}

// Returns diffs for a specific repo execution within a run.
// Repo attribution comes from joining diffs.job_id to jobs.repo_id.
// This supports the repo-scoped endpoint GET /v1/runs/{run_id}/repos/{repo_id}/diffs.
// Diffs for repo A are excluded from repo B listing via the j.repo_id filter.
func (q *Queries) ListDiffsByRunRepo(ctx context.Context, arg ListDiffsByRunRepoParams) ([]Diff, error) {
	rows, err := q.db.Query(ctx, listDiffsByRunRepo, arg.RunID, arg.RepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Diff{}
	for rows.Next() {
		var i Diff
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobID,
			&i.PatchSize,
			&i.ObjectKey,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiffsMetaByRun = `-- name: ListDiffsMetaByRun :many
SELECT id, run_id, job_id, patch_size, object_key, summary, created_at FROM diffs
WHERE run_id = $1
ORDER BY created_at ASC, id ASC
`

// Returns diff metadata for a run.
func (q *Queries) ListDiffsMetaByRun(ctx context.Context, runID types.RunID) ([]Diff, error) {
	rows, err := q.db.Query(ctx, listDiffsMetaByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Diff{}
	for rows.Next() {
		var i Diff
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobID,
			&i.PatchSize,
			&i.ObjectKey,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiffsMetaByRunRepo = `-- name: ListDiffsMetaByRunRepo :many
SELECT d.id, d.run_id, d.job_id, d.patch_size, d.object_key, d.summary, d.created_at FROM diffs d
JOIN jobs j ON j.id = d.job_id
WHERE d.run_id = $1 AND j.repo_id = $2
ORDER BY j.step_index ASC, d.created_at ASC, d.id ASC
`

type ListDiffsMetaByRunRepoParams struct {
	RunID  types.RunID     `json:"run_id"`
	RepoID types.ModRepoID `json:"repo_id"`
}

// Returns diff metadata for a specific repo within a run.
func (q *Queries) ListDiffsMetaByRunRepo(ctx context.Context, arg ListDiffsMetaByRunRepoParams) ([]Diff, error) {
	rows, err := q.db.Query(ctx, listDiffsMetaByRunRepo, arg.RunID, arg.RepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Diff{}
	for rows.Next() {
		var i Diff
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobID,
			&i.PatchSize,
			&i.ObjectKey,
			&i.Summary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
