// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (run_id, job_id, time, level, message, meta)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, job_id, time, level, message, meta
`

type CreateEventParams struct {
	RunID   types.RunID        `json:"run_id"`
	JobID   *types.JobID       `json:"job_id"`
	Time    pgtype.Timestamptz `json:"time"`
	Level   string             `json:"level"`
	Message string             `json:"message"`
	Meta    []byte             `json:"meta"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.RunID,
		arg.JobID,
		arg.Time,
		arg.Level,
		arg.Message,
		arg.Meta,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobID,
		&i.Time,
		&i.Level,
		&i.Message,
		&i.Meta,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, run_id, job_id, time, level, message, meta FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobID,
		&i.Time,
		&i.Level,
		&i.Message,
		&i.Meta,
	)
	return i, err
}

const listEventsByRun = `-- name: ListEventsByRun :many
SELECT id, run_id, job_id, time, level, message, meta FROM events
WHERE run_id = $1
ORDER BY time ASC, id ASC
`

func (q *Queries) ListEventsByRun(ctx context.Context, runID types.RunID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobID,
			&i.Time,
			&i.Level,
			&i.Message,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByRunSince = `-- name: ListEventsByRunSince :many
SELECT id, run_id, job_id, time, level, message, meta FROM events
WHERE run_id = $1 AND id > $2
ORDER BY time ASC, id ASC
`

type ListEventsByRunSinceParams struct {
	RunID types.RunID `json:"run_id"`
	ID    int64       `json:"id"`
}

func (q *Queries) ListEventsByRunSince(ctx context.Context, arg ListEventsByRunSinceParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByRunSince, arg.RunID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobID,
			&i.Time,
			&i.Level,
			&i.Message,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
