// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gate_profiles.sql

package store

import (
	"context"
)

const getDefaultGateProfile = `-- name: GetDefaultGateProfile :one
SELECT id,
       COALESCE(repo_id, '') AS repo_id,
       COALESCE(repo_sha, '') AS repo_sha,
       COALESCE(repo_sha8, '') AS repo_sha8,
       stack_id,
       url
FROM gate_profiles
WHERE repo_id IS NULL
  AND repo_sha IS NULL
  AND stack_id = $1
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetDefaultGateProfileRow struct {
	ID       int64  `json:"id"`
	RepoID   string `json:"repo_id"`
	RepoSha  string `json:"repo_sha"`
	RepoSha8 string `json:"repo_sha8"`
	StackID  int64  `json:"stack_id"`
	Url      string `json:"url"`
}

func (q *Queries) GetDefaultGateProfile(ctx context.Context, stackID int64) (GetDefaultGateProfileRow, error) {
	row := q.db.QueryRow(ctx, getDefaultGateProfile, stackID)
	var i GetDefaultGateProfileRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RepoSha,
		&i.RepoSha8,
		&i.StackID,
		&i.Url,
	)
	return i, err
}

const getExactGateProfile = `-- name: GetExactGateProfile :one
SELECT id,
       COALESCE(repo_id, '') AS repo_id,
       COALESCE(repo_sha, '') AS repo_sha,
       COALESCE(repo_sha8, '') AS repo_sha8,
       stack_id,
       url
FROM gate_profiles
WHERE COALESCE(repo_id, '') = $1::text
  AND COALESCE(repo_sha, '') = $2::text
  AND stack_id = $3
LIMIT 1
`

type GetExactGateProfileParams struct {
	RepoID  string `json:"repo_id"`
	RepoSha string `json:"repo_sha"`
	StackID int64  `json:"stack_id"`
}

type GetExactGateProfileRow struct {
	ID       int64  `json:"id"`
	RepoID   string `json:"repo_id"`
	RepoSha  string `json:"repo_sha"`
	RepoSha8 string `json:"repo_sha8"`
	StackID  int64  `json:"stack_id"`
	Url      string `json:"url"`
}

func (q *Queries) GetExactGateProfile(ctx context.Context, arg GetExactGateProfileParams) (GetExactGateProfileRow, error) {
	row := q.db.QueryRow(ctx, getExactGateProfile, arg.RepoID, arg.RepoSha, arg.StackID)
	var i GetExactGateProfileRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RepoSha,
		&i.RepoSha8,
		&i.StackID,
		&i.Url,
	)
	return i, err
}

const getLatestRepoGateProfile = `-- name: GetLatestRepoGateProfile :one
SELECT id,
       COALESCE(repo_id, '') AS repo_id,
       COALESCE(repo_sha, '') AS repo_sha,
       COALESCE(repo_sha8, '') AS repo_sha8,
       stack_id,
       url
FROM gate_profiles
WHERE COALESCE(repo_id, '') = $1::text
  AND stack_id = $2
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type GetLatestRepoGateProfileParams struct {
	RepoID  string `json:"repo_id"`
	StackID int64  `json:"stack_id"`
}

type GetLatestRepoGateProfileRow struct {
	ID       int64  `json:"id"`
	RepoID   string `json:"repo_id"`
	RepoSha  string `json:"repo_sha"`
	RepoSha8 string `json:"repo_sha8"`
	StackID  int64  `json:"stack_id"`
	Url      string `json:"url"`
}

func (q *Queries) GetLatestRepoGateProfile(ctx context.Context, arg GetLatestRepoGateProfileParams) (GetLatestRepoGateProfileRow, error) {
	row := q.db.QueryRow(ctx, getLatestRepoGateProfile, arg.RepoID, arg.StackID)
	var i GetLatestRepoGateProfileRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RepoSha,
		&i.RepoSha8,
		&i.StackID,
		&i.Url,
	)
	return i, err
}

const resolveAnyStackID = `-- name: ResolveAnyStackID :one
SELECT id
FROM stacks
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) ResolveAnyStackID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, resolveAnyStackID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const resolvePreGateCreationBindingByRepoSHA = `-- name: ResolvePreGateCreationBindingByRepoSHA :one
SELECT gp.id AS profile_id,
       COALESCE(s.image, '') AS job_image
FROM gate_profiles gp
JOIN stacks s ON s.id = gp.stack_id
WHERE COALESCE(gp.repo_id, '') = $1::text
  AND COALESCE(gp.repo_sha, '') = $2::text
ORDER BY gp.updated_at DESC, gp.id DESC
LIMIT 1
`

type ResolvePreGateCreationBindingByRepoSHAParams struct {
	RepoID  string `json:"repo_id"`
	RepoSha string `json:"repo_sha"`
}

type ResolvePreGateCreationBindingByRepoSHARow struct {
	ProfileID int64  `json:"profile_id"`
	JobImage  string `json:"job_image"`
}

func (q *Queries) ResolvePreGateCreationBindingByRepoSHA(ctx context.Context, arg ResolvePreGateCreationBindingByRepoSHAParams) (ResolvePreGateCreationBindingByRepoSHARow, error) {
	row := q.db.QueryRow(ctx, resolvePreGateCreationBindingByRepoSHA, arg.RepoID, arg.RepoSha)
	var i ResolvePreGateCreationBindingByRepoSHARow
	err := row.Scan(&i.ProfileID, &i.JobImage)
	return i, err
}

const resolvePreGateCreationBindingByRepoSHAAndStack = `-- name: ResolvePreGateCreationBindingByRepoSHAAndStack :one
SELECT gp.id AS profile_id,
       COALESCE(s.image, '') AS job_image
FROM gate_profiles gp
JOIN stacks s ON s.id = gp.stack_id
WHERE COALESCE(gp.repo_id, '') = $1::text
  AND COALESCE(gp.repo_sha, '') = $2::text
  AND ($3::text = '' OR s.lang = $3::text)
  AND ($4::text = '' OR COALESCE(s.tool, '') = $4::text)
  AND ($5::text = '' OR s.release = $5::text)
ORDER BY gp.updated_at DESC, gp.id DESC
LIMIT 1
`

type ResolvePreGateCreationBindingByRepoSHAAndStackParams struct {
	RepoID  string `json:"repo_id"`
	RepoSha string `json:"repo_sha"`
	Lang    string `json:"lang"`
	Tool    string `json:"tool"`
	Release string `json:"release"`
}

type ResolvePreGateCreationBindingByRepoSHAAndStackRow struct {
	ProfileID int64  `json:"profile_id"`
	JobImage  string `json:"job_image"`
}

func (q *Queries) ResolvePreGateCreationBindingByRepoSHAAndStack(ctx context.Context, arg ResolvePreGateCreationBindingByRepoSHAAndStackParams) (ResolvePreGateCreationBindingByRepoSHAAndStackRow, error) {
	row := q.db.QueryRow(ctx, resolvePreGateCreationBindingByRepoSHAAndStack,
		arg.RepoID,
		arg.RepoSha,
		arg.Lang,
		arg.Tool,
		arg.Release,
	)
	var i ResolvePreGateCreationBindingByRepoSHAAndStackRow
	err := row.Scan(&i.ProfileID, &i.JobImage)
	return i, err
}

const resolveStackIDByImage = `-- name: ResolveStackIDByImage :one
SELECT id
FROM stacks
WHERE image = $1
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) ResolveStackIDByImage(ctx context.Context, image string) (int64, error) {
	row := q.db.QueryRow(ctx, resolveStackIDByImage, image)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const resolveStackIDByRepoSHA = `-- name: ResolveStackIDByRepoSHA :one
SELECT stack_id
FROM gate_profiles
WHERE COALESCE(repo_id, '') = $1::text
  AND COALESCE(repo_sha, '') = $2::text
ORDER BY updated_at DESC, id DESC
LIMIT 1
`

type ResolveStackIDByRepoSHAParams struct {
	RepoID  string `json:"repo_id"`
	RepoSha string `json:"repo_sha"`
}

func (q *Queries) ResolveStackIDByRepoSHA(ctx context.Context, arg ResolveStackIDByRepoSHAParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveStackIDByRepoSHA, arg.RepoID, arg.RepoSha)
	var stack_id int64
	err := row.Scan(&stack_id)
	return stack_id, err
}

const resolveStackIDByRequiredStack = `-- name: ResolveStackIDByRequiredStack :one
SELECT id
FROM stacks
WHERE lang = $1::text
  AND release = $2::text
  AND (
    ($3::text <> '' AND COALESCE(tool, '') = $3::text) OR
    ($3::text = '' AND tool IS NULL)
  )
ORDER BY id ASC
LIMIT 1
`

type ResolveStackIDByRequiredStackParams struct {
	Lang    string `json:"lang"`
	Release string `json:"release"`
	Tool    string `json:"tool"`
}

func (q *Queries) ResolveStackIDByRequiredStack(ctx context.Context, arg ResolveStackIDByRequiredStackParams) (int64, error) {
	row := q.db.QueryRow(ctx, resolveStackIDByRequiredStack, arg.Lang, arg.Release, arg.Tool)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const resolveStackRowByImage = `-- name: ResolveStackRowByImage :one
SELECT id,
       lang,
       COALESCE(tool, '') AS tool,
       release
FROM stacks
WHERE image = $1
ORDER BY id ASC
LIMIT 1
`

type ResolveStackRowByImageRow struct {
	ID      int64  `json:"id"`
	Lang    string `json:"lang"`
	Tool    string `json:"tool"`
	Release string `json:"release"`
}

func (q *Queries) ResolveStackRowByImage(ctx context.Context, image string) (ResolveStackRowByImageRow, error) {
	row := q.db.QueryRow(ctx, resolveStackRowByImage, image)
	var i ResolveStackRowByImageRow
	err := row.Scan(
		&i.ID,
		&i.Lang,
		&i.Tool,
		&i.Release,
	)
	return i, err
}

const resolveStackRowByLangTool = `-- name: ResolveStackRowByLangTool :one
SELECT id,
       lang,
       COALESCE(tool, '') AS tool,
       release
FROM stacks
WHERE lang = $1::text
  AND COALESCE(tool, '') = $2::text
ORDER BY id ASC
LIMIT 1
`

type ResolveStackRowByLangToolParams struct {
	Lang string `json:"lang"`
	Tool string `json:"tool"`
}

type ResolveStackRowByLangToolRow struct {
	ID      int64  `json:"id"`
	Lang    string `json:"lang"`
	Tool    string `json:"tool"`
	Release string `json:"release"`
}

func (q *Queries) ResolveStackRowByLangTool(ctx context.Context, arg ResolveStackRowByLangToolParams) (ResolveStackRowByLangToolRow, error) {
	row := q.db.QueryRow(ctx, resolveStackRowByLangTool, arg.Lang, arg.Tool)
	var i ResolveStackRowByLangToolRow
	err := row.Scan(
		&i.ID,
		&i.Lang,
		&i.Tool,
		&i.Release,
	)
	return i, err
}

const resolveStackRowByLangToolRelease = `-- name: ResolveStackRowByLangToolRelease :one
SELECT id,
       lang,
       COALESCE(tool, '') AS tool,
       release
FROM stacks
WHERE lang = $1::text
  AND COALESCE(tool, '') = $2::text
  AND release = $3::text
ORDER BY id ASC
LIMIT 1
`

type ResolveStackRowByLangToolReleaseParams struct {
	Lang    string `json:"lang"`
	Tool    string `json:"tool"`
	Release string `json:"release"`
}

type ResolveStackRowByLangToolReleaseRow struct {
	ID      int64  `json:"id"`
	Lang    string `json:"lang"`
	Tool    string `json:"tool"`
	Release string `json:"release"`
}

func (q *Queries) ResolveStackRowByLangToolRelease(ctx context.Context, arg ResolveStackRowByLangToolReleaseParams) (ResolveStackRowByLangToolReleaseRow, error) {
	row := q.db.QueryRow(ctx, resolveStackRowByLangToolRelease, arg.Lang, arg.Tool, arg.Release)
	var i ResolveStackRowByLangToolReleaseRow
	err := row.Scan(
		&i.ID,
		&i.Lang,
		&i.Tool,
		&i.Release,
	)
	return i, err
}

const upsertExactGateProfile = `-- name: UpsertExactGateProfile :one
INSERT INTO gate_profiles (
  repo_id,
  repo_sha,
  repo_sha8,
  stack_id,
  url
)
VALUES (
  $1::text,
  $2::text,
  SUBSTRING($2::text, 1, 8),
  $3,
  $4
)
ON CONFLICT (repo_id, repo_sha, stack_id)
DO UPDATE SET
  url = EXCLUDED.url,
  repo_sha8 = EXCLUDED.repo_sha8,
  updated_at = NOW()
RETURNING id,
          COALESCE(repo_id, '') AS repo_id,
          COALESCE(repo_sha, '') AS repo_sha,
          COALESCE(repo_sha8, '') AS repo_sha8,
          stack_id,
          url
`

type UpsertExactGateProfileParams struct {
	RepoID  string `json:"repo_id"`
	RepoSha string `json:"repo_sha"`
	StackID int64  `json:"stack_id"`
	Url     string `json:"url"`
}

type UpsertExactGateProfileRow struct {
	ID       int64  `json:"id"`
	RepoID   string `json:"repo_id"`
	RepoSha  string `json:"repo_sha"`
	RepoSha8 string `json:"repo_sha8"`
	StackID  int64  `json:"stack_id"`
	Url      string `json:"url"`
}

func (q *Queries) UpsertExactGateProfile(ctx context.Context, arg UpsertExactGateProfileParams) (UpsertExactGateProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertExactGateProfile,
		arg.RepoID,
		arg.RepoSha,
		arg.StackID,
		arg.Url,
	)
	var i UpsertExactGateProfileRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RepoSha,
		&i.RepoSha8,
		&i.StackID,
		&i.Url,
	)
	return i, err
}

const upsertGateJobProfileLink = `-- name: UpsertGateJobProfileLink :exec
INSERT INTO gates (job_id, profile_id)
VALUES ($1, $2)
ON CONFLICT (job_id)
DO UPDATE SET profile_id = EXCLUDED.profile_id
`

type UpsertGateJobProfileLinkParams struct {
	JobID     string `json:"job_id"`
	ProfileID int64  `json:"profile_id"`
}

func (q *Queries) UpsertGateJobProfileLink(ctx context.Context, arg UpsertGateJobProfileLinkParams) error {
	_, err := q.db.Exec(ctx, upsertGateJobProfileLink, arg.JobID, arg.ProfileID)
	return err
}
