// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hooks_once.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const getHookOnceLedger = `-- name: GetHookOnceLedger :one
SELECT
  run_id,
  repo_id,
  hook_hash,
  first_success_job_id,
  last_success_job_id,
  last_skip_job_id,
  once_skip_marked,
  created_at,
  updated_at
FROM hooks_once
WHERE run_id = $1
  AND repo_id = $2
  AND hook_hash = $3
`

type GetHookOnceLedgerParams struct {
	RunID    types.RunID  `json:"run_id"`
	RepoID   types.RepoID `json:"repo_id"`
	HookHash string       `json:"hook_hash"`
}

func (q *Queries) GetHookOnceLedger(ctx context.Context, arg GetHookOnceLedgerParams) (HooksOnce, error) {
	row := q.db.QueryRow(ctx, getHookOnceLedger, arg.RunID, arg.RepoID, arg.HookHash)
	var i HooksOnce
	err := row.Scan(
		&i.RunID,
		&i.RepoID,
		&i.HookHash,
		&i.FirstSuccessJobID,
		&i.LastSuccessJobID,
		&i.LastSkipJobID,
		&i.OnceSkipMarked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasHookOnceLedger = `-- name: HasHookOnceLedger :one
SELECT EXISTS (
  SELECT 1
  FROM hooks_once
  WHERE run_id = $1
    AND repo_id = $2
    AND hook_hash = $3
)
`

type HasHookOnceLedgerParams struct {
	RunID    types.RunID  `json:"run_id"`
	RepoID   types.RepoID `json:"repo_id"`
	HookHash string       `json:"hook_hash"`
}

func (q *Queries) HasHookOnceLedger(ctx context.Context, arg HasHookOnceLedgerParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasHookOnceLedger, arg.RunID, arg.RepoID, arg.HookHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listHookOnceLedgerByRunRepo = `-- name: ListHookOnceLedgerByRunRepo :many
SELECT
  run_id,
  repo_id,
  hook_hash,
  first_success_job_id,
  last_success_job_id,
  last_skip_job_id,
  once_skip_marked,
  created_at,
  updated_at
FROM hooks_once
WHERE run_id = $1
  AND repo_id = $2
ORDER BY hook_hash ASC
`

type ListHookOnceLedgerByRunRepoParams struct {
	RunID  types.RunID  `json:"run_id"`
	RepoID types.RepoID `json:"repo_id"`
}

func (q *Queries) ListHookOnceLedgerByRunRepo(ctx context.Context, arg ListHookOnceLedgerByRunRepoParams) ([]HooksOnce, error) {
	rows, err := q.db.Query(ctx, listHookOnceLedgerByRunRepo, arg.RunID, arg.RepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HooksOnce{}
	for rows.Next() {
		var i HooksOnce
		if err := rows.Scan(
			&i.RunID,
			&i.RepoID,
			&i.HookHash,
			&i.FirstSuccessJobID,
			&i.LastSuccessJobID,
			&i.LastSkipJobID,
			&i.OnceSkipMarked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHookOnceSkipped = `-- name: MarkHookOnceSkipped :exec
INSERT INTO hooks_once (
  run_id,
  repo_id,
  hook_hash,
  last_skip_job_id,
  once_skip_marked
) VALUES (
  $1, $2, $3, $4, true
)
ON CONFLICT (run_id, repo_id, hook_hash)
DO UPDATE
SET once_skip_marked = true,
    last_skip_job_id = EXCLUDED.last_skip_job_id,
    updated_at = now()
`

type MarkHookOnceSkippedParams struct {
	RunID         types.RunID  `json:"run_id"`
	RepoID        types.RepoID `json:"repo_id"`
	HookHash      string       `json:"hook_hash"`
	LastSkipJobID *types.JobID `json:"last_skip_job_id"`
}

func (q *Queries) MarkHookOnceSkipped(ctx context.Context, arg MarkHookOnceSkippedParams) error {
	_, err := q.db.Exec(ctx, markHookOnceSkipped,
		arg.RunID,
		arg.RepoID,
		arg.HookHash,
		arg.LastSkipJobID,
	)
	return err
}

const upsertHookOnceSuccess = `-- name: UpsertHookOnceSuccess :exec
INSERT INTO hooks_once (
  run_id,
  repo_id,
  hook_hash,
  first_success_job_id,
  last_success_job_id
) VALUES (
  $1, $2, $3, $4, $4
)
ON CONFLICT (run_id, repo_id, hook_hash)
DO UPDATE
SET last_success_job_id = EXCLUDED.last_success_job_id,
    updated_at = now()
`

type UpsertHookOnceSuccessParams struct {
	RunID             types.RunID  `json:"run_id"`
	RepoID            types.RepoID `json:"repo_id"`
	HookHash          string       `json:"hook_hash"`
	FirstSuccessJobID *types.JobID `json:"first_success_job_id"`
}

func (q *Queries) UpsertHookOnceSuccess(ctx context.Context, arg UpsertHookOnceSuccessParams) error {
	_, err := q.db.Exec(ctx, upsertHookOnceSuccess,
		arg.RunID,
		arg.RepoID,
		arg.HookHash,
		arg.FirstSuccessJobID,
	)
	return err
}
