// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_metrics.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const upsertJobMetric = `-- name: UpsertJobMetric :exec
INSERT INTO job_metrics (
  node_id,
  job_id,
  cpu_consumed_ns,
  disk_consumed_bytes,
  mem_consumed_bytes
) VALUES (
  $1, $2, $3, $4, $5
)
ON CONFLICT (job_id) DO UPDATE
SET
  node_id = EXCLUDED.node_id,
  cpu_consumed_ns = EXCLUDED.cpu_consumed_ns,
  disk_consumed_bytes = EXCLUDED.disk_consumed_bytes,
  mem_consumed_bytes = EXCLUDED.mem_consumed_bytes
`

type UpsertJobMetricParams struct {
	NodeID            types.NodeID `json:"node_id"`
	JobID             types.JobID  `json:"job_id"`
	CpuConsumedNs     int64        `json:"cpu_consumed_ns"`
	DiskConsumedBytes int64        `json:"disk_consumed_bytes"`
	MemConsumedBytes  int64        `json:"mem_consumed_bytes"`
}

func (q *Queries) UpsertJobMetric(ctx context.Context, arg UpsertJobMetricParams) error {
	_, err := q.db.Exec(ctx, upsertJobMetric,
		arg.NodeID,
		arg.JobID,
		arg.CpuConsumedNs,
		arg.DiskConsumedBytes,
		arg.MemConsumedBytes,
	)
	return err
}
