// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveJobsByRun = `-- name: CancelActiveJobsByRun :execrows
UPDATE jobs
SET status = 'Cancelled',
    finished_at = COALESCE(finished_at, now()),
    duration_ms = CASE
      WHEN started_at IS NULL THEN 0
      ELSE GREATEST(EXTRACT(EPOCH FROM (COALESCE(finished_at, now()) - started_at)) * 1000, 0)::BIGINT
    END
WHERE run_id = $1
  AND status IN ('Created', 'Queued', 'Running')
`

// Bulk-cancels active jobs for a run (Created/Queued/Running -> Cancelled).
// finished_at is set once; duration_ms is computed from started_at when present.
func (q *Queries) CancelActiveJobsByRun(ctx context.Context, runID types.RunID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelActiveJobsByRun, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelActiveJobsByRunRepoAttempt = `-- name: CancelActiveJobsByRunRepoAttempt :execrows
UPDATE jobs
SET status = 'Cancelled',
    finished_at = COALESCE(finished_at, now()),
    duration_ms = CASE
      WHEN started_at IS NULL THEN 0
      ELSE GREATEST(EXTRACT(EPOCH FROM (COALESCE(finished_at, now()) - started_at)) * 1000, 0)::BIGINT
    END
WHERE run_id = $1
  AND repo_id = $2
  AND attempt = $3
  AND status IN ('Created', 'Queued', 'Running')
`

type CancelActiveJobsByRunRepoAttemptParams struct {
	RunID   types.RunID  `json:"run_id"`
	RepoID  types.RepoID `json:"repo_id"`
	Attempt int32        `json:"attempt"`
}

// Bulk-cancels active jobs for a specific repo attempt.
// Targets Created/Queued/Running and preserves terminal jobs.
// finished_at is set once; duration_ms is computed from started_at when present.
func (q *Queries) CancelActiveJobsByRunRepoAttempt(ctx context.Context, arg CancelActiveJobsByRunRepoAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelActiveJobsByRunRepoAttempt, arg.RunID, arg.RepoID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimJob = `-- name: ClaimJob :one
WITH eligible AS (
  SELECT j.id, n.id AS node_id
  FROM nodes n
  JOIN jobs j ON TRUE
  JOIN runs r ON j.run_id = r.id
  WHERE n.id = $1
    AND $1::TEXT != ''
    AND j.status = 'Queued'
    AND j.node_id IS NULL
    AND r.status = 'Started'
  ORDER BY j.run_id ASC, j.repo_id ASC, j.attempt ASC, j.id ASC
  FOR UPDATE OF j SKIP LOCKED
  LIMIT 1
)
UPDATE jobs
SET status = 'Running', node_id = eligible.node_id, started_at = now()
FROM eligible
WHERE jobs.id = eligible.id
RETURNING jobs.id, jobs.run_id, jobs.repo_id, jobs.repo_base_ref, jobs.attempt, jobs.name, jobs.status, jobs.job_type, jobs.job_image, jobs.next_id, jobs.node_id, jobs.exit_code, jobs.started_at, jobs.finished_at, jobs.duration_ms, jobs.repo_sha_in, jobs.repo_sha_out, jobs.repo_sha_in8, jobs.repo_sha_out8, jobs.cache_key, jobs.meta
`

// Atomically claim the next claimable job for a node (unified queue).
// v1:
// - claimable jobs have status='Queued'
// - jobs are claimable only when runs.status='Started'
// - nodeID must be non-empty
func (q *Queries) ClaimJob(ctx context.Context, nodeID types.NodeID) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, nodeID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.RepoBaseRef,
		&i.Attempt,
		&i.Name,
		&i.Status,
		&i.JobType,
		&i.JobImage,
		&i.NextID,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.RepoShaIn,
		&i.RepoShaOut,
		&i.RepoShaIn8,
		&i.RepoShaOut8,
		&i.CacheKey,
		&i.Meta,
	)
	return i, err
}

const clearRepoSHAChainFromJob = `-- name: ClearRepoSHAChainFromJob :execrows
WITH RECURSIVE chain AS (
  SELECT j.id, j.next_id
  FROM jobs j
  WHERE j.id = $1
    AND j.run_id = $2
    AND j.repo_id = $3
    AND j.attempt = $4
    AND j.status IN ('Created', 'Queued')
  UNION ALL
  SELECT n.id, n.next_id
  FROM jobs n
  JOIN chain c ON n.id = c.next_id
  WHERE n.run_id = $2
    AND n.repo_id = $3
    AND n.attempt = $4
    AND n.status IN ('Created', 'Queued')
)
UPDATE jobs AS j
SET repo_sha_in = '',
    repo_sha_out = '',
    repo_sha_in8 = '',
    repo_sha_out8 = ''
FROM chain
WHERE j.id = chain.id
`

type ClearRepoSHAChainFromJobParams struct {
	ID      types.JobID  `json:"id"`
	RunID   types.RunID  `json:"run_id"`
	RepoID  types.RepoID `json:"repo_id"`
	Attempt int32        `json:"attempt"`
}

func (q *Queries) ClearRepoSHAChainFromJob(ctx context.Context, arg ClearRepoSHAChainFromJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearRepoSHAChainFromJob,
		arg.ID,
		arg.RunID,
		arg.RepoID,
		arg.Attempt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countJobsByRun = `-- name: CountJobsByRun :one
SELECT COUNT(*) FROM jobs
WHERE run_id = $1
`

func (q *Queries) CountJobsByRun(ctx context.Context, runID types.RunID) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByRun, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByRunAndStatus = `-- name: CountJobsByRunAndStatus :one
SELECT COUNT(*) FROM jobs
WHERE run_id = $1 AND status = $2
`

type CountJobsByRunAndStatusParams struct {
	RunID  types.RunID     `json:"run_id"`
	Status types.JobStatus `json:"status"`
}

func (q *Queries) CountJobsByRunAndStatus(ctx context.Context, arg CountJobsByRunAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByRunAndStatus, arg.RunID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByRunRepoAttemptGroupByStatus = `-- name: CountJobsByRunRepoAttemptGroupByStatus :many
SELECT status, COUNT(*)::int AS count
FROM jobs
WHERE run_id = $1
  AND repo_id = $2
  AND attempt = $3
GROUP BY status
`

type CountJobsByRunRepoAttemptGroupByStatusParams struct {
	RunID   types.RunID  `json:"run_id"`
	RepoID  types.RepoID `json:"repo_id"`
	Attempt int32        `json:"attempt"`
}

type CountJobsByRunRepoAttemptGroupByStatusRow struct {
	Status types.JobStatus `json:"status"`
	Count  int32           `json:"count"`
}

// Counts jobs by status for a specific repo attempt.
// Used by repo-scoped terminal detection to determine run_repos.status.
func (q *Queries) CountJobsByRunRepoAttemptGroupByStatus(ctx context.Context, arg CountJobsByRunRepoAttemptGroupByStatusParams) ([]CountJobsByRunRepoAttemptGroupByStatusRow, error) {
	rows, err := q.db.Query(ctx, countJobsByRunRepoAttemptGroupByStatus, arg.RunID, arg.RepoID, arg.Attempt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountJobsByRunRepoAttemptGroupByStatusRow{}
	for rows.Next() {
		var i CountJobsByRunRepoAttemptGroupByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countJobsForTUI = `-- name: CountJobsForTUI :one
SELECT COUNT(jobs.id)::BIGINT
FROM jobs
JOIN runs ON jobs.run_id = runs.id
JOIN migs ON runs.mig_id = migs.id
WHERE ($1::text IS NULL OR jobs.run_id = $1::text)
`

// Counts jobs with optional run_id filter.
// run_id: if non-null, count jobs for that run; if null, count all jobs.
// Used with ListJobsForTUI to provide total for TUI pagination.
func (q *Queries) CountJobsForTUI(ctx context.Context, runID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsForTUI, runID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countStaleNodesWithRunningJobs = `-- name: CountStaleNodesWithRunningJobs :one
SELECT COUNT(DISTINCT jobs.node_id)::BIGINT
FROM jobs
JOIN nodes ON nodes.id = jobs.node_id
WHERE jobs.status = 'Running'
  AND (
    nodes.last_heartbeat IS NULL
    OR nodes.last_heartbeat < $1
  )
`

// Counts distinct stale nodes that currently have at least one running job.
// Excludes NULL node_id rows (orphaned running jobs) from node count.
func (q *Queries) CountStaleNodesWithRunningJobs(ctx context.Context, lastHeartbeat pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, countStaleNodesWithRunningJobs, lastHeartbeat)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  id,
  run_id,
  repo_id,
  repo_base_ref,
  attempt,
  name,
  status,
  job_type,
  job_image,
  next_id,
  meta,
  repo_sha_in,
  repo_sha_in8
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
  CASE WHEN $12::TEXT = '' THEN '' ELSE SUBSTRING($12::TEXT, 1, 8) END
)
RETURNING
  id,
  run_id,
  repo_id,
  repo_base_ref,
  attempt,
  name,
  status,
  job_type,
  job_image,
  next_id,
  node_id,
  exit_code,
  started_at,
  finished_at,
  duration_ms,
  repo_sha_in,
  repo_sha_out,
  repo_sha_in8,
  repo_sha_out8,
  cache_key,
  meta
`

type CreateJobParams struct {
	ID          types.JobID     `json:"id"`
	RunID       types.RunID     `json:"run_id"`
	RepoID      types.RepoID    `json:"repo_id"`
	RepoBaseRef string          `json:"repo_base_ref"`
	Attempt     int32           `json:"attempt"`
	Name        string          `json:"name"`
	Status      types.JobStatus `json:"status"`
	JobType     types.JobType   `json:"job_type"`
	JobImage    string          `json:"job_image"`
	NextID      *types.JobID    `json:"next_id"`
	Meta        []byte          `json:"meta"`
	RepoShaIn   string          `json:"repo_sha_in"`
}

// Note: `id` is a required TEXT parameter (KSUID-backed); caller generates via types.NewJobID().
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.RunID,
		arg.RepoID,
		arg.RepoBaseRef,
		arg.Attempt,
		arg.Name,
		arg.Status,
		arg.JobType,
		arg.JobImage,
		arg.NextID,
		arg.Meta,
		arg.RepoShaIn,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.RepoBaseRef,
		&i.Attempt,
		&i.Name,
		&i.Status,
		&i.JobType,
		&i.JobImage,
		&i.NextID,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.RepoShaIn,
		&i.RepoShaOut,
		&i.RepoShaIn8,
		&i.RepoShaOut8,
		&i.CacheKey,
		&i.Meta,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id types.JobID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getAdjacentJobIndices = `-- name: GetAdjacentJobIndices :one
SELECT
  j1.id AS prev_id,
  j1.next_id AS next_id
FROM jobs j1
WHERE j1.id = $1
`

type GetAdjacentJobIndicesRow struct {
	PrevID types.JobID  `json:"prev_id"`
	NextID *types.JobID `json:"next_id"`
}

// Transitional: returns current job id and linked successor id.
func (q *Queries) GetAdjacentJobIndices(ctx context.Context, id types.JobID) (GetAdjacentJobIndicesRow, error) {
	row := q.db.QueryRow(ctx, getAdjacentJobIndices, id)
	var i GetAdjacentJobIndicesRow
	err := row.Scan(&i.PrevID, &i.NextID)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT
  id,
  run_id,
  repo_id,
  repo_base_ref,
  attempt,
  name,
  status,
  job_type,
  job_image,
  next_id,
  node_id,
  exit_code,
  started_at,
  finished_at,
  duration_ms,
  repo_sha_in,
  repo_sha_out,
  repo_sha_in8,
  repo_sha_out8,
  cache_key,
  meta
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id types.JobID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.RepoBaseRef,
		&i.Attempt,
		&i.Name,
		&i.Status,
		&i.JobType,
		&i.JobImage,
		&i.NextID,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.RepoShaIn,
		&i.RepoShaOut,
		&i.RepoShaIn8,
		&i.RepoShaOut8,
		&i.CacheKey,
		&i.Meta,
	)
	return i, err
}

const listCreatedJobsByRunRepoAttempt = `-- name: ListCreatedJobsByRunRepoAttempt :many
SELECT
  id,
  run_id,
  repo_id,
  repo_base_ref,
  attempt,
  name,
  status,
  job_type,
  job_image,
  next_id,
  node_id,
  exit_code,
  started_at,
  finished_at,
  duration_ms,
  repo_sha_in,
  repo_sha_out,
  repo_sha_in8,
  repo_sha_out8,
  cache_key,
  meta
FROM jobs
WHERE run_id = $1 AND repo_id = $2 AND attempt = $3 AND status = 'Created'
ORDER BY id ASC
`

type ListCreatedJobsByRunRepoAttemptParams struct {
	RunID   types.RunID  `json:"run_id"`
	RepoID  types.RepoID `json:"repo_id"`
	Attempt int32        `json:"attempt"`
}

func (q *Queries) ListCreatedJobsByRunRepoAttempt(ctx context.Context, arg ListCreatedJobsByRunRepoAttemptParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listCreatedJobsByRunRepoAttempt, arg.RunID, arg.RepoID, arg.Attempt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RepoID,
			&i.RepoBaseRef,
			&i.Attempt,
			&i.Name,
			&i.Status,
			&i.JobType,
			&i.JobImage,
			&i.NextID,
			&i.NodeID,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.RepoShaIn,
			&i.RepoShaOut,
			&i.RepoShaIn8,
			&i.RepoShaOut8,
			&i.CacheKey,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByRun = `-- name: ListJobsByRun :many
SELECT
  id,
  run_id,
  repo_id,
  repo_base_ref,
  attempt,
  name,
  status,
  job_type,
  job_image,
  next_id,
  node_id,
  exit_code,
  started_at,
  finished_at,
  duration_ms,
  repo_sha_in,
  repo_sha_out,
  repo_sha_in8,
  repo_sha_out8,
  cache_key,
  meta
FROM jobs
WHERE run_id = $1
ORDER BY repo_id ASC, attempt ASC, id ASC
`

func (q *Queries) ListJobsByRun(ctx context.Context, runID types.RunID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RepoID,
			&i.RepoBaseRef,
			&i.Attempt,
			&i.Name,
			&i.Status,
			&i.JobType,
			&i.JobImage,
			&i.NextID,
			&i.NodeID,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.RepoShaIn,
			&i.RepoShaOut,
			&i.RepoShaIn8,
			&i.RepoShaOut8,
			&i.CacheKey,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByRunRepoAttempt = `-- name: ListJobsByRunRepoAttempt :many
SELECT
  id,
  run_id,
  repo_id,
  repo_base_ref,
  attempt,
  name,
  status,
  job_type,
  job_image,
  next_id,
  node_id,
  exit_code,
  started_at,
  finished_at,
  duration_ms,
  repo_sha_in,
  repo_sha_out,
  repo_sha_in8,
  repo_sha_out8,
  cache_key,
  meta
FROM jobs
WHERE run_id = $1 AND repo_id = $2 AND attempt = $3
ORDER BY id ASC
`

type ListJobsByRunRepoAttemptParams struct {
	RunID   types.RunID  `json:"run_id"`
	RepoID  types.RepoID `json:"repo_id"`
	Attempt int32        `json:"attempt"`
}

func (q *Queries) ListJobsByRunRepoAttempt(ctx context.Context, arg ListJobsByRunRepoAttemptParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByRunRepoAttempt, arg.RunID, arg.RepoID, arg.Attempt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RepoID,
			&i.RepoBaseRef,
			&i.Attempt,
			&i.Name,
			&i.Status,
			&i.JobType,
			&i.JobImage,
			&i.NextID,
			&i.NodeID,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.RepoShaIn,
			&i.RepoShaOut,
			&i.RepoShaIn8,
			&i.RepoShaOut8,
			&i.CacheKey,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsForTUI = `-- name: ListJobsForTUI :many
SELECT
  jobs.id AS job_id,
  jobs.name,
  jobs.job_type,
  jobs.status,
  jobs.duration_ms,
  jobs.job_image,
  jobs.node_id,
  migs.name AS mig_name,
  jobs.run_id,
  jobs.repo_id
FROM jobs
JOIN runs ON jobs.run_id = runs.id
JOIN migs ON runs.mig_id = migs.id
WHERE ($3::text IS NULL OR jobs.run_id = $3::text)
ORDER BY jobs.id DESC
LIMIT $1 OFFSET $2
`

type ListJobsForTUIParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	RunID  *string `json:"run_id"`
}

type ListJobsForTUIRow struct {
	JobID      types.JobID     `json:"job_id"`
	Name       string          `json:"name"`
	JobType    types.JobType   `json:"job_type"`
	Status     types.JobStatus `json:"status"`
	DurationMs int64           `json:"duration_ms"`
	JobImage   string          `json:"job_image"`
	NodeID     *types.NodeID   `json:"node_id"`
	MigName    string          `json:"mig_name"`
	RunID      types.RunID     `json:"run_id"`
	RepoID     types.RepoID    `json:"repo_id"`
}

// Lists jobs with optional run_id filter, ordered newest-to-oldest by job id.
// run_id: if non-null, filter to jobs for that run; if null, return all jobs.
// Joins runs and migs to surface mig_name per job for the TUI jobs-list screen.
func (q *Queries) ListJobsForTUI(ctx context.Context, arg ListJobsForTUIParams) ([]ListJobsForTUIRow, error) {
	rows, err := q.db.Query(ctx, listJobsForTUI, arg.Limit, arg.Offset, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJobsForTUIRow{}
	for rows.Next() {
		var i ListJobsForTUIRow
		if err := rows.Scan(
			&i.JobID,
			&i.Name,
			&i.JobType,
			&i.Status,
			&i.DurationMs,
			&i.JobImage,
			&i.NodeID,
			&i.MigName,
			&i.RunID,
			&i.RepoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRunningJobs = `-- name: ListStaleRunningJobs :many
SELECT
  jobs.run_id,
  jobs.repo_id,
  jobs.attempt,
  COUNT(*)::int AS running_jobs
FROM jobs
LEFT JOIN nodes ON nodes.id = jobs.node_id
WHERE jobs.status = 'Running'
  AND (
    jobs.node_id IS NULL
    OR nodes.last_heartbeat IS NULL
    OR nodes.last_heartbeat < $1
  )
GROUP BY jobs.run_id, jobs.repo_id, jobs.attempt
ORDER BY jobs.run_id ASC, jobs.repo_id ASC, jobs.attempt ASC
`

type ListStaleRunningJobsRow struct {
	RunID       types.RunID  `json:"run_id"`
	RepoID      types.RepoID `json:"repo_id"`
	Attempt     int32        `json:"attempt"`
	RunningJobs int32        `json:"running_jobs"`
}

// Lists running jobs whose assigned node is stale at the provided cutoff.
// Rows are grouped by (run_id, repo_id, attempt) for deterministic recovery processing.
func (q *Queries) ListStaleRunningJobs(ctx context.Context, lastHeartbeat pgtype.Timestamptz) ([]ListStaleRunningJobsRow, error) {
	rows, err := q.db.Query(ctx, listStaleRunningJobs, lastHeartbeat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleRunningJobsRow{}
	for rows.Next() {
		var i ListStaleRunningJobsRow
		if err := rows.Scan(
			&i.RunID,
			&i.RepoID,
			&i.Attempt,
			&i.RunningJobs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteJobByIDIfUnblocked = `-- name: PromoteJobByIDIfUnblocked :one
WITH candidate AS (
  SELECT j.id
  FROM jobs j
  WHERE j.id = $1
    AND j.status = 'Created'
    AND NOT EXISTS (
      SELECT 1
      FROM jobs p
      WHERE p.next_id = j.id
        AND p.status != 'Success'
    )
  FOR UPDATE SKIP LOCKED
)
UPDATE jobs
SET status = 'Queued'
FROM candidate
WHERE jobs.id = candidate.id
  AND jobs.status = 'Created'
RETURNING
  jobs.id,
  jobs.run_id,
  jobs.repo_id,
  jobs.repo_base_ref,
  jobs.attempt,
  jobs.name,
  jobs.status,
  jobs.job_type,
  jobs.job_image,
  jobs.next_id,
  jobs.node_id,
  jobs.exit_code,
  jobs.started_at,
  jobs.finished_at,
  jobs.duration_ms,
  jobs.repo_sha_in,
  jobs.repo_sha_out,
  jobs.repo_sha_in8,
  jobs.repo_sha_out8,
  jobs.cache_key,
  jobs.meta
`

// Atomically promote a specific linked successor job: Created -> Queued.
// The candidate is eligible only when every predecessor that points to it is Success.
func (q *Queries) PromoteJobByIDIfUnblocked(ctx context.Context, id types.JobID) (Job, error) {
	row := q.db.QueryRow(ctx, promoteJobByIDIfUnblocked, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.RepoBaseRef,
		&i.Attempt,
		&i.Name,
		&i.Status,
		&i.JobType,
		&i.JobImage,
		&i.NextID,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.RepoShaIn,
		&i.RepoShaOut,
		&i.RepoShaIn8,
		&i.RepoShaOut8,
		&i.CacheKey,
		&i.Meta,
	)
	return i, err
}

const resolveReusableJobByCacheKey = `-- name: ResolveReusableJobByCacheKey :one
SELECT
  id,
  status,
  exit_code,
  repo_sha_out,
  meta
FROM jobs
WHERE repo_id = $1
  AND job_type = $2
  AND cache_key = $3
  AND cache_key <> ''
  AND status IN ('Success', 'Fail')
  AND (
    status <> 'Fail'
    OR EXISTS (
      SELECT 1
      FROM logs
      WHERE logs.run_id = jobs.run_id
        AND logs.job_id = jobs.id
    )
  )
  AND NOT (meta ? 'cache_mirror')
ORDER BY finished_at DESC NULLS LAST, id DESC
LIMIT 1
`

type ResolveReusableJobByCacheKeyParams struct {
	RepoID   types.RepoID  `json:"repo_id"`
	JobType  types.JobType `json:"job_type"`
	CacheKey string        `json:"cache_key"`
}

type ResolveReusableJobByCacheKeyRow struct {
	ID         types.JobID     `json:"id"`
	Status     types.JobStatus `json:"status"`
	ExitCode   *int32          `json:"exit_code"`
	RepoShaOut string          `json:"repo_sha_out"`
	Meta       []byte          `json:"meta"`
}

func (q *Queries) ResolveReusableJobByCacheKey(ctx context.Context, arg ResolveReusableJobByCacheKeyParams) (ResolveReusableJobByCacheKeyRow, error) {
	row := q.db.QueryRow(ctx, resolveReusableJobByCacheKey, arg.RepoID, arg.JobType, arg.CacheKey)
	var i ResolveReusableJobByCacheKeyRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ExitCode,
		&i.RepoShaOut,
		&i.Meta,
	)
	return i, err
}

const resolveReusableSBOMByCacheKey = `-- name: ResolveReusableSBOMByCacheKey :one
SELECT
  j.id AS ref_job_id,
  j.job_image AS ref_job_image,
  ab.id::text AS ref_artifact_id
FROM jobs j
JOIN LATERAL (
  SELECT a.id
  FROM artifact_bundles a
  WHERE a.run_id = j.run_id
    AND a.job_id = j.id
    AND (a.name = 'mig-out' OR a.name IS NULL)
  ORDER BY a.created_at DESC, a.id DESC
  LIMIT 1
) ab ON true
WHERE j.repo_id = $1
  AND j.job_type = 'sbom'
  AND j.status = 'Success'
  AND j.cache_key = $2
  AND j.cache_key <> ''
  AND j.job_image <> ''
  AND NOT (j.meta ? 'cache_mirror')
ORDER BY j.finished_at DESC NULLS LAST, j.id DESC
LIMIT 1
`

type ResolveReusableSBOMByCacheKeyParams struct {
	RepoID   types.RepoID `json:"repo_id"`
	CacheKey string       `json:"cache_key"`
}

type ResolveReusableSBOMByCacheKeyRow struct {
	RefJobID      types.JobID `json:"ref_job_id"`
	RefJobImage   string      `json:"ref_job_image"`
	RefArtifactID string      `json:"ref_artifact_id"`
}

func (q *Queries) ResolveReusableSBOMByCacheKey(ctx context.Context, arg ResolveReusableSBOMByCacheKeyParams) (ResolveReusableSBOMByCacheKeyRow, error) {
	row := q.db.QueryRow(ctx, resolveReusableSBOMByCacheKey, arg.RepoID, arg.CacheKey)
	var i ResolveReusableSBOMByCacheKeyRow
	err := row.Scan(&i.RefJobID, &i.RefJobImage, &i.RefArtifactID)
	return i, err
}

const resolveReusableStepByCacheKey = `-- name: ResolveReusableStepByCacheKey :one
SELECT
  id AS ref_job_id,
  repo_sha_out AS ref_repo_sha_out
FROM jobs
WHERE repo_id = $1
  AND job_type = 'mig'
  AND status = 'Success'
  AND cache_key = $2
  AND cache_key <> ''
  AND NOT (meta ? 'cache_mirror')
  AND repo_sha_out ~ '^[0-9a-f]{40}$'
ORDER BY finished_at DESC NULLS LAST, id DESC
LIMIT 1
`

type ResolveReusableStepByCacheKeyParams struct {
	RepoID   types.RepoID `json:"repo_id"`
	CacheKey string       `json:"cache_key"`
}

type ResolveReusableStepByCacheKeyRow struct {
	RefJobID      types.JobID `json:"ref_job_id"`
	RefRepoShaOut string      `json:"ref_repo_sha_out"`
}

func (q *Queries) ResolveReusableStepByCacheKey(ctx context.Context, arg ResolveReusableStepByCacheKeyParams) (ResolveReusableStepByCacheKeyRow, error) {
	row := q.db.QueryRow(ctx, resolveReusableStepByCacheKey, arg.RepoID, arg.CacheKey)
	var i ResolveReusableStepByCacheKeyRow
	err := row.Scan(&i.RefJobID, &i.RefRepoShaOut)
	return i, err
}

const scheduleNextJob = `-- name: ScheduleNextJob :one
WITH next_job AS (
  SELECT j.id
  FROM jobs j
  WHERE j.run_id = $1
    AND j.repo_id = $2
    AND j.attempt = $3
    AND j.status = 'Created'
    AND NOT EXISTS (
      SELECT 1
      FROM jobs p
      WHERE p.run_id = j.run_id
        AND p.repo_id = j.repo_id
        AND p.attempt = j.attempt
        AND p.next_id = j.id
        AND p.status != 'Success'
    )
  ORDER BY j.id ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE jobs
SET status = 'Queued'
FROM next_job
WHERE jobs.id = next_job.id
  AND jobs.status = 'Created'
RETURNING
  jobs.id,
  jobs.run_id,
  jobs.repo_id,
  jobs.repo_base_ref,
  jobs.attempt,
  jobs.name,
  jobs.status,
  jobs.job_type,
  jobs.job_image,
  jobs.next_id,
  jobs.node_id,
  jobs.exit_code,
  jobs.started_at,
  jobs.finished_at,
  jobs.duration_ms,
  jobs.repo_sha_in,
  jobs.repo_sha_out,
  jobs.repo_sha_in8,
  jobs.repo_sha_out8,
  jobs.cache_key,
  jobs.meta
`

type ScheduleNextJobParams struct {
	RunID   types.RunID  `json:"run_id"`
	RepoID  types.RepoID `json:"repo_id"`
	Attempt int32        `json:"attempt"`
}

// Atomically promote the next unblocked job in a repo attempt: Created -> Queued.
// A created job is unblocked when all predecessor jobs that point to it are Success.
func (q *Queries) ScheduleNextJob(ctx context.Context, arg ScheduleNextJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, scheduleNextJob, arg.RunID, arg.RepoID, arg.Attempt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoID,
		&i.RepoBaseRef,
		&i.Attempt,
		&i.Name,
		&i.Status,
		&i.JobType,
		&i.JobImage,
		&i.NextID,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.RepoShaIn,
		&i.RepoShaOut,
		&i.RepoShaIn8,
		&i.RepoShaOut8,
		&i.CacheKey,
		&i.Meta,
	)
	return i, err
}

const updateJobCacheKey = `-- name: UpdateJobCacheKey :exec
UPDATE jobs
SET cache_key = $2
WHERE id = $1
`

type UpdateJobCacheKeyParams struct {
	ID       types.JobID `json:"id"`
	CacheKey string      `json:"cache_key"`
}

func (q *Queries) UpdateJobCacheKey(ctx context.Context, arg UpdateJobCacheKeyParams) error {
	_, err := q.db.Exec(ctx, updateJobCacheKey, arg.ID, arg.CacheKey)
	return err
}

const updateJobCompletion = `-- name: UpdateJobCompletion :exec
WITH completed AS (
  UPDATE jobs
  SET status = $1,
      exit_code = $2,
      repo_sha_out = CASE
        WHEN $3::TEXT = '' THEN repo_sha_out
        ELSE $3::TEXT
      END,
      repo_sha_out8 = CASE
        WHEN $3::TEXT = '' THEN repo_sha_out8
        ELSE SUBSTRING($3::TEXT, 1, 8)
      END,
      finished_at = now(),
      duration_ms = COALESCE(EXTRACT(EPOCH FROM (now() - started_at)) * 1000, 0)::BIGINT
  WHERE jobs.id = $4
  RETURNING next_id, repo_sha_out
)
UPDATE jobs AS next_job
SET repo_sha_in = CASE
      WHEN completed.repo_sha_out = '' THEN next_job.repo_sha_in
      ELSE completed.repo_sha_out
    END,
    repo_sha_in8 = CASE
      WHEN completed.repo_sha_out = '' THEN next_job.repo_sha_in8
      ELSE SUBSTRING(completed.repo_sha_out, 1, 8)
    END
FROM completed
WHERE next_job.id = completed.next_id
`

type UpdateJobCompletionParams struct {
	Status     types.JobStatus `json:"status"`
	ExitCode   *int32          `json:"exit_code"`
	RepoShaOut string          `json:"repo_sha_out"`
	ID         types.JobID     `json:"id"`
}

func (q *Queries) UpdateJobCompletion(ctx context.Context, arg UpdateJobCompletionParams) error {
	_, err := q.db.Exec(ctx, updateJobCompletion,
		arg.Status,
		arg.ExitCode,
		arg.RepoShaOut,
		arg.ID,
	)
	return err
}

const updateJobCompletionWithMeta = `-- name: UpdateJobCompletionWithMeta :exec
WITH completed AS (
  UPDATE jobs
  SET status = $1,
      exit_code = $2,
      repo_sha_out = CASE
        WHEN $3::TEXT = '' THEN repo_sha_out
        ELSE $3::TEXT
      END,
      repo_sha_out8 = CASE
        WHEN $3::TEXT = '' THEN repo_sha_out8
        ELSE SUBSTRING($3::TEXT, 1, 8)
      END,
      finished_at = now(),
      duration_ms = COALESCE(EXTRACT(EPOCH FROM (now() - started_at)) * 1000, 0)::BIGINT,
      meta = $4
  WHERE jobs.id = $5
  RETURNING next_id, repo_sha_out
)
UPDATE jobs AS next_job
SET repo_sha_in = CASE
      WHEN completed.repo_sha_out = '' THEN next_job.repo_sha_in
      ELSE completed.repo_sha_out
    END,
    repo_sha_in8 = CASE
      WHEN completed.repo_sha_out = '' THEN next_job.repo_sha_in8
      ELSE SUBSTRING(completed.repo_sha_out, 1, 8)
    END
FROM completed
WHERE next_job.id = completed.next_id
`

type UpdateJobCompletionWithMetaParams struct {
	Status     types.JobStatus `json:"status"`
	ExitCode   *int32          `json:"exit_code"`
	RepoShaOut string          `json:"repo_sha_out"`
	Meta       []byte          `json:"meta"`
	ID         types.JobID     `json:"id"`
}

func (q *Queries) UpdateJobCompletionWithMeta(ctx context.Context, arg UpdateJobCompletionWithMetaParams) error {
	_, err := q.db.Exec(ctx, updateJobCompletionWithMeta,
		arg.Status,
		arg.ExitCode,
		arg.RepoShaOut,
		arg.Meta,
		arg.ID,
	)
	return err
}

const updateJobImageName = `-- name: UpdateJobImageName :exec
UPDATE jobs
SET job_image = $2
WHERE id = $1
`

type UpdateJobImageNameParams struct {
	ID       types.JobID `json:"id"`
	JobImage string      `json:"job_image"`
}

// Persist the container image name used to execute a job.
// This is set by the node immediately before job execution starts.
func (q *Queries) UpdateJobImageName(ctx context.Context, arg UpdateJobImageNameParams) error {
	_, err := q.db.Exec(ctx, updateJobImageName, arg.ID, arg.JobImage)
	return err
}

const updateJobMeta = `-- name: UpdateJobMeta :exec
UPDATE jobs
SET meta = $2
WHERE id = $1
`

type UpdateJobMetaParams struct {
	ID   types.JobID `json:"id"`
	Meta []byte      `json:"meta"`
}

func (q *Queries) UpdateJobMeta(ctx context.Context, arg UpdateJobMetaParams) error {
	_, err := q.db.Exec(ctx, updateJobMeta, arg.ID, arg.Meta)
	return err
}

const updateJobNextID = `-- name: UpdateJobNextID :exec
UPDATE jobs
SET next_id = $2
WHERE id = $1
`

type UpdateJobNextIDParams struct {
	ID     types.JobID  `json:"id"`
	NextID *types.JobID `json:"next_id"`
}

func (q *Queries) UpdateJobNextID(ctx context.Context, arg UpdateJobNextIDParams) error {
	_, err := q.db.Exec(ctx, updateJobNextID, arg.ID, arg.NextID)
	return err
}

const updateJobRepoSHAIn = `-- name: UpdateJobRepoSHAIn :exec
UPDATE jobs
SET repo_sha_in = $2,
    repo_sha_in8 = CASE
      WHEN $2::TEXT = '' THEN ''
      ELSE SUBSTRING($2::TEXT, 1, 8)
    END
WHERE id = $1
`

type UpdateJobRepoSHAInParams struct {
	ID        types.JobID `json:"id"`
	RepoShaIn string      `json:"repo_sha_in"`
}

func (q *Queries) UpdateJobRepoSHAIn(ctx context.Context, arg UpdateJobRepoSHAInParams) error {
	_, err := q.db.Exec(ctx, updateJobRepoSHAIn, arg.ID, arg.RepoShaIn)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = $2,
    -- started_at: set when transitioning to Running (defensive; preserves existing started_at).
    started_at = CASE
      WHEN $2 = 'Running'::job_status AND started_at IS NULL THEN now()
      WHEN $2 = 'Running'::job_status THEN started_at
      ELSE $3
    END,
    finished_at = $4,
    duration_ms = $5
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID         types.JobID        `json:"id"`
	Status     types.JobStatus    `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	DurationMs int64              `json:"duration_ms"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
	)
	return err
}
