// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
WITH eligible AS (
  SELECT j.id FROM jobs j
  WHERE j.run_id IN (SELECT id FROM runs WHERE status IN ('queued', 'running'))
    AND j.status = 'scheduled'
    AND j.node_id IS NULL
  ORDER BY j.step_index ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE jobs SET status = 'running', node_id = $1, started_at = now()
FROM eligible WHERE jobs.id = eligible.id
RETURNING jobs.id, jobs.run_id, jobs.name, jobs.status, jobs.step_index, jobs.node_id, jobs.exit_code, jobs.started_at, jobs.finished_at, jobs.duration_ms, jobs.meta
`

// Atomically claim the next scheduled job for a node.
// Server-driven scheduling: only 'scheduled' jobs are claimable.
// Job transitions directly to 'running' (no intermediate 'assigned' state).
func (q *Queries) ClaimJob(ctx context.Context, nodeID pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, nodeID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.StepIndex,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
	)
	return i, err
}

const countJobsByRun = `-- name: CountJobsByRun :one
SELECT COUNT(*) FROM jobs
WHERE run_id = $1
`

// Counts total jobs for a run.
func (q *Queries) CountJobsByRun(ctx context.Context, runID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByRun, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByRunAndStatus = `-- name: CountJobsByRunAndStatus :one
SELECT COUNT(*) FROM jobs
WHERE run_id = $1 AND status = $2
`

type CountJobsByRunAndStatusParams struct {
	RunID  pgtype.UUID `json:"run_id"`
	Status JobStatus   `json:"status"`
}

// Counts jobs for a run with a specific status.
func (q *Queries) CountJobsByRunAndStatus(ctx context.Context, arg CountJobsByRunAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByRunAndStatus, arg.RunID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (run_id, name, status, step_index, meta)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, name, status, step_index, node_id, exit_code, started_at, finished_at, duration_ms, meta
`

type CreateJobParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	Name      string      `json:"name"`
	Status    JobStatus   `json:"status"`
	StepIndex float64     `json:"step_index"`
	Meta      []byte      `json:"meta"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.RunID,
		arg.Name,
		arg.Status,
		arg.StepIndex,
		arg.Meta,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.StepIndex,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getAdjacentJobIndices = `-- name: GetAdjacentJobIndices :one
SELECT
  j1.step_index as prev_index,
  (SELECT MIN(j2.step_index) FROM jobs j2 WHERE j2.run_id = j1.run_id AND j2.step_index > j1.step_index) as next_index
FROM jobs j1 WHERE j1.id = $1
`

type GetAdjacentJobIndicesRow struct {
	PrevIndex float64     `json:"prev_index"`
	NextIndex interface{} `json:"next_index"`
}

// Get the step_index of a job and the next job's step_index for healing insertion.
// Returns prev_index (the given job's index) and next_index (the following job's index, or NULL if none).
func (q *Queries) GetAdjacentJobIndices(ctx context.Context, id pgtype.UUID) (GetAdjacentJobIndicesRow, error) {
	row := q.db.QueryRow(ctx, getAdjacentJobIndices, id)
	var i GetAdjacentJobIndicesRow
	err := row.Scan(&i.PrevIndex, &i.NextIndex)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, run_id, name, status, step_index, node_id, exit_code, started_at, finished_at, duration_ms, meta FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.StepIndex,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
	)
	return i, err
}

const listCreatedJobsByRun = `-- name: ListCreatedJobsByRun :many
SELECT id, run_id, name, status, step_index, node_id, exit_code, started_at, finished_at, duration_ms, meta FROM jobs
WHERE run_id = $1 AND status = 'created'
ORDER BY step_index ASC
`

// List all created (not yet scheduled) jobs for a run, ordered by step_index.
func (q *Queries) ListCreatedJobsByRun(ctx context.Context, runID pgtype.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listCreatedJobsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.Status,
			&i.StepIndex,
			&i.NodeID,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByRun = `-- name: ListJobsByRun :many
SELECT id, run_id, name, status, step_index, node_id, exit_code, started_at, finished_at, duration_ms, meta FROM jobs
WHERE run_id = $1
ORDER BY step_index ASC
`

func (q *Queries) ListJobsByRun(ctx context.Context, runID pgtype.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.Status,
			&i.StepIndex,
			&i.NodeID,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleNextJob = `-- name: ScheduleNextJob :one
UPDATE jobs SET status = 'scheduled'
WHERE id = (
  SELECT j.id FROM jobs j
  WHERE j.run_id = $1 AND j.status = 'created'
  ORDER BY j.step_index ASC
  LIMIT 1
)
RETURNING id, run_id, name, status, step_index, node_id, exit_code, started_at, finished_at, duration_ms, meta
`

// Transitions the first 'created' job to 'scheduled' for a run.
// Called by server after a job completes successfully to enable server-driven scheduling.
// Returns the scheduled job, or null if no more jobs to schedule.
func (q *Queries) ScheduleNextJob(ctx context.Context, runID pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, scheduleNextJob, runID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.StepIndex,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
	)
	return i, err
}

const updateJobCompletion = `-- name: UpdateJobCompletion :exec
UPDATE jobs
SET status = $2, exit_code = $3, finished_at = now(),
    duration_ms = EXTRACT(EPOCH FROM (now() - started_at)) * 1000
WHERE id = $1
`

type UpdateJobCompletionParams struct {
	ID       pgtype.UUID `json:"id"`
	Status   JobStatus   `json:"status"`
	ExitCode *int32      `json:"exit_code"`
}

// Updates a job's terminal status, exit code, and timing.
func (q *Queries) UpdateJobCompletion(ctx context.Context, arg UpdateJobCompletionParams) error {
	_, err := q.db.Exec(ctx, updateJobCompletion, arg.ID, arg.Status, arg.ExitCode)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = $2, started_at = $3, finished_at = $4, duration_ms = $5
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     JobStatus          `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	DurationMs int64              `json:"duration_ms"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
	)
	return err
}
