// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
WITH eligible AS (
  SELECT j.id FROM jobs j
  WHERE j.run_id IN (SELECT id FROM runs WHERE status IN ('queued', 'running'))
    AND j.status = 'pending'
    AND j.node_id IS NULL
  ORDER BY j.step_index ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE jobs SET status = 'running', node_id = $1, started_at = now()
FROM eligible WHERE jobs.id = eligible.id
RETURNING jobs.id, jobs.run_id, jobs.name, jobs.status, jobs.mod_type, jobs.mod_image, jobs.step_index, jobs.node_id, jobs.exit_code, jobs.started_at, jobs.finished_at, jobs.duration_ms, jobs.meta
`

// Atomically claim the next pending job for a node (single unified queue).
// Jobs are ordered by step_index; no special handling for gate vs mod jobs.
// Server-driven scheduling: only 'pending' jobs are claimable.
// Job transitions directly to 'running' (no intermediate 'assigned' state).
func (q *Queries) ClaimJob(ctx context.Context, nodeID *string) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, nodeID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.ModType,
		&i.ModImage,
		&i.StepIndex,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
	)
	return i, err
}

const countJobsByRun = `-- name: CountJobsByRun :one
SELECT COUNT(*) FROM jobs
WHERE run_id = $1
`

// Counts total jobs for a run.
func (q *Queries) CountJobsByRun(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByRun, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobsByRunAndStatus = `-- name: CountJobsByRunAndStatus :one
SELECT COUNT(*) FROM jobs
WHERE run_id = $1 AND status = $2
`

type CountJobsByRunAndStatusParams struct {
	RunID  string    `json:"run_id"`
	Status JobStatus `json:"status"`
}

// Counts jobs for a run with a specific status.
func (q *Queries) CountJobsByRunAndStatus(ctx context.Context, arg CountJobsByRunAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobsByRunAndStatus, arg.RunID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (id, run_id, name, status, mod_type, mod_image, step_index, meta)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, run_id, name, status, mod_type, mod_image, step_index, node_id, exit_code, started_at, finished_at, duration_ms, meta
`

type CreateJobParams struct {
	ID        string    `json:"id"`
	RunID     string    `json:"run_id"`
	Name      string    `json:"name"`
	Status    JobStatus `json:"status"`
	ModType   string    `json:"mod_type"`
	ModImage  string    `json:"mod_image"`
	StepIndex float64   `json:"step_index"`
	Meta      []byte    `json:"meta"`
}

// Note: `id` is now a required TEXT parameter (KSUID-backed); caller generates via types.NewJobID().
func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.ID,
		arg.RunID,
		arg.Name,
		arg.Status,
		arg.ModType,
		arg.ModImage,
		arg.StepIndex,
		arg.Meta,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.ModType,
		&i.ModImage,
		&i.StepIndex,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) DeleteJob(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteJob, id)
	return err
}

const getAdjacentJobIndices = `-- name: GetAdjacentJobIndices :one
SELECT
  j1.step_index as prev_index,
  (SELECT MIN(j2.step_index) FROM jobs j2 WHERE j2.run_id = j1.run_id AND j2.step_index > j1.step_index) as next_index
FROM jobs j1 WHERE j1.id = $1
`

type GetAdjacentJobIndicesRow struct {
	PrevIndex float64     `json:"prev_index"`
	NextIndex interface{} `json:"next_index"`
}

// Get the step_index of a job and the next job's step_index for healing insertion.
// Returns prev_index (the given job's index) and next_index (the following job's index, or NULL if none).
func (q *Queries) GetAdjacentJobIndices(ctx context.Context, id string) (GetAdjacentJobIndicesRow, error) {
	row := q.db.QueryRow(ctx, getAdjacentJobIndices, id)
	var i GetAdjacentJobIndicesRow
	err := row.Scan(&i.PrevIndex, &i.NextIndex)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, run_id, name, status, mod_type, mod_image, step_index, node_id, exit_code, started_at, finished_at, duration_ms, meta
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.ModType,
		&i.ModImage,
		&i.StepIndex,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
	)
	return i, err
}

const listCreatedJobsByRun = `-- name: ListCreatedJobsByRun :many
SELECT id, run_id, name, status, mod_type, mod_image, step_index, node_id, exit_code, started_at, finished_at, duration_ms, meta
FROM jobs
WHERE run_id = $1 AND status = 'created'
ORDER BY step_index ASC
`

// List all created (not yet pending) jobs for a run, ordered by step_index.
func (q *Queries) ListCreatedJobsByRun(ctx context.Context, runID string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listCreatedJobsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.Status,
			&i.ModType,
			&i.ModImage,
			&i.StepIndex,
			&i.NodeID,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByRun = `-- name: ListJobsByRun :many
SELECT id, run_id, name, status, mod_type, mod_image, step_index, node_id, exit_code, started_at, finished_at, duration_ms, meta
FROM jobs
WHERE run_id = $1
ORDER BY step_index ASC
`

func (q *Queries) ListJobsByRun(ctx context.Context, runID string) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.Status,
			&i.ModType,
			&i.ModImage,
			&i.StepIndex,
			&i.NodeID,
			&i.ExitCode,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleNextJob = `-- name: ScheduleNextJob :one
UPDATE jobs SET status = 'pending'
WHERE id = (
  SELECT j.id FROM jobs j
  WHERE j.run_id = $1 AND j.status = 'created'
  ORDER BY j.step_index ASC
  LIMIT 1
)
RETURNING id, run_id, name, status, mod_type, mod_image, step_index, node_id, exit_code, started_at, finished_at, duration_ms, meta
`

// Transitions the first 'created' job to 'pending' for a run.
// Called by server after a job completes successfully to enable server-driven scheduling.
// Returns the pending job, or null if no more jobs to schedule.
func (q *Queries) ScheduleNextJob(ctx context.Context, runID string) (Job, error) {
	row := q.db.QueryRow(ctx, scheduleNextJob, runID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.ModType,
		&i.ModImage,
		&i.StepIndex,
		&i.NodeID,
		&i.ExitCode,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
	)
	return i, err
}

const updateJobCompletion = `-- name: UpdateJobCompletion :exec
UPDATE jobs
SET status = $2, exit_code = $3, finished_at = now(),
    duration_ms = EXTRACT(EPOCH FROM (now() - started_at)) * 1000
WHERE id = $1
`

type UpdateJobCompletionParams struct {
	ID       string    `json:"id"`
	Status   JobStatus `json:"status"`
	ExitCode *int32    `json:"exit_code"`
}

// Updates a job's terminal status, exit code, and timing.
func (q *Queries) UpdateJobCompletion(ctx context.Context, arg UpdateJobCompletionParams) error {
	_, err := q.db.Exec(ctx, updateJobCompletion, arg.ID, arg.Status, arg.ExitCode)
	return err
}

const updateJobCompletionWithMeta = `-- name: UpdateJobCompletionWithMeta :exec
UPDATE jobs
SET status = $2, exit_code = $3, finished_at = now(),
    duration_ms = EXTRACT(EPOCH FROM (now() - started_at)) * 1000,
    meta = $4
WHERE id = $1
`

type UpdateJobCompletionWithMetaParams struct {
	ID       string    `json:"id"`
	Status   JobStatus `json:"status"`
	ExitCode *int32    `json:"exit_code"`
	Meta     []byte    `json:"meta"`
}

// Updates a job's terminal status, exit code, timing, and meta in one operation.
// Use this when completing a gate or build job that has execution metadata.
func (q *Queries) UpdateJobCompletionWithMeta(ctx context.Context, arg UpdateJobCompletionWithMetaParams) error {
	_, err := q.db.Exec(ctx, updateJobCompletionWithMeta,
		arg.ID,
		arg.Status,
		arg.ExitCode,
		arg.Meta,
	)
	return err
}

const updateJobMeta = `-- name: UpdateJobMeta :exec
UPDATE jobs
SET meta = $2
WHERE id = $1
`

type UpdateJobMetaParams struct {
	ID   string `json:"id"`
	Meta []byte `json:"meta"`
}

// Updates a job's meta JSONB field with structured gate/build metadata.
// Used to persist gate validation results or build metrics after job execution.
// The meta parameter should be JSON-encoded JobMeta (see internal/workflow/contracts.JobMeta).
func (q *Queries) UpdateJobMeta(ctx context.Context, arg UpdateJobMetaParams) error {
	_, err := q.db.Exec(ctx, updateJobMeta, arg.ID, arg.Meta)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = $2, started_at = $3, finished_at = $4, duration_ms = $5
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID         string             `json:"id"`
	Status     JobStatus          `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	DurationMs int64              `json:"duration_ms"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
	)
	return err
}
