// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLog = `-- name: CreateLog :one
INSERT INTO logs (run_id, stage_id, build_id, chunk_no, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, run_id, stage_id, build_id, chunk_no, data, created_at
`

type CreateLogParams struct {
	RunID   pgtype.UUID `json:"run_id"`
	StageID pgtype.UUID `json:"stage_id"`
	BuildID pgtype.UUID `json:"build_id"`
	ChunkNo int32       `json:"chunk_no"`
	Data    []byte      `json:"data"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRow(ctx, createLog,
		arg.RunID,
		arg.StageID,
		arg.BuildID,
		arg.ChunkNo,
		arg.Data,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageID,
		&i.BuildID,
		&i.ChunkNo,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLog = `-- name: DeleteLog :exec
DELETE FROM logs
WHERE id = $1
`

func (q *Queries) DeleteLog(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLog, id)
	return err
}

const deleteLogsOlderThan = `-- name: DeleteLogsOlderThan :exec
DELETE FROM logs
WHERE created_at < $1
`

func (q *Queries) DeleteLogsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteLogsOlderThan, createdAt)
	return err
}

const getLog = `-- name: GetLog :one
SELECT id, run_id, stage_id, build_id, chunk_no, data, created_at FROM logs
WHERE id = $1
`

func (q *Queries) GetLog(ctx context.Context, id int64) (Log, error) {
	row := q.db.QueryRow(ctx, getLog, id)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StageID,
		&i.BuildID,
		&i.ChunkNo,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listLogsByRun = `-- name: ListLogsByRun :many
SELECT id, run_id, stage_id, build_id, chunk_no, data, created_at FROM logs
WHERE run_id = $1
ORDER BY chunk_no ASC
`

func (q *Queries) ListLogsByRun(ctx context.Context, runID pgtype.UUID) ([]Log, error) {
	rows, err := q.db.Query(ctx, listLogsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Log{}
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageID,
			&i.BuildID,
			&i.ChunkNo,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByRunAndStage = `-- name: ListLogsByRunAndStage :many
SELECT id, run_id, stage_id, build_id, chunk_no, data, created_at FROM logs
WHERE run_id = $1 AND stage_id = $2
ORDER BY chunk_no ASC
`

type ListLogsByRunAndStageParams struct {
	RunID   pgtype.UUID `json:"run_id"`
	StageID pgtype.UUID `json:"stage_id"`
}

func (q *Queries) ListLogsByRunAndStage(ctx context.Context, arg ListLogsByRunAndStageParams) ([]Log, error) {
	rows, err := q.db.Query(ctx, listLogsByRunAndStage, arg.RunID, arg.StageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Log{}
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageID,
			&i.BuildID,
			&i.ChunkNo,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsByRunStageAndBuild = `-- name: ListLogsByRunStageAndBuild :many
SELECT id, run_id, stage_id, build_id, chunk_no, data, created_at FROM logs
WHERE run_id = $1 AND stage_id = $2 AND build_id = $3
ORDER BY chunk_no ASC
`

type ListLogsByRunStageAndBuildParams struct {
	RunID   pgtype.UUID `json:"run_id"`
	StageID pgtype.UUID `json:"stage_id"`
	BuildID pgtype.UUID `json:"build_id"`
}

func (q *Queries) ListLogsByRunStageAndBuild(ctx context.Context, arg ListLogsByRunStageAndBuildParams) ([]Log, error) {
	rows, err := q.db.Query(ctx, listLogsByRunStageAndBuild, arg.RunID, arg.StageID, arg.BuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Log{}
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StageID,
			&i.BuildID,
			&i.ChunkNo,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
