// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mig_repos.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPrepRepo = `-- name: ClaimNextPrepRepo :one
WITH candidate AS (
  SELECT mr.id
  FROM mig_repos mr
  WHERE mr.prep_status = 'PrepPending'
  ORDER BY mr.prep_updated_at ASC, mr.created_at ASC, mr.id ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE mig_repos mr
SET prep_status = 'PrepRunning',
    prep_attempts = mr.prep_attempts + 1,
    prep_last_error = NULL,
    prep_failure_code = NULL,
    prep_updated_at = now()
FROM candidate
WHERE mr.id = candidate.id
  AND mr.prep_status = 'PrepPending'
RETURNING mr.id, mr.mig_id, mr.repo_url, mr.base_ref, mr.target_ref, mr.prep_status, mr.prep_attempts, mr.prep_last_error, mr.prep_failure_code, mr.prep_updated_at, mr.prep_profile, mr.prep_artifacts, mr.created_at
`

func (q *Queries) ClaimNextPrepRepo(ctx context.Context) (MigRepo, error) {
	row := q.db.QueryRow(ctx, claimNextPrepRepo)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.PrepStatus,
		&i.PrepAttempts,
		&i.PrepLastError,
		&i.PrepFailureCode,
		&i.PrepUpdatedAt,
		&i.PrepProfile,
		&i.PrepArtifacts,
		&i.CreatedAt,
	)
	return i, err
}

const claimNextPrepRetryRepo = `-- name: ClaimNextPrepRetryRepo :one
WITH candidate AS (
  SELECT mr.id
  FROM mig_repos mr
  WHERE mr.prep_status = 'PrepRetryScheduled'
    AND mr.prep_updated_at <= $1
  ORDER BY mr.prep_updated_at ASC, mr.created_at ASC, mr.id ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE mig_repos mr
SET prep_status = 'PrepRunning',
    prep_attempts = mr.prep_attempts + 1,
    prep_last_error = NULL,
    prep_failure_code = NULL,
    prep_updated_at = now()
FROM candidate
WHERE mr.id = candidate.id
  AND mr.prep_status = 'PrepRetryScheduled'
RETURNING mr.id, mr.mig_id, mr.repo_url, mr.base_ref, mr.target_ref, mr.prep_status, mr.prep_attempts, mr.prep_last_error, mr.prep_failure_code, mr.prep_updated_at, mr.prep_profile, mr.prep_artifacts, mr.created_at
`

func (q *Queries) ClaimNextPrepRetryRepo(ctx context.Context, prepUpdatedAt pgtype.Timestamptz) (MigRepo, error) {
	row := q.db.QueryRow(ctx, claimNextPrepRetryRepo, prepUpdatedAt)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.PrepStatus,
		&i.PrepAttempts,
		&i.PrepLastError,
		&i.PrepFailureCode,
		&i.PrepUpdatedAt,
		&i.PrepProfile,
		&i.PrepArtifacts,
		&i.CreatedAt,
	)
	return i, err
}

const createMigRepo = `-- name: CreateMigRepo :one
INSERT INTO mig_repos (
  id,
  mig_id,
  repo_url,
  base_ref,
  target_ref,
  prep_status,
  prep_last_error,
  prep_failure_code,
  prep_profile,
  prep_artifacts,
  prep_updated_at
)
VALUES ($1, $2, $3, $4, $5, 'PrepPending', NULL, NULL, NULL, NULL, now())
RETURNING id, mig_id, repo_url, base_ref, target_ref, prep_status, prep_attempts, prep_last_error, prep_failure_code, prep_updated_at, prep_profile, prep_artifacts, created_at
`

type CreateMigRepoParams struct {
	ID        types.MigRepoID `json:"id"`
	MigID     types.MigID     `json:"mig_id"`
	RepoUrl   string          `json:"repo_url"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

func (q *Queries) CreateMigRepo(ctx context.Context, arg CreateMigRepoParams) (MigRepo, error) {
	row := q.db.QueryRow(ctx, createMigRepo,
		arg.ID,
		arg.MigID,
		arg.RepoUrl,
		arg.BaseRef,
		arg.TargetRef,
	)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.PrepStatus,
		&i.PrepAttempts,
		&i.PrepLastError,
		&i.PrepFailureCode,
		&i.PrepUpdatedAt,
		&i.PrepProfile,
		&i.PrepArtifacts,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMigRepo = `-- name: DeleteMigRepo :exec
DELETE FROM mig_repos
WHERE id = $1
`

// Deletes a mod_repo by id.
// Note: mig_repos.id is referenced by run_repos.repo_id and jobs.repo_id with ON DELETE RESTRICT.
// This DELETE will fail if any run_repos/jobs rows still reference the repo.
func (q *Queries) DeleteMigRepo(ctx context.Context, id types.MigRepoID) error {
	_, err := q.db.Exec(ctx, deleteMigRepo, id)
	return err
}

const getMigRepo = `-- name: GetMigRepo :one
SELECT id, mig_id, repo_url, base_ref, target_ref, prep_status, prep_attempts, prep_last_error, prep_failure_code, prep_updated_at, prep_profile, prep_artifacts, created_at
FROM mig_repos
WHERE id = $1
`

func (q *Queries) GetMigRepo(ctx context.Context, id types.MigRepoID) (MigRepo, error) {
	row := q.db.QueryRow(ctx, getMigRepo, id)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.PrepStatus,
		&i.PrepAttempts,
		&i.PrepLastError,
		&i.PrepFailureCode,
		&i.PrepUpdatedAt,
		&i.PrepProfile,
		&i.PrepArtifacts,
		&i.CreatedAt,
	)
	return i, err
}

const getMigRepoByURL = `-- name: GetMigRepoByURL :one
SELECT id, mig_id, repo_url, base_ref, target_ref, prep_status, prep_attempts, prep_last_error, prep_failure_code, prep_updated_at, prep_profile, prep_artifacts, created_at
FROM mig_repos
WHERE mig_id = $1 AND repo_url = $2
`

type GetMigRepoByURLParams struct {
	MigID   types.MigID `json:"mig_id"`
	RepoUrl string      `json:"repo_url"`
}

// Gets a mod_repo by mig_id and repo_url (for uniqueness constraint enforcement).
func (q *Queries) GetMigRepoByURL(ctx context.Context, arg GetMigRepoByURLParams) (MigRepo, error) {
	row := q.db.QueryRow(ctx, getMigRepoByURL, arg.MigID, arg.RepoUrl)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.PrepStatus,
		&i.PrepAttempts,
		&i.PrepLastError,
		&i.PrepFailureCode,
		&i.PrepUpdatedAt,
		&i.PrepProfile,
		&i.PrepArtifacts,
		&i.CreatedAt,
	)
	return i, err
}

const hasMigRepoHistory = `-- name: HasMigRepoHistory :one
SELECT EXISTS(
  SELECT 1 FROM run_repos WHERE repo_id = $1 LIMIT 1
) AS has_history
`

// Checks if a mod_repo has any historical executions (run_repos references).
// Returns true if the repo cannot be deleted due to history, false otherwise.
// Deletion is refused if the repo has historical executions.
func (q *Queries) HasMigRepoHistory(ctx context.Context, repoID types.MigRepoID) (bool, error) {
	row := q.db.QueryRow(ctx, hasMigRepoHistory, repoID)
	var has_history bool
	err := row.Scan(&has_history)
	return has_history, err
}

const listDistinctRepos = `-- name: ListDistinctRepos :many
SELECT
  mr.id AS repo_id,
  mr.repo_url,
  rr.last_run_at,
  COALESCE(rr.last_status::text, '') AS last_status,
  mr.prep_status,
  mr.prep_failure_code,
  mr.prep_updated_at
FROM mig_repos mr
LEFT JOIN LATERAL (
  SELECT
    rrr.started_at AS last_run_at,
    rrr.status AS last_status
  FROM run_repos rrr
  WHERE rrr.repo_id = mr.id
  ORDER BY rrr.started_at DESC NULLS LAST, rrr.created_at DESC, rrr.run_id DESC
  LIMIT 1
) rr ON true
WHERE ($1::text IS NULL OR $1 = '' OR mr.repo_url ILIKE '%' || $1 || '%')
ORDER BY mr.repo_url ASC, mr.id ASC
`

type ListDistinctReposRow struct {
	RepoID          types.MigRepoID    `json:"repo_id"`
	RepoUrl         string             `json:"repo_url"`
	LastRunAt       pgtype.Timestamptz `json:"last_run_at"`
	LastStatus      interface{}        `json:"last_status"`
	PrepStatus      PrepStatus         `json:"prep_status"`
	PrepFailureCode *string            `json:"prep_failure_code"`
	PrepUpdatedAt   pgtype.Timestamptz `json:"prep_updated_at"`
}

// v1: Lists distinct repos (mig_repos) with last known run metadata, optionally filtered by repo_url substring.
func (q *Queries) ListDistinctRepos(ctx context.Context, filter string) ([]ListDistinctReposRow, error) {
	rows, err := q.db.Query(ctx, listDistinctRepos, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistinctReposRow{}
	for rows.Next() {
		var i ListDistinctReposRow
		if err := rows.Scan(
			&i.RepoID,
			&i.RepoUrl,
			&i.LastRunAt,
			&i.LastStatus,
			&i.PrepStatus,
			&i.PrepFailureCode,
			&i.PrepUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigReposByMig = `-- name: ListMigReposByMig :many
SELECT id, mig_id, repo_url, base_ref, target_ref, prep_status, prep_attempts, prep_last_error, prep_failure_code, prep_updated_at, prep_profile, prep_artifacts, created_at
FROM mig_repos
WHERE mig_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMigReposByMig(ctx context.Context, migID types.MigID) ([]MigRepo, error) {
	rows, err := q.db.Query(ctx, listMigReposByMig, migID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MigRepo{}
	for rows.Next() {
		var i MigRepo
		if err := rows.Scan(
			&i.ID,
			&i.MigID,
			&i.RepoUrl,
			&i.BaseRef,
			&i.TargetRef,
			&i.PrepStatus,
			&i.PrepAttempts,
			&i.PrepLastError,
			&i.PrepFailureCode,
			&i.PrepUpdatedAt,
			&i.PrepProfile,
			&i.PrepArtifacts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByPrepStatus = `-- name: ListReposByPrepStatus :many
SELECT id, mig_id, repo_url, base_ref, target_ref, prep_status, prep_attempts, prep_last_error, prep_failure_code, prep_updated_at, prep_profile, prep_artifacts, created_at
FROM mig_repos
WHERE prep_status = $1
ORDER BY prep_updated_at ASC, created_at ASC, id ASC
`

func (q *Queries) ListReposByPrepStatus(ctx context.Context, prepStatus PrepStatus) ([]MigRepo, error) {
	rows, err := q.db.Query(ctx, listReposByPrepStatus, prepStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MigRepo{}
	for rows.Next() {
		var i MigRepo
		if err := rows.Scan(
			&i.ID,
			&i.MigID,
			&i.RepoUrl,
			&i.BaseRef,
			&i.TargetRef,
			&i.PrepStatus,
			&i.PrepAttempts,
			&i.PrepLastError,
			&i.PrepFailureCode,
			&i.PrepUpdatedAt,
			&i.PrepProfile,
			&i.PrepArtifacts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteReGateRecoveryCandidatePrepProfile = `-- name: PromoteReGateRecoveryCandidatePrepProfile :one
WITH target_job AS (
  SELECT j.id, j.repo_id
  FROM jobs j
  WHERE j.id = $1
    AND j.job_type = 're_gate'
    AND j.status = 'Success'
    AND (
      CASE
        WHEN jsonb_typeof(j.meta->'recovery'->'candidate_promoted') = 'boolean'
        THEN (j.meta->'recovery'->>'candidate_promoted')::boolean
        ELSE false
      END
    ) = false
  FOR UPDATE
),
updated_job AS (
  UPDATE jobs j
  SET meta = $2
  FROM target_job tj
  WHERE j.id = tj.id
  RETURNING tj.repo_id
)
UPDATE mig_repos mr
SET prep_profile = $3,
    prep_artifacts = $4,
    prep_status = 'PrepReady',
    prep_last_error = NULL,
    prep_failure_code = NULL,
    prep_updated_at = now()
FROM updated_job uj
WHERE mr.id = uj.repo_id
RETURNING mr.id
`

type PromoteReGateRecoveryCandidatePrepProfileParams struct {
	ID            types.JobID `json:"id"`
	Meta          []byte      `json:"meta"`
	PrepProfile   []byte      `json:"prep_profile"`
	PrepArtifacts []byte      `json:"prep_artifacts"`
}

func (q *Queries) PromoteReGateRecoveryCandidatePrepProfile(ctx context.Context, arg PromoteReGateRecoveryCandidatePrepProfileParams) (types.MigRepoID, error) {
	row := q.db.QueryRow(ctx, promoteReGateRecoveryCandidatePrepProfile,
		arg.ID,
		arg.Meta,
		arg.PrepProfile,
		arg.PrepArtifacts,
	)
	var id types.MigRepoID
	err := row.Scan(&id)
	return id, err
}

const saveMigRepoPrepProfile = `-- name: SaveMigRepoPrepProfile :exec
UPDATE mig_repos
SET prep_profile = $2,
    prep_artifacts = $3,
    prep_status = 'PrepReady',
    prep_last_error = NULL,
    prep_failure_code = NULL,
    prep_updated_at = now()
WHERE id = $1
`

type SaveMigRepoPrepProfileParams struct {
	ID            types.MigRepoID `json:"id"`
	PrepProfile   []byte          `json:"prep_profile"`
	PrepArtifacts []byte          `json:"prep_artifacts"`
}

func (q *Queries) SaveMigRepoPrepProfile(ctx context.Context, arg SaveMigRepoPrepProfileParams) error {
	_, err := q.db.Exec(ctx, saveMigRepoPrepProfile, arg.ID, arg.PrepProfile, arg.PrepArtifacts)
	return err
}

const updateMigRepoPrepState = `-- name: UpdateMigRepoPrepState :exec
UPDATE mig_repos
SET prep_status = $2,
    prep_last_error = $3,
    prep_failure_code = $4,
    prep_updated_at = now()
WHERE id = $1
`

type UpdateMigRepoPrepStateParams struct {
	ID              types.MigRepoID `json:"id"`
	PrepStatus      PrepStatus      `json:"prep_status"`
	PrepLastError   *string         `json:"prep_last_error"`
	PrepFailureCode *string         `json:"prep_failure_code"`
}

func (q *Queries) UpdateMigRepoPrepState(ctx context.Context, arg UpdateMigRepoPrepStateParams) error {
	_, err := q.db.Exec(ctx, updateMigRepoPrepState,
		arg.ID,
		arg.PrepStatus,
		arg.PrepLastError,
		arg.PrepFailureCode,
	)
	return err
}

const updateMigRepoRefs = `-- name: UpdateMigRepoRefs :exec
UPDATE mig_repos
SET base_ref = $2,
    target_ref = $3
WHERE id = $1
`

type UpdateMigRepoRefsParams struct {
	ID        types.MigRepoID `json:"id"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

func (q *Queries) UpdateMigRepoRefs(ctx context.Context, arg UpdateMigRepoRefsParams) error {
	_, err := q.db.Exec(ctx, updateMigRepoRefs, arg.ID, arg.BaseRef, arg.TargetRef)
	return err
}

const upsertMigRepo = `-- name: UpsertMigRepo :one
INSERT INTO mig_repos (
  id,
  mig_id,
  repo_url,
  base_ref,
  target_ref,
  prep_status,
  prep_last_error,
  prep_failure_code,
  prep_profile,
  prep_artifacts,
  prep_updated_at
)
VALUES ($1, $2, $3, $4, $5, 'PrepPending', NULL, NULL, NULL, NULL, now())
ON CONFLICT (mig_id, repo_url)
DO UPDATE SET
  base_ref = EXCLUDED.base_ref,
  target_ref = EXCLUDED.target_ref,
  prep_status = CASE
    WHEN mig_repos.base_ref IS DISTINCT FROM EXCLUDED.base_ref
      OR mig_repos.target_ref IS DISTINCT FROM EXCLUDED.target_ref
    THEN 'PrepPending'::prep_status
    ELSE mig_repos.prep_status
  END,
  prep_last_error = CASE
    WHEN mig_repos.base_ref IS DISTINCT FROM EXCLUDED.base_ref
      OR mig_repos.target_ref IS DISTINCT FROM EXCLUDED.target_ref
    THEN NULL
    ELSE mig_repos.prep_last_error
  END,
  prep_failure_code = CASE
    WHEN mig_repos.base_ref IS DISTINCT FROM EXCLUDED.base_ref
      OR mig_repos.target_ref IS DISTINCT FROM EXCLUDED.target_ref
    THEN NULL
    ELSE mig_repos.prep_failure_code
  END,
  prep_profile = CASE
    WHEN mig_repos.base_ref IS DISTINCT FROM EXCLUDED.base_ref
      OR mig_repos.target_ref IS DISTINCT FROM EXCLUDED.target_ref
    THEN NULL
    ELSE mig_repos.prep_profile
  END,
  prep_artifacts = CASE
    WHEN mig_repos.base_ref IS DISTINCT FROM EXCLUDED.base_ref
      OR mig_repos.target_ref IS DISTINCT FROM EXCLUDED.target_ref
    THEN NULL
    ELSE mig_repos.prep_artifacts
  END,
  prep_updated_at = CASE
    WHEN mig_repos.base_ref IS DISTINCT FROM EXCLUDED.base_ref
      OR mig_repos.target_ref IS DISTINCT FROM EXCLUDED.target_ref
    THEN now()
    ELSE mig_repos.prep_updated_at
  END
RETURNING id, mig_id, repo_url, base_ref, target_ref, prep_status, prep_attempts, prep_last_error, prep_failure_code, prep_updated_at, prep_profile, prep_artifacts, created_at
`

type UpsertMigRepoParams struct {
	ID        types.MigRepoID `json:"id"`
	MigID     types.MigID     `json:"mig_id"`
	RepoUrl   string          `json:"repo_url"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

// Bulk upsert a mod_repo by normalized repo_url.
// Uniqueness is on (mig_id, repo_url) to prevent duplicate repo URLs per mig.
// If a row exists, update refs; otherwise insert.
func (q *Queries) UpsertMigRepo(ctx context.Context, arg UpsertMigRepoParams) (MigRepo, error) {
	row := q.db.QueryRow(ctx, upsertMigRepo,
		arg.ID,
		arg.MigID,
		arg.RepoUrl,
		arg.BaseRef,
		arg.TargetRef,
	)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.PrepStatus,
		&i.PrepAttempts,
		&i.PrepLastError,
		&i.PrepFailureCode,
		&i.PrepUpdatedAt,
		&i.PrepProfile,
		&i.PrepArtifacts,
		&i.CreatedAt,
	)
	return i, err
}
