// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mig_repos.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMigRepo = `-- name: CreateMigRepo :one
INSERT INTO mig_repos (
  id,
  mig_id,
  repo_url,
  base_ref,
  target_ref,
  gate_profile,
  gate_profile_artifacts,
  gate_profile_updated_at
)
VALUES ($1, $2, $3, $4, $5, NULL, NULL, now())
RETURNING id, mig_id, repo_url, base_ref, target_ref, gate_profile_updated_at, gate_profile, gate_profile_artifacts, created_at
`

type CreateMigRepoParams struct {
	ID        types.MigRepoID `json:"id"`
	MigID     types.MigID     `json:"mig_id"`
	RepoUrl   string          `json:"repo_url"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

func (q *Queries) CreateMigRepo(ctx context.Context, arg CreateMigRepoParams) (MigRepo, error) {
	row := q.db.QueryRow(ctx, createMigRepo,
		arg.ID,
		arg.MigID,
		arg.RepoUrl,
		arg.BaseRef,
		arg.TargetRef,
	)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.GateProfileUpdatedAt,
		&i.GateProfile,
		&i.GateProfileArtifacts,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMigRepo = `-- name: DeleteMigRepo :exec
DELETE FROM mig_repos
WHERE id = $1
`

// Deletes a mod_repo by id.
// Note: mig_repos.id is referenced by run_repos.repo_id and jobs.repo_id with ON DELETE RESTRICT.
// This DELETE will fail if any run_repos/jobs rows still reference the repo.
func (q *Queries) DeleteMigRepo(ctx context.Context, id types.MigRepoID) error {
	_, err := q.db.Exec(ctx, deleteMigRepo, id)
	return err
}

const getMigRepo = `-- name: GetMigRepo :one
SELECT id, mig_id, repo_url, base_ref, target_ref, gate_profile_updated_at, gate_profile, gate_profile_artifacts, created_at
FROM mig_repos
WHERE id = $1
`

func (q *Queries) GetMigRepo(ctx context.Context, id types.MigRepoID) (MigRepo, error) {
	row := q.db.QueryRow(ctx, getMigRepo, id)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.GateProfileUpdatedAt,
		&i.GateProfile,
		&i.GateProfileArtifacts,
		&i.CreatedAt,
	)
	return i, err
}

const getMigRepoByURL = `-- name: GetMigRepoByURL :one
SELECT id, mig_id, repo_url, base_ref, target_ref, gate_profile_updated_at, gate_profile, gate_profile_artifacts, created_at
FROM mig_repos
WHERE mig_id = $1 AND repo_url = $2
`

type GetMigRepoByURLParams struct {
	MigID   types.MigID `json:"mig_id"`
	RepoUrl string      `json:"repo_url"`
}

// Gets a mod_repo by mig_id and repo_url (for uniqueness constraint enforcement).
func (q *Queries) GetMigRepoByURL(ctx context.Context, arg GetMigRepoByURLParams) (MigRepo, error) {
	row := q.db.QueryRow(ctx, getMigRepoByURL, arg.MigID, arg.RepoUrl)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.GateProfileUpdatedAt,
		&i.GateProfile,
		&i.GateProfileArtifacts,
		&i.CreatedAt,
	)
	return i, err
}

const hasMigRepoHistory = `-- name: HasMigRepoHistory :one
SELECT EXISTS(
  SELECT 1 FROM run_repos WHERE repo_id = $1 LIMIT 1
) AS has_history
`

// Checks if a mod_repo has any historical executions (run_repos references).
// Returns true if the repo cannot be deleted due to history, false otherwise.
// Deletion is refused if the repo has historical executions.
func (q *Queries) HasMigRepoHistory(ctx context.Context, repoID types.MigRepoID) (bool, error) {
	row := q.db.QueryRow(ctx, hasMigRepoHistory, repoID)
	var has_history bool
	err := row.Scan(&has_history)
	return has_history, err
}

const listDistinctRepos = `-- name: ListDistinctRepos :many
SELECT
  mr.id AS repo_id,
  mr.repo_url,
  rr.last_run_at,
  COALESCE(rr.last_status::text, '') AS last_status
FROM mig_repos mr
LEFT JOIN LATERAL (
  SELECT
    rrr.started_at AS last_run_at,
    rrr.status AS last_status
  FROM run_repos rrr
  WHERE rrr.repo_id = mr.id
  ORDER BY rrr.started_at DESC NULLS LAST, rrr.created_at DESC, rrr.run_id DESC
  LIMIT 1
) rr ON true
WHERE ($1::text IS NULL OR $1 = '' OR mr.repo_url ILIKE '%' || $1 || '%')
ORDER BY mr.repo_url ASC, mr.id ASC
`

type ListDistinctReposRow struct {
	RepoID     types.MigRepoID    `json:"repo_id"`
	RepoUrl    string             `json:"repo_url"`
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	LastStatus interface{}        `json:"last_status"`
}

// v1: Lists distinct repos (mig_repos) with last known run metadata, optionally filtered by repo_url substring.
func (q *Queries) ListDistinctRepos(ctx context.Context, filter string) ([]ListDistinctReposRow, error) {
	rows, err := q.db.Query(ctx, listDistinctRepos, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistinctReposRow{}
	for rows.Next() {
		var i ListDistinctReposRow
		if err := rows.Scan(
			&i.RepoID,
			&i.RepoUrl,
			&i.LastRunAt,
			&i.LastStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigReposByMig = `-- name: ListMigReposByMig :many
SELECT id, mig_id, repo_url, base_ref, target_ref, gate_profile_updated_at, gate_profile, gate_profile_artifacts, created_at
FROM mig_repos
WHERE mig_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMigReposByMig(ctx context.Context, migID types.MigID) ([]MigRepo, error) {
	rows, err := q.db.Query(ctx, listMigReposByMig, migID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MigRepo{}
	for rows.Next() {
		var i MigRepo
		if err := rows.Scan(
			&i.ID,
			&i.MigID,
			&i.RepoUrl,
			&i.BaseRef,
			&i.TargetRef,
			&i.GateProfileUpdatedAt,
			&i.GateProfile,
			&i.GateProfileArtifacts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteReGateRecoveryCandidateGateProfile = `-- name: PromoteReGateRecoveryCandidateGateProfile :one
WITH target_job AS (
  SELECT j.id, j.repo_id
  FROM jobs j
  WHERE j.id = $1
    AND j.job_type = 're_gate'
    AND j.status = 'Success'
    AND (
      CASE
        WHEN jsonb_typeof(j.meta->'recovery'->'candidate_promoted') = 'boolean'
        THEN (j.meta->'recovery'->>'candidate_promoted')::boolean
        ELSE false
      END
    ) = false
  FOR UPDATE
),
updated_job AS (
  UPDATE jobs j
  SET meta = $2
  FROM target_job tj
  WHERE j.id = tj.id
  RETURNING tj.repo_id
)
UPDATE mig_repos mr
SET gate_profile = $3,
    gate_profile_artifacts = $4,
    gate_profile_updated_at = now()
FROM updated_job uj
WHERE mr.id = uj.repo_id
RETURNING mr.id
`

type PromoteReGateRecoveryCandidateGateProfileParams struct {
	ID                   types.JobID `json:"id"`
	Meta                 []byte      `json:"meta"`
	GateProfile          []byte      `json:"gate_profile"`
	GateProfileArtifacts []byte      `json:"gate_profile_artifacts"`
}

func (q *Queries) PromoteReGateRecoveryCandidateGateProfile(ctx context.Context, arg PromoteReGateRecoveryCandidateGateProfileParams) (types.MigRepoID, error) {
	row := q.db.QueryRow(ctx, promoteReGateRecoveryCandidateGateProfile,
		arg.ID,
		arg.Meta,
		arg.GateProfile,
		arg.GateProfileArtifacts,
	)
	var id types.MigRepoID
	err := row.Scan(&id)
	return id, err
}

const promotePreGateGeneratedGateProfile = `-- name: PromotePreGateGeneratedGateProfile :one
WITH target_job AS (
  SELECT j.id, j.repo_id
  FROM jobs j
  WHERE j.id = $1
    AND j.job_type = 'pre_gate'
    AND j.status = 'Success'
)
UPDATE mig_repos mr
SET gate_profile = $2,
    gate_profile_artifacts = $3,
    gate_profile_updated_at = now()
FROM target_job tj
WHERE mr.id = tj.repo_id
  AND mr.gate_profile IS NULL
RETURNING mr.id
`

type PromotePreGateGeneratedGateProfileParams struct {
	ID                   types.JobID `json:"id"`
	GateProfile          []byte      `json:"gate_profile"`
	GateProfileArtifacts []byte      `json:"gate_profile_artifacts"`
}

func (q *Queries) PromotePreGateGeneratedGateProfile(ctx context.Context, arg PromotePreGateGeneratedGateProfileParams) (types.MigRepoID, error) {
	row := q.db.QueryRow(ctx, promotePreGateGeneratedGateProfile, arg.ID, arg.GateProfile, arg.GateProfileArtifacts)
	var id types.MigRepoID
	err := row.Scan(&id)
	return id, err
}

const updateMigRepoRefs = `-- name: UpdateMigRepoRefs :exec
UPDATE mig_repos
SET base_ref = $2,
    target_ref = $3
WHERE id = $1
`

type UpdateMigRepoRefsParams struct {
	ID        types.MigRepoID `json:"id"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

func (q *Queries) UpdateMigRepoRefs(ctx context.Context, arg UpdateMigRepoRefsParams) error {
	_, err := q.db.Exec(ctx, updateMigRepoRefs, arg.ID, arg.BaseRef, arg.TargetRef)
	return err
}

const upsertMigRepo = `-- name: UpsertMigRepo :one
INSERT INTO mig_repos (
  id,
  mig_id,
  repo_url,
  base_ref,
  target_ref,
  gate_profile,
  gate_profile_artifacts,
  gate_profile_updated_at
)
VALUES ($1, $2, $3, $4, $5, NULL, NULL, now())
ON CONFLICT (mig_id, repo_url)
DO UPDATE SET
  base_ref = EXCLUDED.base_ref,
  target_ref = EXCLUDED.target_ref
RETURNING id, mig_id, repo_url, base_ref, target_ref, gate_profile_updated_at, gate_profile, gate_profile_artifacts, created_at
`

type UpsertMigRepoParams struct {
	ID        types.MigRepoID `json:"id"`
	MigID     types.MigID     `json:"mig_id"`
	RepoUrl   string          `json:"repo_url"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

// Bulk upsert a mod_repo by normalized repo_url.
// Uniqueness is on (mig_id, repo_url) to prevent duplicate repo URLs per mig.
// If a row exists, update refs; otherwise insert.
func (q *Queries) UpsertMigRepo(ctx context.Context, arg UpsertMigRepoParams) (MigRepo, error) {
	row := q.db.QueryRow(ctx, upsertMigRepo,
		arg.ID,
		arg.MigID,
		arg.RepoUrl,
		arg.BaseRef,
		arg.TargetRef,
	)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.GateProfileUpdatedAt,
		&i.GateProfile,
		&i.GateProfileArtifacts,
		&i.CreatedAt,
	)
	return i, err
}
