// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mig_repos.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMigRepo = `-- name: CreateMigRepo :one
WITH existing_repo AS (
  SELECT id
  FROM repos
  WHERE repos.url = $3
),
inserted_repo AS (
  INSERT INTO repos (id, url)
  SELECT $1, $3
  WHERE NOT EXISTS (SELECT 1 FROM existing_repo)
  ON CONFLICT (url) DO NOTHING
  RETURNING id
),
resolved_repo AS (
  SELECT id FROM inserted_repo
  UNION ALL
  SELECT id FROM existing_repo
  UNION ALL
  SELECT id FROM repos WHERE repos.url = $3
  LIMIT 1
)
INSERT INTO mig_repos (
  id,
  mig_id,
  repo_id,
  base_ref,
  target_ref
)
VALUES ($1, $2, (SELECT id FROM resolved_repo), $4, $5)
RETURNING id, mig_id, repo_id, base_ref, target_ref, created_at
`

type CreateMigRepoParams struct {
	ID        types.MigRepoID `json:"id"`
	MigID     types.MigID     `json:"mig_id"`
	Url       string          `json:"url"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

func (q *Queries) CreateMigRepo(ctx context.Context, arg CreateMigRepoParams) (MigRepo, error) {
	row := q.db.QueryRow(ctx, createMigRepo,
		arg.ID,
		arg.MigID,
		arg.Url,
		arg.BaseRef,
		arg.TargetRef,
	)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoID,
		&i.BaseRef,
		&i.TargetRef,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMigRepo = `-- name: DeleteMigRepo :exec
DELETE FROM mig_repos
WHERE id = $1
`

// Deletes a mig_repo by id.
// Note: mig_repos.id remains referenced by API-level repo membership records.
func (q *Queries) DeleteMigRepo(ctx context.Context, id types.MigRepoID) error {
	_, err := q.db.Exec(ctx, deleteMigRepo, id)
	return err
}

const getMigRepo = `-- name: GetMigRepo :one
SELECT id, mig_id, repo_id, base_ref, target_ref, created_at
FROM mig_repos
WHERE id = $1
`

func (q *Queries) GetMigRepo(ctx context.Context, id types.MigRepoID) (MigRepo, error) {
	row := q.db.QueryRow(ctx, getMigRepo, id)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoID,
		&i.BaseRef,
		&i.TargetRef,
		&i.CreatedAt,
	)
	return i, err
}

const getMigRepoByURL = `-- name: GetMigRepoByURL :one
SELECT mr.id, mr.mig_id, mr.repo_id, mr.base_ref, mr.target_ref, mr.created_at
FROM mig_repos mr
JOIN repos r ON r.id = mr.repo_id
WHERE mr.mig_id = $1 AND r.url = $2
`

type GetMigRepoByURLParams struct {
	MigID types.MigID `json:"mig_id"`
	Url   string      `json:"url"`
}

// Gets a mig_repo by mig_id and repo_url (for uniqueness constraint enforcement).
func (q *Queries) GetMigRepoByURL(ctx context.Context, arg GetMigRepoByURLParams) (MigRepo, error) {
	row := q.db.QueryRow(ctx, getMigRepoByURL, arg.MigID, arg.Url)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoID,
		&i.BaseRef,
		&i.TargetRef,
		&i.CreatedAt,
	)
	return i, err
}

const hasMigRepoHistory = `-- name: HasMigRepoHistory :one
SELECT EXISTS(
  SELECT 1 FROM run_repos WHERE repo_id = $1 LIMIT 1
) AS has_history
`

// Checks if a mig_repo has any historical executions (run_repos references).
// Returns true if the repo cannot be deleted due to history, false otherwise.
func (q *Queries) HasMigRepoHistory(ctx context.Context, repoID types.MigRepoID) (bool, error) {
	row := q.db.QueryRow(ctx, hasMigRepoHistory, repoID)
	var has_history bool
	err := row.Scan(&has_history)
	return has_history, err
}

const listDistinctRepos = `-- name: ListDistinctRepos :many
SELECT
  mr.repo_id,
  r.url AS repo_url,
  rr.last_run_at,
  COALESCE(rr.last_status::text, '') AS last_status
FROM mig_repos mr
JOIN repos r ON r.id = mr.repo_id
LEFT JOIN LATERAL (
  SELECT
    rrr.started_at AS last_run_at,
    rrr.status AS last_status
  FROM run_repos rrr
  WHERE rrr.repo_id = mr.repo_id
    AND rrr.mig_id = mr.mig_id
  ORDER BY rrr.started_at DESC NULLS LAST, rrr.created_at DESC, rrr.run_id DESC
  LIMIT 1
) rr ON true
WHERE ($1::text IS NULL OR $1 = '' OR r.url ILIKE '%' || $1 || '%')
ORDER BY r.url ASC, mr.repo_id ASC
`

type ListDistinctReposRow struct {
	RepoID     types.MigRepoID    `json:"repo_id"`
	RepoUrl    string             `json:"repo_url"`
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	LastStatus interface{}        `json:"last_status"`
}

// Lists distinct repos for a mig with last known run metadata,
// optionally filtered by repo_url substring.
func (q *Queries) ListDistinctRepos(ctx context.Context, filter string) ([]ListDistinctReposRow, error) {
	rows, err := q.db.Query(ctx, listDistinctRepos, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistinctReposRow{}
	for rows.Next() {
		var i ListDistinctReposRow
		if err := rows.Scan(
			&i.RepoID,
			&i.RepoUrl,
			&i.LastRunAt,
			&i.LastStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigReposByMig = `-- name: ListMigReposByMig :many
SELECT id, mig_id, repo_id, base_ref, target_ref, created_at
FROM mig_repos
WHERE mig_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListMigReposByMig(ctx context.Context, migID types.MigID) ([]MigRepo, error) {
	rows, err := q.db.Query(ctx, listMigReposByMig, migID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MigRepo{}
	for rows.Next() {
		var i MigRepo
		if err := rows.Scan(
			&i.ID,
			&i.MigID,
			&i.RepoID,
			&i.BaseRef,
			&i.TargetRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promotePreGateGeneratedGateProfile = `-- name: PromotePreGateGeneratedGateProfile :one
WITH compat_args AS (
  SELECT
    $2::jsonb AS gate_profile,
    $3::jsonb AS gate_profile_artifacts
)
SELECT j.repo_id
FROM jobs j, compat_args
WHERE j.id = $1
  AND j.job_type = 'pre_gate'
  AND j.status = 'Success'
LIMIT 1
`

type PromotePreGateGeneratedGateProfileParams struct {
	ID                   types.JobID `json:"id"`
	GateProfile          []byte      `json:"gate_profile"`
	GateProfileArtifacts []byte      `json:"gate_profile_artifacts"`
}

// Legacy compatibility shim: gate profile persistence on mig_repos is removed.
// Returns target repo_id for callers that still rely on this method's result.
func (q *Queries) PromotePreGateGeneratedGateProfile(ctx context.Context, arg PromotePreGateGeneratedGateProfileParams) (types.MigRepoID, error) {
	row := q.db.QueryRow(ctx, promotePreGateGeneratedGateProfile, arg.ID, arg.GateProfile, arg.GateProfileArtifacts)
	var repo_id types.MigRepoID
	err := row.Scan(&repo_id)
	return repo_id, err
}

const promoteReGateRecoveryCandidateGateProfile = `-- name: PromoteReGateRecoveryCandidateGateProfile :one
WITH compat_args AS (
  SELECT
    $2::jsonb AS job_meta,
    $3::jsonb AS gate_profile,
    $4::jsonb AS gate_profile_artifacts
)
SELECT j.repo_id
FROM jobs j, compat_args
WHERE j.id = $1
  AND j.job_type = 're_gate'
  AND j.status = 'Success'
  AND (
    CASE
      WHEN jsonb_typeof(j.meta->'recovery'->'candidate_promoted') = 'boolean'
      THEN (j.meta->'recovery'->>'candidate_promoted')::boolean
      ELSE false
    END
  ) = false
LIMIT 1
`

type PromoteReGateRecoveryCandidateGateProfileParams struct {
	ID                   types.JobID `json:"id"`
	JobMeta              []byte      `json:"job_meta"`
	GateProfile          []byte      `json:"gate_profile"`
	GateProfileArtifacts []byte      `json:"gate_profile_artifacts"`
}

// Legacy compatibility shim: gate profile persistence on mig_repos is removed.
// Returns target repo_id for callers that still rely on this method's result.
func (q *Queries) PromoteReGateRecoveryCandidateGateProfile(ctx context.Context, arg PromoteReGateRecoveryCandidateGateProfileParams) (types.MigRepoID, error) {
	row := q.db.QueryRow(ctx, promoteReGateRecoveryCandidateGateProfile,
		arg.ID,
		arg.JobMeta,
		arg.GateProfile,
		arg.GateProfileArtifacts,
	)
	var repo_id types.MigRepoID
	err := row.Scan(&repo_id)
	return repo_id, err
}

const updateMigRepoRefs = `-- name: UpdateMigRepoRefs :exec
UPDATE mig_repos
SET base_ref = $2,
    target_ref = $3
WHERE id = $1
`

type UpdateMigRepoRefsParams struct {
	ID        types.MigRepoID `json:"id"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

func (q *Queries) UpdateMigRepoRefs(ctx context.Context, arg UpdateMigRepoRefsParams) error {
	_, err := q.db.Exec(ctx, updateMigRepoRefs, arg.ID, arg.BaseRef, arg.TargetRef)
	return err
}

const upsertMigRepo = `-- name: UpsertMigRepo :one
WITH existing_repo AS (
  SELECT id
  FROM repos
  WHERE repos.url = $3
),
inserted_repo AS (
  INSERT INTO repos (id, url)
  SELECT $1, $3
  WHERE NOT EXISTS (SELECT 1 FROM existing_repo)
  ON CONFLICT (url) DO NOTHING
  RETURNING id
),
resolved_repo AS (
  SELECT id FROM inserted_repo
  UNION ALL
  SELECT id FROM existing_repo
  UNION ALL
  SELECT id FROM repos WHERE repos.url = $3
  LIMIT 1
)
INSERT INTO mig_repos (
  id,
  mig_id,
  repo_id,
  base_ref,
  target_ref
)
VALUES ($1, $2, (SELECT id FROM resolved_repo), $4, $5)
ON CONFLICT (mig_id, repo_id)
DO UPDATE SET
  base_ref = EXCLUDED.base_ref,
  target_ref = EXCLUDED.target_ref
RETURNING id, mig_id, repo_id, base_ref, target_ref, created_at
`

type UpsertMigRepoParams struct {
	ID        types.MigRepoID `json:"id"`
	MigID     types.MigID     `json:"mig_id"`
	Url       string          `json:"url"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

// Bulk upsert a mig_repo by normalized repo_url.
// Uniqueness is on (mig_id, repo_id) to prevent duplicate repo membership per mig.
func (q *Queries) UpsertMigRepo(ctx context.Context, arg UpsertMigRepoParams) (MigRepo, error) {
	row := q.db.QueryRow(ctx, upsertMigRepo,
		arg.ID,
		arg.MigID,
		arg.Url,
		arg.BaseRef,
		arg.TargetRef,
	)
	var i MigRepo
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.RepoID,
		&i.BaseRef,
		&i.TargetRef,
		&i.CreatedAt,
	)
	return i, err
}
