// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mod_repos.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModRepo = `-- name: CreateModRepo :one
INSERT INTO mod_repos (id, mod_id, repo_url, base_ref, target_ref)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, mod_id, repo_url, base_ref, target_ref, created_at
`

type CreateModRepoParams struct {
	ID        string `json:"id"`
	ModID     string `json:"mod_id"`
	RepoUrl   string `json:"repo_url"`
	BaseRef   string `json:"base_ref"`
	TargetRef string `json:"target_ref"`
}

func (q *Queries) CreateModRepo(ctx context.Context, arg CreateModRepoParams) (ModRepo, error) {
	row := q.db.QueryRow(ctx, createModRepo,
		arg.ID,
		arg.ModID,
		arg.RepoUrl,
		arg.BaseRef,
		arg.TargetRef,
	)
	var i ModRepo
	err := row.Scan(
		&i.ID,
		&i.ModID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.CreatedAt,
	)
	return i, err
}

const getModRepo = `-- name: GetModRepo :one
SELECT id, mod_id, repo_url, base_ref, target_ref, created_at
FROM mod_repos
WHERE id = $1
`

func (q *Queries) GetModRepo(ctx context.Context, id string) (ModRepo, error) {
	row := q.db.QueryRow(ctx, getModRepo, id)
	var i ModRepo
	err := row.Scan(
		&i.ID,
		&i.ModID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.CreatedAt,
	)
	return i, err
}

const listDistinctRepos = `-- name: ListDistinctRepos :many
SELECT
  mr.id AS repo_id,
  mr.repo_url,
  rr.last_run_at,
  COALESCE(rr.last_status::text, '') AS last_status
FROM mod_repos mr
LEFT JOIN LATERAL (
  SELECT
    rrr.started_at AS last_run_at,
    rrr.status AS last_status
  FROM run_repos rrr
  WHERE rrr.repo_id = mr.id
  ORDER BY rrr.started_at DESC NULLS LAST, rrr.created_at DESC
  LIMIT 1
) rr ON true
WHERE ($1::text IS NULL OR $1 = '' OR mr.repo_url ILIKE '%' || $1 || '%')
ORDER BY mr.repo_url ASC
`

type ListDistinctReposRow struct {
	RepoID     string             `json:"repo_id"`
	RepoUrl    string             `json:"repo_url"`
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	LastStatus interface{}        `json:"last_status"`
}

// v1: Lists distinct repos (mod_repos) with last known run metadata, optionally filtered by repo_url substring.
func (q *Queries) ListDistinctRepos(ctx context.Context, filter string) ([]ListDistinctReposRow, error) {
	rows, err := q.db.Query(ctx, listDistinctRepos, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistinctReposRow{}
	for rows.Next() {
		var i ListDistinctReposRow
		if err := rows.Scan(
			&i.RepoID,
			&i.RepoUrl,
			&i.LastRunAt,
			&i.LastStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModReposByMod = `-- name: ListModReposByMod :many
SELECT id, mod_id, repo_url, base_ref, target_ref, created_at
FROM mod_repos
WHERE mod_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListModReposByMod(ctx context.Context, modID string) ([]ModRepo, error) {
	rows, err := q.db.Query(ctx, listModReposByMod, modID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModRepo{}
	for rows.Next() {
		var i ModRepo
		if err := rows.Scan(
			&i.ID,
			&i.ModID,
			&i.RepoUrl,
			&i.BaseRef,
			&i.TargetRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModRepoRefs = `-- name: UpdateModRepoRefs :exec
UPDATE mod_repos
SET base_ref = $2,
    target_ref = $3
WHERE id = $1
`

type UpdateModRepoRefsParams struct {
	ID        string `json:"id"`
	BaseRef   string `json:"base_ref"`
	TargetRef string `json:"target_ref"`
}

func (q *Queries) UpdateModRepoRefs(ctx context.Context, arg UpdateModRepoRefsParams) error {
	_, err := q.db.Exec(ctx, updateModRepoRefs, arg.ID, arg.BaseRef, arg.TargetRef)
	return err
}
