// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mod_repos.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const createModRepo = `-- name: CreateModRepo :one
INSERT INTO mod_repos (id, mod_id, repo_url, base_ref, target_ref)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, mod_id, repo_url, base_ref, target_ref, created_at
`

type CreateModRepoParams struct {
	ID        types.ModRepoID `json:"id"`
	ModID     types.ModID     `json:"mod_id"`
	RepoUrl   string          `json:"repo_url"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

func (q *Queries) CreateModRepo(ctx context.Context, arg CreateModRepoParams) (ModRepo, error) {
	row := q.db.QueryRow(ctx, createModRepo,
		arg.ID,
		arg.ModID,
		arg.RepoUrl,
		arg.BaseRef,
		arg.TargetRef,
	)
	var i ModRepo
	err := row.Scan(
		&i.ID,
		&i.ModID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.CreatedAt,
	)
	return i, err
}

const deleteModRepo = `-- name: DeleteModRepo :exec
DELETE FROM mod_repos
WHERE id = $1
`

// Deletes a mod_repo by id.
// Note: mod_repos.id is referenced by run_repos.repo_id and jobs.repo_id with ON DELETE RESTRICT.
// This DELETE will fail if any run_repos/jobs rows still reference the repo.
func (q *Queries) DeleteModRepo(ctx context.Context, id types.ModRepoID) error {
	_, err := q.db.Exec(ctx, deleteModRepo, id)
	return err
}

const getModRepo = `-- name: GetModRepo :one
SELECT id, mod_id, repo_url, base_ref, target_ref, created_at
FROM mod_repos
WHERE id = $1
`

func (q *Queries) GetModRepo(ctx context.Context, id types.ModRepoID) (ModRepo, error) {
	row := q.db.QueryRow(ctx, getModRepo, id)
	var i ModRepo
	err := row.Scan(
		&i.ID,
		&i.ModID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.CreatedAt,
	)
	return i, err
}

const getModRepoByURL = `-- name: GetModRepoByURL :one
SELECT id, mod_id, repo_url, base_ref, target_ref, created_at
FROM mod_repos
WHERE mod_id = $1 AND repo_url = $2
`

type GetModRepoByURLParams struct {
	ModID   types.ModID `json:"mod_id"`
	RepoUrl string      `json:"repo_url"`
}

// Gets a mod_repo by mod_id and repo_url (for uniqueness constraint enforcement).
func (q *Queries) GetModRepoByURL(ctx context.Context, arg GetModRepoByURLParams) (ModRepo, error) {
	row := q.db.QueryRow(ctx, getModRepoByURL, arg.ModID, arg.RepoUrl)
	var i ModRepo
	err := row.Scan(
		&i.ID,
		&i.ModID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.CreatedAt,
	)
	return i, err
}

const hasModRepoHistory = `-- name: HasModRepoHistory :one
SELECT EXISTS(
  SELECT 1 FROM run_repos WHERE repo_id = $1 LIMIT 1
) AS has_history
`

// Checks if a mod_repo has any historical executions (run_repos references).
// Returns true if the repo cannot be deleted due to history, false otherwise.
// Deletion is refused if the repo has historical executions.
func (q *Queries) HasModRepoHistory(ctx context.Context, repoID types.ModRepoID) (bool, error) {
	row := q.db.QueryRow(ctx, hasModRepoHistory, repoID)
	var has_history bool
	err := row.Scan(&has_history)
	return has_history, err
}

const listDistinctRepos = `-- name: ListDistinctRepos :many
SELECT
  mr.id AS repo_id,
  mr.repo_url,
  rr.last_run_at,
  COALESCE(rr.last_status::text, '') AS last_status
FROM mod_repos mr
LEFT JOIN LATERAL (
  SELECT
    rrr.started_at AS last_run_at,
    rrr.status AS last_status
  FROM run_repos rrr
  WHERE rrr.repo_id = mr.id
  ORDER BY rrr.started_at DESC NULLS LAST, rrr.created_at DESC
  LIMIT 1
) rr ON true
WHERE ($1::text IS NULL OR $1 = '' OR mr.repo_url ILIKE '%' || $1 || '%')
ORDER BY mr.repo_url ASC, mr.id ASC
`

type ListDistinctReposRow struct {
	RepoID     types.ModRepoID    `json:"repo_id"`
	RepoUrl    string             `json:"repo_url"`
	LastRunAt  pgtype.Timestamptz `json:"last_run_at"`
	LastStatus interface{}        `json:"last_status"`
}

// v1: Lists distinct repos (mod_repos) with last known run metadata, optionally filtered by repo_url substring.
func (q *Queries) ListDistinctRepos(ctx context.Context, filter string) ([]ListDistinctReposRow, error) {
	rows, err := q.db.Query(ctx, listDistinctRepos, filter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistinctReposRow{}
	for rows.Next() {
		var i ListDistinctReposRow
		if err := rows.Scan(
			&i.RepoID,
			&i.RepoUrl,
			&i.LastRunAt,
			&i.LastStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModReposByMod = `-- name: ListModReposByMod :many
SELECT id, mod_id, repo_url, base_ref, target_ref, created_at
FROM mod_repos
WHERE mod_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListModReposByMod(ctx context.Context, modID types.ModID) ([]ModRepo, error) {
	rows, err := q.db.Query(ctx, listModReposByMod, modID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModRepo{}
	for rows.Next() {
		var i ModRepo
		if err := rows.Scan(
			&i.ID,
			&i.ModID,
			&i.RepoUrl,
			&i.BaseRef,
			&i.TargetRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateModRepoRefs = `-- name: UpdateModRepoRefs :exec
UPDATE mod_repos
SET base_ref = $2,
    target_ref = $3
WHERE id = $1
`

type UpdateModRepoRefsParams struct {
	ID        types.ModRepoID `json:"id"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

func (q *Queries) UpdateModRepoRefs(ctx context.Context, arg UpdateModRepoRefsParams) error {
	_, err := q.db.Exec(ctx, updateModRepoRefs, arg.ID, arg.BaseRef, arg.TargetRef)
	return err
}

const upsertModRepo = `-- name: UpsertModRepo :one
INSERT INTO mod_repos (id, mod_id, repo_url, base_ref, target_ref)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (mod_id, repo_url)
DO UPDATE SET
  base_ref = EXCLUDED.base_ref,
  target_ref = EXCLUDED.target_ref
RETURNING id, mod_id, repo_url, base_ref, target_ref, created_at
`

type UpsertModRepoParams struct {
	ID        types.ModRepoID `json:"id"`
	ModID     types.ModID     `json:"mod_id"`
	RepoUrl   string          `json:"repo_url"`
	BaseRef   string          `json:"base_ref"`
	TargetRef string          `json:"target_ref"`
}

// Bulk upsert a mod_repo by normalized repo_url.
// Uniqueness is on (mod_id, repo_url) to prevent duplicate repo URLs per mod.
// If a row exists, update refs; otherwise insert.
func (q *Queries) UpsertModRepo(ctx context.Context, arg UpsertModRepoParams) (ModRepo, error) {
	row := q.db.QueryRow(ctx, upsertModRepo,
		arg.ID,
		arg.ModID,
		arg.RepoUrl,
		arg.BaseRef,
		arg.TargetRef,
	)
	var i ModRepo
	err := row.Scan(
		&i.ID,
		&i.ModID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.CreatedAt,
	)
	return i, err
}
