// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobStatus string

const (
	JobStatusCreated   JobStatus = "created"
	JobStatusPending   JobStatus = "pending"
	JobStatusRunning   JobStatus = "running"
	JobStatusSucceeded JobStatus = "succeeded"
	JobStatusFailed    JobStatus = "failed"
	JobStatusSkipped   JobStatus = "skipped"
	JobStatusCanceled  JobStatus = "canceled"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type RunRepoStatus string

const (
	RunRepoStatusPending   RunRepoStatus = "pending"
	RunRepoStatusRunning   RunRepoStatus = "running"
	RunRepoStatusSucceeded RunRepoStatus = "succeeded"
	RunRepoStatusFailed    RunRepoStatus = "failed"
	RunRepoStatusSkipped   RunRepoStatus = "skipped"
	RunRepoStatusCancelled RunRepoStatus = "cancelled"
)

func (e *RunRepoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunRepoStatus(s)
	case string:
		*e = RunRepoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunRepoStatus: %T", src)
	}
	return nil
}

type NullRunRepoStatus struct {
	RunRepoStatus RunRepoStatus `json:"run_repo_status"`
	Valid         bool          `json:"valid"` // Valid is true if RunRepoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunRepoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunRepoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunRepoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunRepoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunRepoStatus), nil
}

type RunStatus string

const (
	RunStatusQueued    RunStatus = "queued"
	RunStatusAssigned  RunStatus = "assigned"
	RunStatusRunning   RunStatus = "running"
	RunStatusSucceeded RunStatus = "succeeded"
	RunStatusFailed    RunStatus = "failed"
	RunStatusCanceled  RunStatus = "canceled"
)

func (e *RunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunStatus(s)
	case string:
		*e = RunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunStatus: %T", src)
	}
	return nil
}

type NullRunStatus struct {
	RunStatus RunStatus `json:"run_status"`
	Valid     bool      `json:"valid"` // Valid is true if RunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunStatus), nil
}

type ApiToken struct {
	ID          pgtype.UUID        `json:"id"`
	TokenHash   string             `json:"token_hash"`
	TokenID     string             `json:"token_id"`
	ClusterID   *string            `json:"cluster_id"`
	Role        string             `json:"role"`
	Description *string            `json:"description"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ArtifactBundle struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     string             `json:"run_id"`
	JobID     *string            `json:"job_id"`
	Name      *string            `json:"name"`
	Bundle    []byte             `json:"bundle"`
	Cid       *string            `json:"cid"`
	Digest    *string            `json:"digest"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BootstrapToken struct {
	ID           pgtype.UUID        `json:"id"`
	TokenHash    string             `json:"token_hash"`
	TokenID      string             `json:"token_id"`
	NodeID       *string            `json:"node_id"`
	ClusterID    *string            `json:"cluster_id"`
	IssuedAt     pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	CertIssuedAt pgtype.Timestamptz `json:"cert_issued_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	IssuedBy     *string            `json:"issued_by"`
}

type Diff struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     string             `json:"run_id"`
	JobID     *string            `json:"job_id"`
	Patch     []byte             `json:"patch"`
	Summary   []byte             `json:"summary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID      int64              `json:"id"`
	RunID   string             `json:"run_id"`
	JobID   *string            `json:"job_id"`
	Time    pgtype.Timestamptz `json:"time"`
	Level   string             `json:"level"`
	Message string             `json:"message"`
	Meta    []byte             `json:"meta"`
}

type Job struct {
	ID         string             `json:"id"`
	RunID      string             `json:"run_id"`
	Name       string             `json:"name"`
	Status     JobStatus          `json:"status"`
	ModType    string             `json:"mod_type"`
	ModImage   string             `json:"mod_image"`
	StepIndex  float64            `json:"step_index"`
	NodeID     *string            `json:"node_id"`
	ExitCode   *int32             `json:"exit_code"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	DurationMs int64              `json:"duration_ms"`
	Meta       []byte             `json:"meta"`
}

type Log struct {
	ID        int64              `json:"id"`
	RunID     string             `json:"run_id"`
	JobID     *string            `json:"job_id"`
	ChunkNo   int32              `json:"chunk_no"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Node struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	IpAddress       netip.Addr         `json:"ip_address"`
	Version         *string            `json:"version"`
	Concurrency     int32              `json:"concurrency"`
	CpuTotalMillis  int32              `json:"cpu_total_millis"`
	CpuFreeMillis   int32              `json:"cpu_free_millis"`
	MemTotalBytes   int64              `json:"mem_total_bytes"`
	MemFreeBytes    int64              `json:"mem_free_bytes"`
	DiskTotalBytes  int64              `json:"disk_total_bytes"`
	DiskFreeBytes   int64              `json:"disk_free_bytes"`
	Drained         bool               `json:"drained"`
	CertSerial      *string            `json:"cert_serial"`
	CertFingerprint *string            `json:"cert_fingerprint"`
	CertNotBefore   pgtype.Timestamptz `json:"cert_not_before"`
	CertNotAfter    pgtype.Timestamptz `json:"cert_not_after"`
	LastHeartbeat   pgtype.Timestamptz `json:"last_heartbeat"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type NodeMetric struct {
	ID             int64              `json:"id"`
	NodeID         string             `json:"node_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CpuTotalMillis int32              `json:"cpu_total_millis"`
	CpuFreeMillis  int32              `json:"cpu_free_millis"`
	MemTotalBytes  int64              `json:"mem_total_bytes"`
	MemFreeBytes   int64              `json:"mem_free_bytes"`
	DiskTotalBytes int64              `json:"disk_total_bytes"`
	DiskFreeBytes  int64              `json:"disk_free_bytes"`
}

type Run struct {
	ID         string             `json:"id"`
	Name       *string            `json:"name"`
	RepoUrl    string             `json:"repo_url"`
	Spec       []byte             `json:"spec"`
	CreatedBy  *string            `json:"created_by"`
	Status     RunStatus          `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	NodeID     *string            `json:"node_id"`
	BaseRef    string             `json:"base_ref"`
	TargetRef  string             `json:"target_ref"`
	CommitSha  *string            `json:"commit_sha"`
	Stats      []byte             `json:"stats"`
}

type RunRepo struct {
	ID             string             `json:"id"`
	RunID          string             `json:"run_id"`
	RepoUrl        string             `json:"repo_url"`
	BaseRef        string             `json:"base_ref"`
	TargetRef      string             `json:"target_ref"`
	Status         RunRepoStatus      `json:"status"`
	Attempt        int32              `json:"attempt"`
	LastError      *string            `json:"last_error"`
	ExecutionRunID *string            `json:"execution_run_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type RunsTiming struct {
	ID      string `json:"id"`
	QueueMs int64  `json:"queue_ms"`
	RunMs   int64  `json:"run_ms"`
}
