// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type BuildgateJobStatus string

const (
	BuildgateJobStatusPending   BuildgateJobStatus = "pending"
	BuildgateJobStatusClaimed   BuildgateJobStatus = "claimed"
	BuildgateJobStatusRunning   BuildgateJobStatus = "running"
	BuildgateJobStatusCompleted BuildgateJobStatus = "completed"
	BuildgateJobStatusFailed    BuildgateJobStatus = "failed"
)

func (e *BuildgateJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildgateJobStatus(s)
	case string:
		*e = BuildgateJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildgateJobStatus: %T", src)
	}
	return nil
}

type NullBuildgateJobStatus struct {
	BuildgateJobStatus BuildgateJobStatus `json:"buildgate_job_status"`
	Valid              bool               `json:"valid"` // Valid is true if BuildgateJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildgateJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BuildgateJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildgateJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildgateJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildgateJobStatus), nil
}

type RunStatus string

const (
	RunStatusQueued    RunStatus = "queued"
	RunStatusAssigned  RunStatus = "assigned"
	RunStatusRunning   RunStatus = "running"
	RunStatusSucceeded RunStatus = "succeeded"
	RunStatusFailed    RunStatus = "failed"
	RunStatusCanceled  RunStatus = "canceled"
)

func (e *RunStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RunStatus(s)
	case string:
		*e = RunStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RunStatus: %T", src)
	}
	return nil
}

type NullRunStatus struct {
	RunStatus RunStatus `json:"run_status"`
	Valid     bool      `json:"valid"` // Valid is true if RunStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRunStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RunStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RunStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRunStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RunStatus), nil
}

type StageStatus string

const (
	StageStatusPending   StageStatus = "pending"
	StageStatusRunning   StageStatus = "running"
	StageStatusSucceeded StageStatus = "succeeded"
	StageStatusFailed    StageStatus = "failed"
	StageStatusSkipped   StageStatus = "skipped"
	StageStatusCanceled  StageStatus = "canceled"
)

func (e *StageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StageStatus(s)
	case string:
		*e = StageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StageStatus: %T", src)
	}
	return nil
}

type NullStageStatus struct {
	StageStatus StageStatus `json:"stage_status"`
	Valid       bool        `json:"valid"` // Valid is true if StageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StageStatus), nil
}

type ApiToken struct {
	ID          pgtype.UUID        `json:"id"`
	TokenHash   string             `json:"token_hash"`
	TokenID     string             `json:"token_id"`
	ClusterID   string             `json:"cluster_id"`
	Role        string             `json:"role"`
	Description *string            `json:"description"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedBy   *string            `json:"created_by"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ArtifactBundle struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	StageID   pgtype.UUID        `json:"stage_id"`
	BuildID   pgtype.UUID        `json:"build_id"`
	Name      *string            `json:"name"`
	Bundle    []byte             `json:"bundle"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Cid       *string            `json:"cid"`
	Digest    *string            `json:"digest"`
}

type BootstrapToken struct {
	ID           pgtype.UUID        `json:"id"`
	TokenHash    string             `json:"token_hash"`
	TokenID      string             `json:"token_id"`
	NodeID       pgtype.UUID        `json:"node_id"`
	ClusterID    string             `json:"cluster_id"`
	IssuedAt     pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	CertIssuedAt pgtype.Timestamptz `json:"cert_issued_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	IssuedBy     *string            `json:"issued_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Build struct {
	ID         pgtype.UUID        `json:"id"`
	RunID      pgtype.UUID        `json:"run_id"`
	StageID    pgtype.UUID        `json:"stage_id"`
	Tool       *string            `json:"tool"`
	Command    *string            `json:"command"`
	Status     StageStatus        `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	DurationMs int64              `json:"duration_ms"`
	Metrics    []byte             `json:"metrics"`
}

type BuildgateJob struct {
	ID             pgtype.UUID        `json:"id"`
	Status         BuildgateJobStatus `json:"status"`
	RequestPayload []byte             `json:"request_payload"`
	Result         []byte             `json:"result"`
	Error          *string            `json:"error"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	NodeID         pgtype.UUID        `json:"node_id"`
}

type Diff struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	StageID   pgtype.UUID        `json:"stage_id"`
	Patch     []byte             `json:"patch"`
	Summary   []byte             `json:"summary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID      int64              `json:"id"`
	RunID   pgtype.UUID        `json:"run_id"`
	StageID pgtype.UUID        `json:"stage_id"`
	Time    pgtype.Timestamptz `json:"time"`
	Level   string             `json:"level"`
	Message string             `json:"message"`
	Meta    []byte             `json:"meta"`
}

type Log struct {
	ID        int64              `json:"id"`
	RunID     pgtype.UUID        `json:"run_id"`
	StageID   pgtype.UUID        `json:"stage_id"`
	BuildID   pgtype.UUID        `json:"build_id"`
	ChunkNo   int32              `json:"chunk_no"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Node struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	IpAddress       netip.Addr         `json:"ip_address"`
	Version         *string            `json:"version"`
	Concurrency     int32              `json:"concurrency"`
	CpuTotalMillis  int32              `json:"cpu_total_millis"`
	CpuFreeMillis   int32              `json:"cpu_free_millis"`
	MemTotalBytes   int64              `json:"mem_total_bytes"`
	MemFreeBytes    int64              `json:"mem_free_bytes"`
	DiskTotalBytes  int64              `json:"disk_total_bytes"`
	DiskFreeBytes   int64              `json:"disk_free_bytes"`
	Drained         bool               `json:"drained"`
	CertSerial      *string            `json:"cert_serial"`
	CertFingerprint *string            `json:"cert_fingerprint"`
	CertNotBefore   pgtype.Timestamptz `json:"cert_not_before"`
	CertNotAfter    pgtype.Timestamptz `json:"cert_not_after"`
	LastHeartbeat   pgtype.Timestamptz `json:"last_heartbeat"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type NodeMetric struct {
	ID             int64              `json:"id"`
	NodeID         pgtype.UUID        `json:"node_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CpuTotalMillis int32              `json:"cpu_total_millis"`
	CpuFreeMillis  int32              `json:"cpu_free_millis"`
	MemTotalBytes  int64              `json:"mem_total_bytes"`
	MemFreeBytes   int64              `json:"mem_free_bytes"`
	DiskTotalBytes int64              `json:"disk_total_bytes"`
	DiskFreeBytes  int64              `json:"disk_free_bytes"`
}

type Run struct {
	ID         pgtype.UUID        `json:"id"`
	RepoUrl    string             `json:"repo_url"`
	Spec       []byte             `json:"spec"`
	CreatedBy  *string            `json:"created_by"`
	Status     RunStatus          `json:"status"`
	Reason     *string            `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	NodeID     pgtype.UUID        `json:"node_id"`
	BaseRef    string             `json:"base_ref"`
	TargetRef  string             `json:"target_ref"`
	CommitSha  *string            `json:"commit_sha"`
	Stats      []byte             `json:"stats"`
}

type RunsTiming struct {
	ID      pgtype.UUID `json:"id"`
	QueueMs int64       `json:"queue_ms"`
	RunMs   int64       `json:"run_ms"`
}

type Stage struct {
	ID         pgtype.UUID        `json:"id"`
	RunID      pgtype.UUID        `json:"run_id"`
	Name       string             `json:"name"`
	Status     StageStatus        `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	DurationMs int64              `json:"duration_ms"`
	Meta       []byte             `json:"meta"`
}
