// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"net/netip"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID          pgtype.UUID        `json:"id"`
	TokenHash   string             `json:"token_hash"`
	TokenID     string             `json:"token_id"`
	ClusterID   *string            `json:"cluster_id"`
	Role        string             `json:"role"`
	Description *string            `json:"description"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedBy   *string            `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ArtifactBundle struct {
	ID         pgtype.UUID        `json:"id"`
	RunID      types.RunID        `json:"run_id"`
	JobID      *types.JobID       `json:"job_id"`
	Name       *string            `json:"name"`
	BundleSize int64              `json:"bundle_size"`
	ObjectKey  *string            `json:"object_key"`
	Cid        *string            `json:"cid"`
	Digest     *string            `json:"digest"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BootstrapToken struct {
	ID           pgtype.UUID        `json:"id"`
	TokenHash    string             `json:"token_hash"`
	TokenID      string             `json:"token_id"`
	NodeID       *types.NodeID      `json:"node_id"`
	ClusterID    *string            `json:"cluster_id"`
	IssuedAt     pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	CertIssuedAt pgtype.Timestamptz `json:"cert_issued_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	IssuedBy     *string            `json:"issued_by"`
}

type ConfigBundleMap struct {
	Hash      string             `json:"hash"`
	BundleID  string             `json:"bundle_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ConfigCa struct {
	Hash      string             `json:"hash"`
	Section   string             `json:"section"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ConfigEnv struct {
	Key       string             `json:"key"`
	Target    string             `json:"target"`
	Value     string             `json:"value"`
	Secret    bool               `json:"secret"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ConfigHome struct {
	Entry     string             `json:"entry"`
	Dst       string             `json:"dst"`
	Section   string             `json:"section"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ConfigIn struct {
	Entry     string             `json:"entry"`
	Dst       string             `json:"dst"`
	Section   string             `json:"section"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Diff struct {
	ID        pgtype.UUID        `json:"id"`
	RunID     types.RunID        `json:"run_id"`
	JobID     *types.JobID       `json:"job_id"`
	PatchSize int64              `json:"patch_size"`
	ObjectKey *string            `json:"object_key"`
	Summary   []byte             `json:"summary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID      int64              `json:"id"`
	RunID   types.RunID        `json:"run_id"`
	JobID   *types.JobID       `json:"job_id"`
	Time    pgtype.Timestamptz `json:"time"`
	Level   string             `json:"level"`
	Message string             `json:"message"`
	Meta    []byte             `json:"meta"`
}

type Gate struct {
	JobID     string             `json:"job_id"`
	ProfileID int64              `json:"profile_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GateProfile struct {
	ID        int64              `json:"id"`
	RepoID    *string            `json:"repo_id"`
	RepoSha   *string            `json:"repo_sha"`
	RepoSha8  *string            `json:"repo_sha8"`
	StackID   int64              `json:"stack_id"`
	Url       string             `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type HooksOnce struct {
	RunID             types.RunID        `json:"run_id"`
	RepoID            types.RepoID       `json:"repo_id"`
	HookHash          string             `json:"hook_hash"`
	FirstSuccessJobID *types.JobID       `json:"first_success_job_id"`
	LastSuccessJobID  *types.JobID       `json:"last_success_job_id"`
	LastSkipJobID     *types.JobID       `json:"last_skip_job_id"`
	OnceSkipMarked    bool               `json:"once_skip_marked"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID          types.JobID        `json:"id"`
	RunID       types.RunID        `json:"run_id"`
	RepoID      types.RepoID       `json:"repo_id"`
	RepoBaseRef string             `json:"repo_base_ref"`
	Attempt     int32              `json:"attempt"`
	Name        string             `json:"name"`
	Status      types.JobStatus    `json:"status"`
	JobType     types.JobType      `json:"job_type"`
	JobImage    string             `json:"job_image"`
	NextID      *types.JobID       `json:"next_id"`
	NodeID      *types.NodeID      `json:"node_id"`
	ExitCode    *int32             `json:"exit_code"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	DurationMs  int64              `json:"duration_ms"`
	RepoShaIn   string             `json:"repo_sha_in"`
	RepoShaOut  string             `json:"repo_sha_out"`
	RepoShaIn8  string             `json:"repo_sha_in8"`
	RepoShaOut8 string             `json:"repo_sha_out8"`
	CacheKey    string             `json:"cache_key"`
	Meta        []byte             `json:"meta"`
}

type JobMetric struct {
	ID                int64              `json:"id"`
	NodeID            types.NodeID       `json:"node_id"`
	JobID             types.JobID        `json:"job_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CpuConsumedNs     int64              `json:"cpu_consumed_ns"`
	DiskConsumedBytes int64              `json:"disk_consumed_bytes"`
	MemConsumedBytes  int64              `json:"mem_consumed_bytes"`
}

type Log struct {
	ID        int64              `json:"id"`
	RunID     types.RunID        `json:"run_id"`
	JobID     *types.JobID       `json:"job_id"`
	ChunkNo   int32              `json:"chunk_no"`
	DataSize  int64              `json:"data_size"`
	ObjectKey *string            `json:"object_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Mig struct {
	ID         types.MigID        `json:"id"`
	Name       string             `json:"name"`
	SpecID     *types.SpecID      `json:"spec_id"`
	CreatedBy  *string            `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type MigRepo struct {
	ID        types.MigRepoID    `json:"id"`
	MigID     types.MigID        `json:"mig_id"`
	RepoID    types.RepoID       `json:"repo_id"`
	BaseRef   string             `json:"base_ref"`
	TargetRef string             `json:"target_ref"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Node struct {
	ID              types.NodeID       `json:"id"`
	Name            string             `json:"name"`
	IpAddress       netip.Addr         `json:"ip_address"`
	Version         *string            `json:"version"`
	Concurrency     int32              `json:"concurrency"`
	CpuTotalMillis  int32              `json:"cpu_total_millis"`
	CpuFreeMillis   int32              `json:"cpu_free_millis"`
	MemTotalBytes   int64              `json:"mem_total_bytes"`
	MemFreeBytes    int64              `json:"mem_free_bytes"`
	DiskTotalBytes  int64              `json:"disk_total_bytes"`
	DiskFreeBytes   int64              `json:"disk_free_bytes"`
	Drained         bool               `json:"drained"`
	CertSerial      *string            `json:"cert_serial"`
	CertFingerprint *string            `json:"cert_fingerprint"`
	CertNotBefore   pgtype.Timestamptz `json:"cert_not_before"`
	CertNotAfter    pgtype.Timestamptz `json:"cert_not_after"`
	LastHeartbeat   pgtype.Timestamptz `json:"last_heartbeat"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type NodeMetric struct {
	ID             int64              `json:"id"`
	NodeID         types.NodeID       `json:"node_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CpuTotalMillis int32              `json:"cpu_total_millis"`
	CpuFreeMillis  int32              `json:"cpu_free_millis"`
	MemTotalBytes  int64              `json:"mem_total_bytes"`
	MemFreeBytes   int64              `json:"mem_free_bytes"`
	DiskTotalBytes int64              `json:"disk_total_bytes"`
	DiskFreeBytes  int64              `json:"disk_free_bytes"`
}

type PloySchemaVersion struct {
	Version   int64              `json:"version"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type Repo struct {
	ID        types.RepoID       `json:"id"`
	Url       string             `json:"url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Run struct {
	ID         types.RunID        `json:"id"`
	MigID      types.MigID        `json:"mig_id"`
	SpecID     types.SpecID       `json:"spec_id"`
	CreatedBy  *string            `json:"created_by"`
	Status     types.RunStatus    `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	Stats      []byte             `json:"stats"`
}

type RunRepo struct {
	MigID           types.MigID         `json:"mig_id"`
	RunID           types.RunID         `json:"run_id"`
	RepoID          types.RepoID        `json:"repo_id"`
	RepoBaseRef     string              `json:"repo_base_ref"`
	RepoTargetRef   string              `json:"repo_target_ref"`
	SourceCommitSha string              `json:"source_commit_sha"`
	RepoSha0        string              `json:"repo_sha0"`
	Status          types.RunRepoStatus `json:"status"`
	Attempt         int32               `json:"attempt"`
	LastError       *string             `json:"last_error"`
	CreatedAt       pgtype.Timestamptz  `json:"created_at"`
	StartedAt       pgtype.Timestamptz  `json:"started_at"`
	FinishedAt      pgtype.Timestamptz  `json:"finished_at"`
}

type RunRepoAction struct {
	ID         types.JobID        `json:"id"`
	RunID      types.RunID        `json:"run_id"`
	RepoID     types.RepoID       `json:"repo_id"`
	Attempt    int32              `json:"attempt"`
	ActionType string             `json:"action_type"`
	Status     types.JobStatus    `json:"status"`
	NodeID     *types.NodeID      `json:"node_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	DurationMs int64              `json:"duration_ms"`
	Meta       []byte             `json:"meta"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RunsTiming struct {
	ID      types.RunID `json:"id"`
	QueueMs int64       `json:"queue_ms"`
	RunMs   int64       `json:"run_ms"`
}

type Sbom struct {
	JobID  types.JobID  `json:"job_id"`
	RepoID types.RepoID `json:"repo_id"`
	Lib    string       `json:"lib"`
	Ver    string       `json:"ver"`
}

type Spec struct {
	ID         types.SpecID       `json:"id"`
	Name       string             `json:"name"`
	Spec       []byte             `json:"spec"`
	CreatedBy  *string            `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type SpecBundle struct {
	ID        string             `json:"id"`
	Cid       string             `json:"cid"`
	Digest    string             `json:"digest"`
	Size      int64              `json:"size"`
	ObjectKey *string            `json:"object_key"`
	CreatedBy *string            `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastRefAt pgtype.Timestamptz `json:"last_ref_at"`
}

type Stack struct {
	ID        int64              `json:"id"`
	Lang      string             `json:"lang"`
	Release   string             `json:"release"`
	Tool      *string            `json:"tool"`
	Image     string             `json:"image"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
