// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mods.sql

package store

import (
	"context"
)

const createMod = `-- name: CreateMod :one
INSERT INTO mods (id, name, spec_id, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, spec_id, created_by, created_at, archived_at
`

type CreateModParams struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	SpecID    *string `json:"spec_id"`
	CreatedBy *string `json:"created_by"`
}

func (q *Queries) CreateMod(ctx context.Context, arg CreateModParams) (Mod, error) {
	row := q.db.QueryRow(ctx, createMod,
		arg.ID,
		arg.Name,
		arg.SpecID,
		arg.CreatedBy,
	)
	var i Mod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpecID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getMod = `-- name: GetMod :one
SELECT id, name, spec_id, created_by, created_at, archived_at
FROM mods
WHERE id = $1
`

func (q *Queries) GetMod(ctx context.Context, id string) (Mod, error) {
	row := q.db.QueryRow(ctx, getMod, id)
	var i Mod
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SpecID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateModSpec = `-- name: UpdateModSpec :exec
UPDATE mods
SET spec_id = $2
WHERE id = $1
`

type UpdateModSpecParams struct {
	ID     string  `json:"id"`
	SpecID *string `json:"spec_id"`
}

func (q *Queries) UpdateModSpec(ctx context.Context, arg UpdateModSpecParams) error {
	_, err := q.db.Exec(ctx, updateModSpec, arg.ID, arg.SpecID)
	return err
}
