// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mods.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMod = `-- name: CreateMod :one
INSERT INTO mods (repo_id, spec, created_by)
VALUES ($1, $2, $3)
RETURNING id, repo_id, spec, created_by, created_at
`

type CreateModParams struct {
	RepoID    pgtype.UUID `json:"repo_id"`
	Spec      []byte      `json:"spec"`
	CreatedBy *string     `json:"created_by"`
}

func (q *Queries) CreateMod(ctx context.Context, arg CreateModParams) (Mod, error) {
	row := q.db.QueryRow(ctx, createMod, arg.RepoID, arg.Spec, arg.CreatedBy)
	var i Mod
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Spec,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMod = `-- name: DeleteMod :exec
DELETE FROM mods
WHERE id = $1
`

func (q *Queries) DeleteMod(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMod, id)
	return err
}

const getMod = `-- name: GetMod :one
SELECT id, repo_id, spec, created_by, created_at FROM mods
WHERE id = $1
`

func (q *Queries) GetMod(ctx context.Context, id pgtype.UUID) (Mod, error) {
	row := q.db.QueryRow(ctx, getMod, id)
	var i Mod
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Spec,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listMods = `-- name: ListMods :many
SELECT id, repo_id, spec, created_by, created_at FROM mods
ORDER BY created_at DESC
`

func (q *Queries) ListMods(ctx context.Context) ([]Mod, error) {
	rows, err := q.db.Query(ctx, listMods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mod{}
	for rows.Next() {
		var i Mod
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Spec,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModsByRepo = `-- name: ListModsByRepo :many
SELECT id, repo_id, spec, created_by, created_at FROM mods
WHERE repo_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListModsByRepo(ctx context.Context, repoID pgtype.UUID) ([]Mod, error) {
	rows, err := q.db.Query(ctx, listModsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mod{}
	for rows.Next() {
		var i Mod
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Spec,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
