// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node_actions.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const claimNodeAction = `-- name: ClaimNodeAction :one
WITH eligible AS (
  SELECT a.id
  FROM node_actions a
  WHERE a.node_id = $1
    AND $1::TEXT != ''
    AND a.status = 'Queued'
  ORDER BY a.id ASC
  FOR UPDATE SKIP LOCKED
  LIMIT 1
)
UPDATE node_actions a
SET status = 'Running',
    started_at = now()
FROM eligible
WHERE a.id = eligible.id
RETURNING a.id, a.node_id, a.action_type, a.status, a.started_at, a.finished_at, a.duration_ms, a.meta, a.result, a.created_at
`

func (q *Queries) ClaimNodeAction(ctx context.Context, nodeID types.NodeID) (NodeAction, error) {
	row := q.db.QueryRow(ctx, claimNodeAction, nodeID)
	var i NodeAction
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ActionType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const createNodeAction = `-- name: CreateNodeAction :one
INSERT INTO node_actions (
  id,
  node_id,
  action_type,
  status,
  meta
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, node_id, action_type, status, started_at, finished_at, duration_ms, meta, result, created_at
`

type CreateNodeActionParams struct {
	ID         types.JobID     `json:"id"`
	NodeID     types.NodeID    `json:"node_id"`
	ActionType string          `json:"action_type"`
	Status     types.JobStatus `json:"status"`
	Meta       []byte          `json:"meta"`
}

func (q *Queries) CreateNodeAction(ctx context.Context, arg CreateNodeActionParams) (NodeAction, error) {
	row := q.db.QueryRow(ctx, createNodeAction,
		arg.ID,
		arg.NodeID,
		arg.ActionType,
		arg.Status,
		arg.Meta,
	)
	var i NodeAction
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ActionType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeAction = `-- name: GetNodeAction :one
SELECT id, node_id, action_type, status, started_at, finished_at, duration_ms, meta, result, created_at
FROM node_actions
WHERE id = $1
`

func (q *Queries) GetNodeAction(ctx context.Context, id types.JobID) (NodeAction, error) {
	row := q.db.QueryRow(ctx, getNodeAction, id)
	var i NodeAction
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.ActionType,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const listNodeActions = `-- name: ListNodeActions :many
SELECT id, node_id, action_type, status, started_at, finished_at, duration_ms, meta, result, created_at
FROM node_actions
WHERE node_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListNodeActionsParams struct {
	NodeID types.NodeID `json:"node_id"`
	Limit  int32        `json:"limit"`
}

func (q *Queries) ListNodeActions(ctx context.Context, arg ListNodeActionsParams) ([]NodeAction, error) {
	rows, err := q.db.Query(ctx, listNodeActions, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeAction{}
	for rows.Next() {
		var i NodeAction
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.ActionType,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Meta,
			&i.Result,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeActionCompletion = `-- name: UpdateNodeActionCompletion :exec
UPDATE node_actions
SET status = $2,
    finished_at = now(),
    duration_ms = COALESCE(EXTRACT(EPOCH FROM (now() - started_at)) * 1000, 0)::BIGINT,
    result = $3
WHERE id = $1
`

type UpdateNodeActionCompletionParams struct {
	ID     types.JobID     `json:"id"`
	Status types.JobStatus `json:"status"`
	Result []byte          `json:"result"`
}

func (q *Queries) UpdateNodeActionCompletion(ctx context.Context, arg UpdateNodeActionCompletionParams) error {
	_, err := q.db.Exec(ctx, updateNodeActionCompletion, arg.ID, arg.Status, arg.Result)
	return err
}
