// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: node_diagnostics.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNodeDaemonLog = `-- name: CreateNodeDaemonLog :one
INSERT INTO node_daemon_logs (
  node_id,
  component,
  stream,
  message
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, node_id, component, stream, message, created_at
`

type CreateNodeDaemonLogParams struct {
	NodeID    types.NodeID `json:"node_id"`
	Component string       `json:"component"`
	Stream    string       `json:"stream"`
	Message   string       `json:"message"`
}

func (q *Queries) CreateNodeDaemonLog(ctx context.Context, arg CreateNodeDaemonLogParams) (NodeDaemonLog, error) {
	row := q.db.QueryRow(ctx, createNodeDaemonLog,
		arg.NodeID,
		arg.Component,
		arg.Stream,
		arg.Message,
	)
	var i NodeDaemonLog
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Component,
		&i.Stream,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listNodeDaemonLogs = `-- name: ListNodeDaemonLogs :many
SELECT id, node_id, component, stream, message, created_at FROM node_daemon_logs
WHERE node_id = $1
  AND ($2::text IS NULL OR component = $2::text)
ORDER BY id DESC
LIMIT $3
`

type ListNodeDaemonLogsParams struct {
	NodeID     types.NodeID `json:"node_id"`
	Component  *string      `json:"component"`
	LimitCount int32        `json:"limit_count"`
}

func (q *Queries) ListNodeDaemonLogs(ctx context.Context, arg ListNodeDaemonLogsParams) ([]NodeDaemonLog, error) {
	rows, err := q.db.Query(ctx, listNodeDaemonLogs, arg.NodeID, arg.Component, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeDaemonLog{}
	for rows.Next() {
		var i NodeDaemonLog
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Component,
			&i.Stream,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeDiagnostics = `-- name: ListNodeDiagnostics :many
SELECT node_id, component, status, last_error, version, image_ref, local_image_id, remote_image_id, details, last_checked_at, last_success_at, updated_at FROM node_diagnostics
WHERE node_id = $1
ORDER BY component
`

func (q *Queries) ListNodeDiagnostics(ctx context.Context, nodeID types.NodeID) ([]NodeDiagnostic, error) {
	rows, err := q.db.Query(ctx, listNodeDiagnostics, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeDiagnostic{}
	for rows.Next() {
		var i NodeDiagnostic
		if err := rows.Scan(
			&i.NodeID,
			&i.Component,
			&i.Status,
			&i.LastError,
			&i.Version,
			&i.ImageRef,
			&i.LocalImageID,
			&i.RemoteImageID,
			&i.Details,
			&i.LastCheckedAt,
			&i.LastSuccessAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimNodeDaemonLogs = `-- name: TrimNodeDaemonLogs :exec
DELETE FROM node_daemon_logs
WHERE node_daemon_logs.node_id = $1
  AND node_daemon_logs.component = $2
  AND id NOT IN (
  SELECT id
  FROM node_daemon_logs
  WHERE node_daemon_logs.node_id = $1
    AND node_daemon_logs.component = $2
  ORDER BY id DESC
  LIMIT $3
)
`

type TrimNodeDaemonLogsParams struct {
	NodeID    types.NodeID `json:"node_id"`
	Component string       `json:"component"`
	KeepCount int32        `json:"keep_count"`
}

func (q *Queries) TrimNodeDaemonLogs(ctx context.Context, arg TrimNodeDaemonLogsParams) error {
	_, err := q.db.Exec(ctx, trimNodeDaemonLogs, arg.NodeID, arg.Component, arg.KeepCount)
	return err
}

const upsertNodeDiagnostic = `-- name: UpsertNodeDiagnostic :one
INSERT INTO node_diagnostics (
  node_id,
  component,
  status,
  last_error,
  version,
  image_ref,
  local_image_id,
  remote_image_id,
  details,
  last_checked_at,
  last_success_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  now()
)
ON CONFLICT (node_id, component) DO UPDATE
SET
  status = EXCLUDED.status,
  last_error = EXCLUDED.last_error,
  version = EXCLUDED.version,
  image_ref = EXCLUDED.image_ref,
  local_image_id = EXCLUDED.local_image_id,
  remote_image_id = EXCLUDED.remote_image_id,
  details = EXCLUDED.details,
  last_checked_at = EXCLUDED.last_checked_at,
  last_success_at = EXCLUDED.last_success_at,
  updated_at = now()
RETURNING node_id, component, status, last_error, version, image_ref, local_image_id, remote_image_id, details, last_checked_at, last_success_at, updated_at
`

type UpsertNodeDiagnosticParams struct {
	NodeID        types.NodeID       `json:"node_id"`
	Component     string             `json:"component"`
	Status        string             `json:"status"`
	LastError     *string            `json:"last_error"`
	Version       *string            `json:"version"`
	ImageRef      *string            `json:"image_ref"`
	LocalImageID  *string            `json:"local_image_id"`
	RemoteImageID *string            `json:"remote_image_id"`
	Details       []byte             `json:"details"`
	LastCheckedAt pgtype.Timestamptz `json:"last_checked_at"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
}

func (q *Queries) UpsertNodeDiagnostic(ctx context.Context, arg UpsertNodeDiagnosticParams) (NodeDiagnostic, error) {
	row := q.db.QueryRow(ctx, upsertNodeDiagnostic,
		arg.NodeID,
		arg.Component,
		arg.Status,
		arg.LastError,
		arg.Version,
		arg.ImageRef,
		arg.LocalImageID,
		arg.RemoteImageID,
		arg.Details,
		arg.LastCheckedAt,
		arg.LastSuccessAt,
	)
	var i NodeDiagnostic
	err := row.Scan(
		&i.NodeID,
		&i.Component,
		&i.Status,
		&i.LastError,
		&i.Version,
		&i.ImageRef,
		&i.LocalImageID,
		&i.RemoteImageID,
		&i.Details,
		&i.LastCheckedAt,
		&i.LastSuccessAt,
		&i.UpdatedAt,
	)
	return i, err
}
