// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prep_runs.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const createPrepRun = `-- name: CreatePrepRun :one
INSERT INTO prep_runs (repo_id, attempt, status, started_at, result_json, logs_ref)
VALUES ($1, $2, $3, now(), $4, $5)
RETURNING repo_id, attempt, status, started_at, finished_at, result_json, logs_ref
`

type CreatePrepRunParams struct {
	RepoID     types.MigRepoID `json:"repo_id"`
	Attempt    int32           `json:"attempt"`
	Status     PrepStatus      `json:"status"`
	ResultJson []byte          `json:"result_json"`
	LogsRef    *string         `json:"logs_ref"`
}

func (q *Queries) CreatePrepRun(ctx context.Context, arg CreatePrepRunParams) (PrepRun, error) {
	row := q.db.QueryRow(ctx, createPrepRun,
		arg.RepoID,
		arg.Attempt,
		arg.Status,
		arg.ResultJson,
		arg.LogsRef,
	)
	var i PrepRun
	err := row.Scan(
		&i.RepoID,
		&i.Attempt,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ResultJson,
		&i.LogsRef,
	)
	return i, err
}

const finishPrepRun = `-- name: FinishPrepRun :one
UPDATE prep_runs
SET status = $3,
    finished_at = now(),
    result_json = $4,
    logs_ref = $5
WHERE repo_id = $1
  AND attempt = $2
RETURNING repo_id, attempt, status, started_at, finished_at, result_json, logs_ref
`

type FinishPrepRunParams struct {
	RepoID     types.MigRepoID `json:"repo_id"`
	Attempt    int32           `json:"attempt"`
	Status     PrepStatus      `json:"status"`
	ResultJson []byte          `json:"result_json"`
	LogsRef    *string         `json:"logs_ref"`
}

func (q *Queries) FinishPrepRun(ctx context.Context, arg FinishPrepRunParams) (PrepRun, error) {
	row := q.db.QueryRow(ctx, finishPrepRun,
		arg.RepoID,
		arg.Attempt,
		arg.Status,
		arg.ResultJson,
		arg.LogsRef,
	)
	var i PrepRun
	err := row.Scan(
		&i.RepoID,
		&i.Attempt,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ResultJson,
		&i.LogsRef,
	)
	return i, err
}
