// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Archives a mig by setting archived_at to now().
	// Archiving must be refused when the mig has any jobs in a running state.
	// This query only sets the timestamp; validation logic must be in the caller.
	ArchiveMig(ctx context.Context, id types.MigID) error
	// Bulk-cancels active jobs for a run (Created/Queued/Running -> Cancelled).
	// finished_at is set once; duration_ms is computed from started_at when present.
	CancelActiveJobsByRun(ctx context.Context, runID types.RunID) (int64, error)
	// Bulk-cancels active jobs for a specific repo attempt.
	// Targets Created/Queued/Running and preserves terminal jobs.
	// finished_at is set once; duration_ms is computed from started_at when present.
	CancelActiveJobsByRunRepoAttempt(ctx context.Context, arg CancelActiveJobsByRunRepoAttemptParams) (int64, error)
	// Bulk-cancels active repos for a run (Queued/Running -> Cancelled).
	CancelActiveRunReposByRun(ctx context.Context, runID types.RunID) (int64, error)
	CheckAPITokenRevoked(ctx context.Context, tokenID string) (pgtype.Timestamptz, error)
	CheckBootstrapTokenRevoked(ctx context.Context, tokenID string) (pgtype.Timestamptz, error)
	// Atomically claim the next claimable job for a node (unified queue).
	// v1:
	// - claimable jobs have status='Queued'
	// - normal jobs are claimable only when runs.status='Started'
	// - MR jobs (job_type='mr') are claimable only when runs.status='Finished'
	// - nodeID must be non-empty
	ClaimJob(ctx context.Context, nodeID types.NodeID) (Job, error)
	ClaimNextPrepRepo(ctx context.Context) (MigRepo, error)
	ClaimNextPrepRetryRepo(ctx context.Context, prepUpdatedAt pgtype.Timestamptz) (MigRepo, error)
	CountJobsByRun(ctx context.Context, runID types.RunID) (int64, error)
	CountJobsByRunAndStatus(ctx context.Context, arg CountJobsByRunAndStatusParams) (int64, error)
	// Counts jobs by status for a specific repo attempt, excluding MR jobs.
	// Used by repo-scoped terminal detection to determine run_repos.status.
	// MR jobs (job_type='mr') are auxiliary and must not affect run_repos.status derivation.
	CountJobsByRunRepoAttemptGroupByStatus(ctx context.Context, arg CountJobsByRunRepoAttemptGroupByStatusParams) ([]CountJobsByRunRepoAttemptGroupByStatusRow, error)
	CountRunReposByStatus(ctx context.Context, runID types.RunID) ([]CountRunReposByStatusRow, error)
	// Counts distinct stale nodes that currently have at least one running job.
	// Excludes NULL node_id rows (orphaned running jobs) from node count.
	CountStaleNodesWithRunningJobs(ctx context.Context, lastHeartbeat pgtype.Timestamptz) (int64, error)
	// Creates a new artifact bundle metadata. Blob data is stored in object storage.
	// Bundles are grouped at the job level only (build_id removed).
	CreateArtifactBundle(ctx context.Context, arg CreateArtifactBundleParams) (ArtifactBundle, error)
	// Creates a new diff entry associated with a job. Blob data is stored in object storage.
	CreateDiff(ctx context.Context, arg CreateDiffParams) (Diff, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// Note: `id` is a required TEXT parameter (KSUID-backed); caller generates via types.NewJobID().
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	// Creates a new log chunk metadata. Blob data is stored in object storage.
	// Logs are grouped at the job level only (build_id removed).
	CreateLog(ctx context.Context, arg CreateLogParams) (Log, error)
	CreateMig(ctx context.Context, arg CreateMigParams) (Mig, error)
	CreateMigRepo(ctx context.Context, arg CreateMigRepoParams) (MigRepo, error)
	// Creates a new node with an application-supplied NanoID(6) as the primary key.
	// The `id` parameter must be generated via types.NewNodeKey() before calling.
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreatePrepRun(ctx context.Context, arg CreatePrepRunParams) (PrepRun, error)
	// v1: Creates a new run for a mig + spec snapshot. Runs are created in Started state.
	// Note: `id` is a required TEXT parameter (KSUID-backed); caller generates via types.NewRunID().
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	// v1: Creates a new run_repos row scoped to (run_id, repo_id).
	// Note: attempt defaults to 1; status defaults to 'Queued'.
	CreateRunRepo(ctx context.Context, arg CreateRunRepoParams) (RunRepo, error)
	CreateSpec(ctx context.Context, arg CreateSpecParams) (Spec, error)
	DeleteArtifactBundle(ctx context.Context, id pgtype.UUID) error
	DeleteArtifactBundlesOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error
	DeleteDiff(ctx context.Context, id pgtype.UUID) error
	DeleteDiffsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error
	// DeleteExpiredArtifactBundles removes artifact bundle rows older than the specified timestamp.
	DeleteExpiredArtifactBundles(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	// DeleteExpiredDiffs removes diff rows older than the specified timestamp.
	DeleteExpiredDiffs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	// DeleteExpiredEvents removes event rows older than the specified timestamp.
	DeleteExpiredEvents(ctx context.Context, time pgtype.Timestamptz) (int64, error)
	// DeleteExpiredLogs removes log rows older than the specified timestamp.
	DeleteExpiredLogs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	// Removes an environment entry by key.
	// No-op if the key does not exist (exec returns no error).
	DeleteGlobalEnv(ctx context.Context, key string) error
	DeleteJob(ctx context.Context, id types.JobID) error
	DeleteLog(ctx context.Context, id int64) error
	DeleteLogsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error
	// Deletes a mig. Use with caution; should only be called when safe to remove.
	DeleteMig(ctx context.Context, id types.MigID) error
	// Deletes a mod_repo by id.
	// Note: mig_repos.id is referenced by run_repos.repo_id and jobs.repo_id with ON DELETE RESTRICT.
	// This DELETE will fail if any run_repos/jobs rows still reference the repo.
	DeleteMigRepo(ctx context.Context, id types.MigRepoID) error
	DeleteNode(ctx context.Context, id types.NodeID) error
	DeleteRun(ctx context.Context, id types.RunID) error
	DeleteRunRepo(ctx context.Context, arg DeleteRunRepoParams) error
	FinishPrepRun(ctx context.Context, arg FinishPrepRunParams) (PrepRun, error)
	// Transitional: returns current job id and linked successor id.
	GetAdjacentJobIndices(ctx context.Context, id types.JobID) (GetAdjacentJobIndicesRow, error)
	// Returns artifact bundle metadata including object_key for object-storage retrieval.
	GetArtifactBundle(ctx context.Context, id pgtype.UUID) (ArtifactBundle, error)
	GetBootstrapToken(ctx context.Context, tokenID string) (GetBootstrapTokenRow, error)
	// Returns diff metadata including object_key for object-storage retrieval.
	GetDiff(ctx context.Context, id pgtype.UUID) (Diff, error)
	GetEvent(ctx context.Context, id int64) (Event, error)
	// Retrieves a single environment entry by key.
	// Returns pgx.ErrNoRows if the key does not exist.
	GetGlobalEnv(ctx context.Context, key string) (ConfigEnv, error)
	GetJob(ctx context.Context, id types.JobID) (Job, error)
	// v1: Gets the newest run_repos row for a specific repo_id in a mig,
	// filtered by terminal status (Success or Fail).
	// Used by POST /v1/migs/{mig_id}/pull to select last-succeeded or last-failed.
	// Order by created_at DESC to get the newest matching run_repos row.
	GetLatestRunRepoByMigAndRepoStatus(ctx context.Context, arg GetLatestRunRepoByMigAndRepoStatusParams) (GetLatestRunRepoByMigAndRepoStatusRow, error)
	// Returns log metadata including object_key for object-storage retrieval.
	GetLog(ctx context.Context, id int64) (Log, error)
	GetMig(ctx context.Context, id types.MigID) (Mig, error)
	GetMigByName(ctx context.Context, name string) (Mig, error)
	GetMigRepo(ctx context.Context, id types.MigRepoID) (MigRepo, error)
	// Gets a mod_repo by mig_id and repo_url (for uniqueness constraint enforcement).
	GetMigRepoByURL(ctx context.Context, arg GetMigRepoByURLParams) (MigRepo, error)
	GetNode(ctx context.Context, id types.NodeID) (Node, error)
	GetRun(ctx context.Context, id types.RunID) (Run, error)
	GetRunRepo(ctx context.Context, arg GetRunRepoParams) (RunRepo, error)
	GetRunTiming(ctx context.Context, id types.RunID) (RunsTiming, error)
	GetSpec(ctx context.Context, id types.SpecID) (Spec, error)
	// Checks if a mod_repo has any historical executions (run_repos references).
	// Returns true if the repo cannot be deleted due to history, false otherwise.
	// Deletion is refused if the repo has historical executions.
	HasMigRepoHistory(ctx context.Context, repoID types.MigRepoID) (bool, error)
	// Increments attempt and resets status/timing for a fresh repo execution attempt.
	IncrementRunRepoAttempt(ctx context.Context, arg IncrementRunRepoAttemptParams) error
	InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error
	InsertBootstrapToken(ctx context.Context, arg InsertBootstrapTokenParams) error
	ListAPITokens(ctx context.Context, clusterID *string) ([]ListAPITokensRow, error)
	// ListArtifactBundlePartitions retrieves all partition names for the artifact_bundles table.
	ListArtifactBundlePartitions(ctx context.Context) ([]string, error)
	// Returns artifact bundle metadata including object_key for object-storage retrieval.
	ListArtifactBundlesByCID(ctx context.Context, cid *string) ([]ArtifactBundle, error)
	// Returns artifact bundle metadata including object_key for object-storage retrieval.
	ListArtifactBundlesByRun(ctx context.Context, runID types.RunID) ([]ArtifactBundle, error)
	// Returns artifact bundle metadata including object_key for object-storage retrieval.
	ListArtifactBundlesByRunAndJob(ctx context.Context, arg ListArtifactBundlesByRunAndJobParams) ([]ArtifactBundle, error)
	// Returns artifact bundle metadata for a given cid.
	ListArtifactBundlesMetaByCID(ctx context.Context, cid *string) ([]ArtifactBundle, error)
	// Returns artifact bundle metadata for a run.
	ListArtifactBundlesMetaByRun(ctx context.Context, runID types.RunID) ([]ArtifactBundle, error)
	// Returns artifact bundle metadata for a run and job.
	ListArtifactBundlesMetaByRunAndJob(ctx context.Context, arg ListArtifactBundlesMetaByRunAndJobParams) ([]ArtifactBundle, error)
	ListCreatedJobsByRunRepoAttempt(ctx context.Context, arg ListCreatedJobsByRunRepoAttemptParams) ([]Job, error)
	// Returns diffs for a specific repo execution within a run.
	// Repo attribution comes from joining diffs.job_id to jobs.repo_id.
	// This supports the repo-scoped endpoint GET /v1/runs/{run_id}/repos/{repo_id}/diffs.
	ListDiffsByRunRepo(ctx context.Context, arg ListDiffsByRunRepoParams) ([]Diff, error)
	// Returns diff metadata for a run.
	ListDiffsMetaByRun(ctx context.Context, runID types.RunID) ([]Diff, error)
	// Returns diff metadata for a specific repo within a run.
	ListDiffsMetaByRunRepo(ctx context.Context, arg ListDiffsMetaByRunRepoParams) ([]Diff, error)
	// v1: Lists distinct repos (mig_repos) with last known run metadata, optionally filtered by repo_url substring.
	ListDistinctRepos(ctx context.Context, filter string) ([]ListDistinctReposRow, error)
	// ListEventPartitions retrieves all partition names for the events table.
	ListEventPartitions(ctx context.Context) ([]string, error)
	ListEventsByRun(ctx context.Context, runID types.RunID) ([]Event, error)
	ListEventsByRunSince(ctx context.Context, arg ListEventsByRunSinceParams) ([]Event, error)
	// Returns event metadata (without the meta blob) for a run.
	// Use GetEvent to fetch the full event with meta by id.
	ListEventsMetaByRun(ctx context.Context, runID types.RunID) ([]ListEventsMetaByRunRow, error)
	// Returns event metadata (without the meta blob) for a run since a given id.
	// Use GetEvent to fetch the full event with meta by id.
	ListEventsMetaByRunSince(ctx context.Context, arg ListEventsMetaByRunSinceParams) ([]ListEventsMetaByRunSinceRow, error)
	// Lists repo_ids whose last terminal run_repos status is 'Fail' for a given mig.
	// "Last terminal state" per repo_id is determined by looking at the newest run_repos
	// row where status in (Fail, Success, Cancelled) and selecting those where status='Fail'.
	// Uses a subquery to get the last terminal status per repo, then filters for 'Fail'.
	ListFailedRepoIDsByMig(ctx context.Context, migID types.MigID) ([]types.MigRepoID, error)
	// config_env.sql — CRUD queries for global environment variables (config_env table).
	// Provides ListGlobalEnv, GetGlobalEnv, UpsertGlobalEnv, DeleteGlobalEnv.
	// Returns all global environment entries, ordered by key for consistent iteration.
	// Used by ConfigHolder initialization and HTTP list endpoint.
	ListGlobalEnv(ctx context.Context) ([]ConfigEnv, error)
	ListJobsByRun(ctx context.Context, runID types.RunID) ([]Job, error)
	ListJobsByRunRepoAttempt(ctx context.Context, arg ListJobsByRunRepoAttemptParams) ([]Job, error)
	// ListLogPartitions retrieves all partition names for the logs table.
	ListLogPartitions(ctx context.Context) ([]string, error)
	// Returns log metadata including object_key for object-storage retrieval.
	ListLogsByRun(ctx context.Context, runID types.RunID) ([]Log, error)
	// Returns log metadata including object_key for object-storage retrieval.
	ListLogsByRunAndJob(ctx context.Context, arg ListLogsByRunAndJobParams) ([]Log, error)
	// Returns log metadata including object_key for object-storage retrieval.
	ListLogsByRunAndJobSince(ctx context.Context, arg ListLogsByRunAndJobSinceParams) ([]Log, error)
	// Returns log metadata including object_key for object-storage retrieval.
	ListLogsByRunSince(ctx context.Context, arg ListLogsByRunSinceParams) ([]Log, error)
	// Returns log metadata for a run.
	ListLogsMetaByRun(ctx context.Context, runID types.RunID) ([]Log, error)
	// Returns log metadata for a run and job.
	ListLogsMetaByRunAndJob(ctx context.Context, arg ListLogsMetaByRunAndJobParams) ([]Log, error)
	// Returns log metadata for a run and job since a given id.
	ListLogsMetaByRunAndJobSince(ctx context.Context, arg ListLogsMetaByRunAndJobSinceParams) ([]Log, error)
	// Returns log metadata for a run since a given id.
	ListLogsMetaByRunSince(ctx context.Context, arg ListLogsMetaByRunSinceParams) ([]Log, error)
	ListMigReposByMig(ctx context.Context, migID types.MigID) ([]MigRepo, error)
	// Lists migs with optional filtering by archived status and name substring.
	// archived_only: if true, return only archived migs; if false, return only active migs; if null, return all.
	// name_filter: if non-empty, filter by name substring (case-insensitive); if null/empty, no name filtering.
	ListMigs(ctx context.Context, arg ListMigsParams) ([]Mig, error)
	// ListNodeMetricsPartitions retrieves all partition names for the node_metrics table.
	ListNodeMetricsPartitions(ctx context.Context) ([]string, error)
	ListNodes(ctx context.Context) ([]Node, error)
	ListQueuedRunReposByRun(ctx context.Context, runID types.RunID) ([]RunRepo, error)
	ListReposByPrepStatus(ctx context.Context, prepStatus PrepStatus) ([]MigRepo, error)
	// Lists all repos associated with a run, ordered by creation time.
	ListRunReposByRun(ctx context.Context, runID types.RunID) ([]RunRepo, error)
	// v1: Lists all run_repos for a run with their repo_url (from mig_repos).
	// Used by:
	// - GET  /v1/runs/{id}/repos (full repo response without N+1 lookups)
	// - POST /v1/runs/{run_id}/pull (repo resolution by normalized URL)
	ListRunReposWithURLByRun(ctx context.Context, runID types.RunID) ([]ListRunReposWithURLByRunRow, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error)
	// Lists runs for a given repo_id (mig_repos.id).
	ListRunsForRepo(ctx context.Context, arg ListRunsForRepoParams) ([]ListRunsForRepoRow, error)
	ListRunsTimings(ctx context.Context, arg ListRunsTimingsParams) ([]RunsTiming, error)
	// Lists runs that have queued work (at least one Queued run_repos row).
	ListRunsWithQueuedRepos(ctx context.Context) ([]types.RunID, error)
	// Lists specs ordered by created_at descending (most recent first).
	// There is an index on created_at to optimize this query.
	ListSpecs(ctx context.Context, arg ListSpecsParams) ([]Spec, error)
	// Lists running jobs whose assigned node is stale at the provided cutoff.
	// Rows are grouped by (run_id, repo_id, attempt) for deterministic recovery processing.
	ListStaleRunningJobs(ctx context.Context, lastHeartbeat pgtype.Timestamptz) ([]ListStaleRunningJobsRow, error)
	MarkBootstrapTokenCertIssued(ctx context.Context, tokenID string) error
	// Atomically promote a specific linked successor job: Created -> Queued.
	// The candidate is eligible only when every predecessor that points to it is Success.
	PromoteJobByIDIfUnblocked(ctx context.Context, id types.JobID) (Job, error)
	RevokeAPIToken(ctx context.Context, tokenID string) error
	SaveMigRepoPrepProfile(ctx context.Context, arg SaveMigRepoPrepProfileParams) error
	// Atomically promote the next unblocked job in a repo attempt: Created -> Queued.
	// A created job is unblocked when all predecessor jobs that point to it are Success.
	ScheduleNextJob(ctx context.Context, arg ScheduleNextJobParams) (Job, error)
	// Unarchives a mig by clearing archived_at.
	UnarchiveMig(ctx context.Context, id types.MigID) error
	UpdateAPITokenLastUsed(ctx context.Context, tokenID string) error
	UpdateBootstrapTokenLastUsed(ctx context.Context, tokenID string) error
	UpdateJobCompletion(ctx context.Context, arg UpdateJobCompletionParams) error
	UpdateJobCompletionWithMeta(ctx context.Context, arg UpdateJobCompletionWithMetaParams) error
	// Persist the container image name used to execute a job.
	// This is set by the node immediately before job execution starts.
	UpdateJobImageName(ctx context.Context, arg UpdateJobImageNameParams) error
	UpdateJobMeta(ctx context.Context, arg UpdateJobMetaParams) error
	UpdateJobNextID(ctx context.Context, arg UpdateJobNextIDParams) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpdateMigRepoPrepState(ctx context.Context, arg UpdateMigRepoPrepStateParams) error
	UpdateMigRepoRefs(ctx context.Context, arg UpdateMigRepoRefsParams) error
	UpdateMigSpec(ctx context.Context, arg UpdateMigSpecParams) error
	UpdateNodeCertMetadata(ctx context.Context, arg UpdateNodeCertMetadataParams) error
	UpdateNodeDrained(ctx context.Context, arg UpdateNodeDrainedParams) error
	UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) error
	UpdateRunCompletion(ctx context.Context, arg UpdateRunCompletionParams) error
	UpdateRunRepoError(ctx context.Context, arg UpdateRunRepoErrorParams) error
	// Updates snapshot refs for the run repo (used when restarting with new refs).
	UpdateRunRepoRefs(ctx context.Context, arg UpdateRunRepoRefsParams) error
	// Updates repo status + timing fields.
	// started_at: set when transitioning to Running.
	// finished_at: set when transitioning to a terminal status.
	UpdateRunRepoStatus(ctx context.Context, arg UpdateRunRepoStatusParams) error
	// Increments resume_count and updates last_resumed_at timestamp in runs.stats.
	// Uses JSONB merge (||) to preserve existing stats while adding resume metadata.
	UpdateRunResume(ctx context.Context, id types.RunID) error
	// Merge an MR URL into runs.stats.metadata.mr_url without altering other fields.
	// Preserves existing stats and metadata keys via JSONB merge.
	UpdateRunStatsMRURL(ctx context.Context, arg UpdateRunStatsMRURLParams) error
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error
	// Inserts or updates an environment entry (upsert on primary key 'key').
	// Updates value, scope, secret, and refreshes updated_at on conflict.
	// This ensures idempotent set operations from the CLI or API.
	UpsertGlobalEnv(ctx context.Context, arg UpsertGlobalEnvParams) error
	UpsertJobMetric(ctx context.Context, arg UpsertJobMetricParams) error
	// Bulk upsert a mod_repo by normalized repo_url.
	// Uniqueness is on (mig_id, repo_url) to prevent duplicate repo URLs per mig.
	// If a row exists, update refs; otherwise insert.
	UpsertMigRepo(ctx context.Context, arg UpsertMigRepoParams) (MigRepo, error)
}

var _ Querier = (*Queries)(nil)
