// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AckBuildGateJobStart(ctx context.Context, id pgtype.UUID) error
	AckRunStart(ctx context.Context, id pgtype.UUID) error
	CheckAPITokenRevoked(ctx context.Context, tokenID string) (pgtype.Timestamptz, error)
	CheckBootstrapTokenRevoked(ctx context.Context, tokenID string) (pgtype.Timestamptz, error)
	ClaimBuildGateJob(ctx context.Context, nodeID pgtype.UUID) (BuildgateJob, error)
	ClaimRun(ctx context.Context, nodeID pgtype.UUID) (Run, error)
	CreateArtifactBundle(ctx context.Context, arg CreateArtifactBundleParams) (ArtifactBundle, error)
	CreateBuildGateJob(ctx context.Context, requestPayload []byte) (BuildgateJob, error)
	CreateDiff(ctx context.Context, arg CreateDiffParams) (Diff, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateLog(ctx context.Context, arg CreateLogParams) (Log, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error)
	DeleteArtifactBundle(ctx context.Context, id pgtype.UUID) error
	DeleteArtifactBundlesOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error
	DeleteDiff(ctx context.Context, id pgtype.UUID) error
	DeleteDiffsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error
	// DeleteExpiredArtifactBundles removes artifact bundle rows older than the specified timestamp.
	DeleteExpiredArtifactBundles(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	// DeleteExpiredDiffs removes diff rows older than the specified timestamp.
	DeleteExpiredDiffs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	// DeleteExpiredEvents removes event rows older than the specified timestamp.
	DeleteExpiredEvents(ctx context.Context, time pgtype.Timestamptz) (int64, error)
	// DeleteExpiredLogs removes log rows older than the specified timestamp.
	DeleteExpiredLogs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	DeleteLog(ctx context.Context, id int64) error
	DeleteLogsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) error
	DeleteNode(ctx context.Context, id pgtype.UUID) error
	DeleteRun(ctx context.Context, id pgtype.UUID) error
	DeleteStage(ctx context.Context, id pgtype.UUID) error
	GetArtifactBundle(ctx context.Context, id pgtype.UUID) (ArtifactBundle, error)
	GetBootstrapToken(ctx context.Context, tokenID string) (GetBootstrapTokenRow, error)
	GetBuildGateJob(ctx context.Context, id pgtype.UUID) (BuildgateJob, error)
	GetDiff(ctx context.Context, id pgtype.UUID) (Diff, error)
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetLog(ctx context.Context, id int64) (Log, error)
	GetNode(ctx context.Context, id pgtype.UUID) (Node, error)
	GetRun(ctx context.Context, id pgtype.UUID) (Run, error)
	GetRunTiming(ctx context.Context, id pgtype.UUID) (RunsTiming, error)
	GetStage(ctx context.Context, id pgtype.UUID) (Stage, error)
	InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error
	InsertBootstrapToken(ctx context.Context, arg InsertBootstrapTokenParams) error
	InsertNodeWithID(ctx context.Context, arg InsertNodeWithIDParams) (Node, error)
	ListAPITokens(ctx context.Context, clusterID string) ([]ListAPITokensRow, error)
	// ListArtifactBundlePartitions retrieves all partition names for the artifact_bundles table.
	ListArtifactBundlePartitions(ctx context.Context) ([]string, error)
	ListArtifactBundlesByCID(ctx context.Context, cid *string) ([]ArtifactBundle, error)
	ListArtifactBundlesByRun(ctx context.Context, runID pgtype.UUID) ([]ArtifactBundle, error)
	ListArtifactBundlesByRunAndStage(ctx context.Context, arg ListArtifactBundlesByRunAndStageParams) ([]ArtifactBundle, error)
	ListDiffsByRun(ctx context.Context, runID pgtype.UUID) ([]Diff, error)
	// ListEventPartitions retrieves all partition names for the events table.
	ListEventPartitions(ctx context.Context) ([]string, error)
	ListEventsByRun(ctx context.Context, runID pgtype.UUID) ([]Event, error)
	ListEventsByRunSince(ctx context.Context, arg ListEventsByRunSinceParams) ([]Event, error)
	// ListLogPartitions retrieves all partition names for the logs table.
	ListLogPartitions(ctx context.Context) ([]string, error)
	ListLogsByRun(ctx context.Context, runID pgtype.UUID) ([]Log, error)
	ListLogsByRunAndStage(ctx context.Context, arg ListLogsByRunAndStageParams) ([]Log, error)
	ListLogsByRunAndStageSince(ctx context.Context, arg ListLogsByRunAndStageSinceParams) ([]Log, error)
	ListLogsByRunSince(ctx context.Context, arg ListLogsByRunSinceParams) ([]Log, error)
	ListLogsByRunStageAndBuild(ctx context.Context, arg ListLogsByRunStageAndBuildParams) ([]Log, error)
	ListLogsByRunStageAndBuildSince(ctx context.Context, arg ListLogsByRunStageAndBuildSinceParams) ([]Log, error)
	// ListNodeMetricsPartitions retrieves all partition names for the node_metrics table.
	ListNodeMetricsPartitions(ctx context.Context) ([]string, error)
	ListNodes(ctx context.Context) ([]Node, error)
	ListPendingBuildGateJobs(ctx context.Context, arg ListPendingBuildGateJobsParams) ([]BuildgateJob, error)
	ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error)
	ListRunsTimings(ctx context.Context, arg ListRunsTimingsParams) ([]RunsTiming, error)
	ListStagesByRun(ctx context.Context, runID pgtype.UUID) ([]Stage, error)
	MarkBootstrapTokenCertIssued(ctx context.Context, tokenID string) error
	RevokeAPIToken(ctx context.Context, tokenID string) error
	UpdateAPITokenLastUsed(ctx context.Context, tokenID string) error
	UpdateBootstrapTokenLastUsed(ctx context.Context, tokenID string) error
	UpdateBuildGateJobCompletion(ctx context.Context, arg UpdateBuildGateJobCompletionParams) error
	UpdateNodeCertMetadata(ctx context.Context, arg UpdateNodeCertMetadataParams) error
	UpdateNodeDrained(ctx context.Context, arg UpdateNodeDrainedParams) error
	UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) error
	UpdateRunCompletion(ctx context.Context, arg UpdateRunCompletionParams) error
	UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error
	UpdateStageStatus(ctx context.Context, arg UpdateStageStatusParams) error
}

var _ Querier = (*Queries)(nil)
