// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (url, branch, commit_sha)
VALUES ($1, $2, $3)
RETURNING id, url, branch, commit_sha, created_at
`

type CreateRepoParams struct {
	Url       string  `json:"url"`
	Branch    *string `json:"branch"`
	CommitSha *string `json:"commit_sha"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepo, arg.Url, arg.Branch, arg.CommitSha)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Branch,
		&i.CommitSha,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos
WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const getRepo = `-- name: GetRepo :one
SELECT id, url, branch, commit_sha, created_at FROM repos
WHERE id = $1
`

func (q *Queries) GetRepo(ctx context.Context, id pgtype.UUID) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Branch,
		&i.CommitSha,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoByURL = `-- name: GetRepoByURL :one
SELECT id, url, branch, commit_sha, created_at FROM repos
WHERE url = $1
`

func (q *Queries) GetRepoByURL(ctx context.Context, url string) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByURL, url)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Branch,
		&i.CommitSha,
		&i.CreatedAt,
	)
	return i, err
}

const listRepos = `-- name: ListRepos :many
SELECT id, url, branch, commit_sha, created_at FROM repos
ORDER BY created_at DESC
`

func (q *Queries) ListRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Branch,
			&i.CommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
