// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repos.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const getRepo = `-- name: GetRepo :one
SELECT id, url, created_at
FROM repos
WHERE id = $1
`

func (q *Queries) GetRepo(ctx context.Context, id types.RepoID) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepo, id)
	var i Repo
	err := row.Scan(&i.ID, &i.Url, &i.CreatedAt)
	return i, err
}
