// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_repos.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRunReposByStatus = `-- name: CountRunReposByStatus :many
SELECT status, COUNT(*)::int AS count
FROM run_repos
WHERE run_id = $1
GROUP BY status
`

type CountRunReposByStatusRow struct {
	Status RunRepoStatus `json:"status"`
	Count  int32         `json:"count"`
}

// Aggregates run_repos counts by status for a given run.
// Used to derive batch-level status (e.g., all succeeded = batch succeeded).
func (q *Queries) CountRunReposByStatus(ctx context.Context, runID pgtype.UUID) ([]CountRunReposByStatusRow, error) {
	rows, err := q.db.Query(ctx, countRunReposByStatus, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRunReposByStatusRow{}
	for rows.Next() {
		var i CountRunReposByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRunRepo = `-- name: CreateRunRepo :one
INSERT INTO run_repos (run_id, repo_url, base_ref, target_ref, status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, run_id, repo_url, base_ref, target_ref, status, attempt, last_error, created_at, started_at, finished_at
`

type CreateRunRepoParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	RepoUrl   string      `json:"repo_url"`
	BaseRef   string      `json:"base_ref"`
	TargetRef string      `json:"target_ref"`
}

// Creates a new run_repo entry for batched runs.
// Each run_repo represents one repository within a batch (parent run).
func (q *Queries) CreateRunRepo(ctx context.Context, arg CreateRunRepoParams) (RunRepo, error) {
	row := q.db.QueryRow(ctx, createRunRepo,
		arg.RunID,
		arg.RepoUrl,
		arg.BaseRef,
		arg.TargetRef,
	)
	var i RunRepo
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.Status,
		&i.Attempt,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteRunRepo = `-- name: DeleteRunRepo :exec
DELETE FROM run_repos
WHERE id = $1
`

func (q *Queries) DeleteRunRepo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRunRepo, id)
	return err
}

const getRunRepo = `-- name: GetRunRepo :one
SELECT id, run_id, repo_url, base_ref, target_ref, status, attempt, last_error, created_at, started_at, finished_at FROM run_repos
WHERE id = $1
`

func (q *Queries) GetRunRepo(ctx context.Context, id pgtype.UUID) (RunRepo, error) {
	row := q.db.QueryRow(ctx, getRunRepo, id)
	var i RunRepo
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.RepoUrl,
		&i.BaseRef,
		&i.TargetRef,
		&i.Status,
		&i.Attempt,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const incrementRunRepoAttempt = `-- name: IncrementRunRepoAttempt :exec
UPDATE run_repos
SET attempt = attempt + 1,
    status = 'pending',
    last_error = NULL,
    started_at = NULL,
    finished_at = NULL
WHERE id = $1
`

// Increments the attempt counter and resets status to 'pending' for retry.
// Clears timing fields to prepare for a fresh execution attempt.
func (q *Queries) IncrementRunRepoAttempt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementRunRepoAttempt, id)
	return err
}

const listRunReposByRun = `-- name: ListRunReposByRun :many
SELECT id, run_id, repo_url, base_ref, target_ref, status, attempt, last_error, created_at, started_at, finished_at FROM run_repos
WHERE run_id = $1
ORDER BY created_at ASC
`

// Lists all repos associated with a run (batch), ordered by creation time.
func (q *Queries) ListRunReposByRun(ctx context.Context, runID pgtype.UUID) ([]RunRepo, error) {
	rows, err := q.db.Query(ctx, listRunReposByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunRepo{}
	for rows.Next() {
		var i RunRepo
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.RepoUrl,
			&i.BaseRef,
			&i.TargetRef,
			&i.Status,
			&i.Attempt,
			&i.LastError,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunRepoError = `-- name: UpdateRunRepoError :exec
UPDATE run_repos
SET last_error = $2
WHERE id = $1
`

type UpdateRunRepoErrorParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError *string     `json:"last_error"`
}

// Updates a run_repo's last_error field (e.g., on failure).
func (q *Queries) UpdateRunRepoError(ctx context.Context, arg UpdateRunRepoErrorParams) error {
	_, err := q.db.Exec(ctx, updateRunRepoError, arg.ID, arg.LastError)
	return err
}

const updateRunRepoStatus = `-- name: UpdateRunRepoStatus :exec
UPDATE run_repos
SET status = $2,
    started_at = CASE WHEN $2 = 'running' AND started_at IS NULL THEN now() ELSE started_at END,
    finished_at = CASE WHEN $2 IN ('succeeded', 'failed', 'skipped', 'cancelled') THEN now() ELSE finished_at END
WHERE id = $1
`

type UpdateRunRepoStatusParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status RunRepoStatus `json:"status"`
}

// Updates a run_repo's status along with timing fields.
// started_at is set when transitioning to 'running'.
// finished_at is set when transitioning to a terminal status.
func (q *Queries) UpdateRunRepoStatus(ctx context.Context, arg UpdateRunRepoStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunRepoStatus, arg.ID, arg.Status)
	return err
}
