// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_steps.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackRunStepStart = `-- name: AckRunStepStart :exec
UPDATE run_steps
SET status = 'running'
WHERE id = $1 AND status = 'assigned'
`

// Acknowledges that a step has started execution (transitions from 'assigned' to 'running').
func (q *Queries) AckRunStepStart(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ackRunStepStart, id)
	return err
}

const claimRunStep = `-- name: ClaimRunStep :one
WITH eligible_steps AS (
  SELECT rs.id, rs.run_id, rs.step_index
  FROM run_steps rs
  INNER JOIN runs r ON r.id = rs.run_id
  INNER JOIN nodes n ON n.id = $1
  WHERE rs.status = 'queued'
    AND n.drained = false
    -- Step 0 can always be claimed; step k>0 requires step k-1 to have succeeded.
    AND (
      rs.step_index = 0
      OR EXISTS (
        SELECT 1 FROM run_steps prev
        WHERE prev.run_id = rs.run_id
          AND prev.step_index = rs.step_index - 1
          AND prev.status = 'succeeded'
      )
    )
  ORDER BY r.created_at, rs.step_index
  FOR UPDATE OF rs SKIP LOCKED
  LIMIT 1
)
UPDATE run_steps rs
SET status = 'assigned', node_id = $1, started_at = now()
FROM eligible_steps e
WHERE rs.id = e.id
RETURNING rs.id, rs.run_id, rs.step_index, rs.status, rs.node_id, rs.started_at, rs.finished_at, rs.reason
`

// Claims the next available step for execution using FOR UPDATE SKIP LOCKED.
// Returns the step and its parent run information for execution.
//
// Claim strategy:
// 1. Find queued steps where the previous step (step_index - 1) has succeeded OR step_index = 0.
// 2. Join with runs to get run metadata (repo_url, base_ref, etc.).
// 3. Join with nodes to ensure the node is not drained.
// 4. Use FOR UPDATE SKIP LOCKED to avoid contention.
// 5. Update step status to 'assigned' and set node_id.
//
// This ensures sequential execution: step k can only be claimed after step k-1 succeeds.
func (q *Queries) ClaimRunStep(ctx context.Context, nodeID pgtype.UUID) (RunStep, error) {
	row := q.db.QueryRow(ctx, claimRunStep, nodeID)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepIndex,
		&i.Status,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Reason,
	)
	return i, err
}

const countRunSteps = `-- name: CountRunSteps :one
SELECT COUNT(*) FROM run_steps
WHERE run_id = $1
`

// Counts the total number of steps for a run.
func (q *Queries) CountRunSteps(ctx context.Context, runID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRunSteps, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRunStepsByStatus = `-- name: CountRunStepsByStatus :one
SELECT COUNT(*) FROM run_steps
WHERE run_id = $1 AND status = $2
`

type CountRunStepsByStatusParams struct {
	RunID  pgtype.UUID   `json:"run_id"`
	Status RunStepStatus `json:"status"`
}

// Counts steps for a run with a specific status.
func (q *Queries) CountRunStepsByStatus(ctx context.Context, arg CountRunStepsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRunStepsByStatus, arg.RunID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRunStep = `-- name: CreateRunStep :one
INSERT INTO run_steps (run_id, step_index, status)
VALUES ($1, $2, $3)
RETURNING id, run_id, step_index, status, node_id, started_at, finished_at, reason
`

type CreateRunStepParams struct {
	RunID     pgtype.UUID   `json:"run_id"`
	StepIndex int32         `json:"step_index"`
	Status    RunStepStatus `json:"status"`
}

// Creates a new step for a run (called when multi-step run is queued).
func (q *Queries) CreateRunStep(ctx context.Context, arg CreateRunStepParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, createRunStep, arg.RunID, arg.StepIndex, arg.Status)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepIndex,
		&i.Status,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Reason,
	)
	return i, err
}

const deleteRunStep = `-- name: DeleteRunStep :exec
DELETE FROM run_steps
WHERE id = $1
`

// Deletes a step (usually for cleanup or test teardown).
func (q *Queries) DeleteRunStep(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRunStep, id)
	return err
}

const getRunStep = `-- name: GetRunStep :one
SELECT id, run_id, step_index, status, node_id, started_at, finished_at, reason FROM run_steps
WHERE id = $1
`

// Retrieves a single step by its ID.
func (q *Queries) GetRunStep(ctx context.Context, id pgtype.UUID) (RunStep, error) {
	row := q.db.QueryRow(ctx, getRunStep, id)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepIndex,
		&i.Status,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Reason,
	)
	return i, err
}

const getRunStepByIndex = `-- name: GetRunStepByIndex :one
SELECT id, run_id, step_index, status, node_id, started_at, finished_at, reason FROM run_steps
WHERE run_id = $1 AND step_index = $2
`

type GetRunStepByIndexParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	StepIndex int32       `json:"step_index"`
}

// Retrieves a specific step of a run by step_index.
func (q *Queries) GetRunStepByIndex(ctx context.Context, arg GetRunStepByIndexParams) (RunStep, error) {
	row := q.db.QueryRow(ctx, getRunStepByIndex, arg.RunID, arg.StepIndex)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepIndex,
		&i.Status,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Reason,
	)
	return i, err
}

const listRunSteps = `-- name: ListRunSteps :many
SELECT id, run_id, step_index, status, node_id, started_at, finished_at, reason FROM run_steps
WHERE run_id = $1
ORDER BY step_index ASC
`

// Lists all steps for a run ordered by step_index.
func (q *Queries) ListRunSteps(ctx context.Context, runID pgtype.UUID) ([]RunStep, error) {
	rows, err := q.db.Query(ctx, listRunSteps, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunStep{}
	for rows.Next() {
		var i RunStep
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepIndex,
			&i.Status,
			&i.NodeID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStepCompletion = `-- name: UpdateRunStepCompletion :exec
UPDATE run_steps
SET status = $2, reason = $3, finished_at = now()
WHERE id = $1
`

type UpdateRunStepCompletionParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status RunStepStatus `json:"status"`
	Reason *string       `json:"reason"`
}

// Updates a step's terminal status (succeeded/failed/canceled) and timing.
func (q *Queries) UpdateRunStepCompletion(ctx context.Context, arg UpdateRunStepCompletionParams) error {
	_, err := q.db.Exec(ctx, updateRunStepCompletion, arg.ID, arg.Status, arg.Reason)
	return err
}
