// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: run_repos.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveRunReposByRun = `-- name: CancelActiveRunReposByRun :execrows
UPDATE run_repos
SET status = 'Cancelled',
    finished_at = COALESCE(finished_at, now())
WHERE run_id = $1
  AND status IN ('Queued', 'Running')
`

// Bulk-cancels active repos for a run (Queued/Running -> Cancelled).
func (q *Queries) CancelActiveRunReposByRun(ctx context.Context, runID types.RunID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelActiveRunReposByRun, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRunReposByStatus = `-- name: CountRunReposByStatus :many
SELECT status, COUNT(*)::int AS count
FROM run_repos
WHERE run_id = $1
GROUP BY status
`

type CountRunReposByStatusRow struct {
	Status RunRepoStatus `json:"status"`
	Count  int32         `json:"count"`
}

func (q *Queries) CountRunReposByStatus(ctx context.Context, runID types.RunID) ([]CountRunReposByStatusRow, error) {
	rows, err := q.db.Query(ctx, countRunReposByStatus, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRunReposByStatusRow{}
	for rows.Next() {
		var i CountRunReposByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRunRepo = `-- name: CreateRunRepo :one
INSERT INTO run_repos (mig_id, run_id, repo_id, repo_base_ref, repo_target_ref)
VALUES ($1, $2, $3, $4, $5)
RETURNING mig_id, run_id, repo_id, repo_base_ref, repo_target_ref, status, attempt, last_error, created_at, started_at, finished_at
`

type CreateRunRepoParams struct {
	MigID         types.MigID     `json:"mig_id"`
	RunID         types.RunID     `json:"run_id"`
	RepoID        types.MigRepoID `json:"repo_id"`
	RepoBaseRef   string          `json:"repo_base_ref"`
	RepoTargetRef string          `json:"repo_target_ref"`
}

// v1: Creates a new run_repos row scoped to (run_id, repo_id).
// Note: attempt defaults to 1; status defaults to 'Queued'.
func (q *Queries) CreateRunRepo(ctx context.Context, arg CreateRunRepoParams) (RunRepo, error) {
	row := q.db.QueryRow(ctx, createRunRepo,
		arg.MigID,
		arg.RunID,
		arg.RepoID,
		arg.RepoBaseRef,
		arg.RepoTargetRef,
	)
	var i RunRepo
	err := row.Scan(
		&i.MigID,
		&i.RunID,
		&i.RepoID,
		&i.RepoBaseRef,
		&i.RepoTargetRef,
		&i.Status,
		&i.Attempt,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteRunRepo = `-- name: DeleteRunRepo :exec
DELETE FROM run_repos
WHERE run_id = $1 AND repo_id = $2
`

type DeleteRunRepoParams struct {
	RunID  types.RunID     `json:"run_id"`
	RepoID types.MigRepoID `json:"repo_id"`
}

func (q *Queries) DeleteRunRepo(ctx context.Context, arg DeleteRunRepoParams) error {
	_, err := q.db.Exec(ctx, deleteRunRepo, arg.RunID, arg.RepoID)
	return err
}

const getLatestRunRepoByMigAndRepoStatus = `-- name: GetLatestRunRepoByMigAndRepoStatus :one
SELECT rr.run_id, rr.repo_id, rr.repo_target_ref
FROM run_repos rr
JOIN runs r ON rr.run_id = r.id
WHERE r.mig_id = $1
  AND rr.repo_id = $2
  AND rr.status = $3
ORDER BY rr.created_at DESC
LIMIT 1
`

type GetLatestRunRepoByMigAndRepoStatusParams struct {
	MigID  types.MigID     `json:"mig_id"`
	RepoID types.MigRepoID `json:"repo_id"`
	Status RunRepoStatus   `json:"status"`
}

type GetLatestRunRepoByMigAndRepoStatusRow struct {
	RunID         types.RunID     `json:"run_id"`
	RepoID        types.MigRepoID `json:"repo_id"`
	RepoTargetRef string          `json:"repo_target_ref"`
}

// v1: Gets the newest run_repos row for a specific repo_id in a mig,
// filtered by terminal status (Success or Fail).
// Used by POST /v1/migs/{mig_id}/pull to select last-succeeded or last-failed.
// Order by created_at DESC to get the newest matching run_repos row.
func (q *Queries) GetLatestRunRepoByMigAndRepoStatus(ctx context.Context, arg GetLatestRunRepoByMigAndRepoStatusParams) (GetLatestRunRepoByMigAndRepoStatusRow, error) {
	row := q.db.QueryRow(ctx, getLatestRunRepoByMigAndRepoStatus, arg.MigID, arg.RepoID, arg.Status)
	var i GetLatestRunRepoByMigAndRepoStatusRow
	err := row.Scan(&i.RunID, &i.RepoID, &i.RepoTargetRef)
	return i, err
}

const getRunRepo = `-- name: GetRunRepo :one
SELECT mig_id, run_id, repo_id, repo_base_ref, repo_target_ref, status, attempt, last_error, created_at, started_at, finished_at
FROM run_repos
WHERE run_id = $1 AND repo_id = $2
`

type GetRunRepoParams struct {
	RunID  types.RunID     `json:"run_id"`
	RepoID types.MigRepoID `json:"repo_id"`
}

func (q *Queries) GetRunRepo(ctx context.Context, arg GetRunRepoParams) (RunRepo, error) {
	row := q.db.QueryRow(ctx, getRunRepo, arg.RunID, arg.RepoID)
	var i RunRepo
	err := row.Scan(
		&i.MigID,
		&i.RunID,
		&i.RepoID,
		&i.RepoBaseRef,
		&i.RepoTargetRef,
		&i.Status,
		&i.Attempt,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const incrementRunRepoAttempt = `-- name: IncrementRunRepoAttempt :exec
UPDATE run_repos
SET attempt = attempt + 1,
    status = 'Queued',
    last_error = NULL,
    started_at = NULL,
    finished_at = NULL
WHERE run_id = $1 AND repo_id = $2
`

type IncrementRunRepoAttemptParams struct {
	RunID  types.RunID     `json:"run_id"`
	RepoID types.MigRepoID `json:"repo_id"`
}

// Increments attempt and resets status/timing for a fresh repo execution attempt.
func (q *Queries) IncrementRunRepoAttempt(ctx context.Context, arg IncrementRunRepoAttemptParams) error {
	_, err := q.db.Exec(ctx, incrementRunRepoAttempt, arg.RunID, arg.RepoID)
	return err
}

const listFailedRepoIDsByMig = `-- name: ListFailedRepoIDsByMig :many
SELECT repo_id FROM (
  SELECT DISTINCT ON (rr.repo_id) rr.repo_id, rr.status
  FROM run_repos rr
  WHERE rr.mig_id = $1
    AND rr.status IN ('Fail', 'Success', 'Cancelled')
  ORDER BY rr.repo_id, rr.created_at DESC, rr.run_id DESC
) AS last_status
WHERE status = 'Fail'
`

// Lists repo_ids whose last terminal run_repos status is 'Fail' for a given mig.
// "Last terminal state" per repo_id is determined by looking at the newest run_repos
// row where status in (Fail, Success, Cancelled) and selecting those where status='Fail'.
// Uses a subquery to get the last terminal status per repo, then filters for 'Fail'.
func (q *Queries) ListFailedRepoIDsByMig(ctx context.Context, migID types.MigID) ([]types.MigRepoID, error) {
	rows, err := q.db.Query(ctx, listFailedRepoIDsByMig, migID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []types.MigRepoID{}
	for rows.Next() {
		var repo_id types.MigRepoID
		if err := rows.Scan(&repo_id); err != nil {
			return nil, err
		}
		items = append(items, repo_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedRunReposByRun = `-- name: ListQueuedRunReposByRun :many
SELECT mig_id, run_id, repo_id, repo_base_ref, repo_target_ref, status, attempt, last_error, created_at, started_at, finished_at
FROM run_repos
WHERE run_id = $1 AND status = 'Queued'
ORDER BY created_at ASC, repo_id ASC
`

func (q *Queries) ListQueuedRunReposByRun(ctx context.Context, runID types.RunID) ([]RunRepo, error) {
	rows, err := q.db.Query(ctx, listQueuedRunReposByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunRepo{}
	for rows.Next() {
		var i RunRepo
		if err := rows.Scan(
			&i.MigID,
			&i.RunID,
			&i.RepoID,
			&i.RepoBaseRef,
			&i.RepoTargetRef,
			&i.Status,
			&i.Attempt,
			&i.LastError,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunReposByRun = `-- name: ListRunReposByRun :many
SELECT mig_id, run_id, repo_id, repo_base_ref, repo_target_ref, status, attempt, last_error, created_at, started_at, finished_at
FROM run_repos
WHERE run_id = $1
ORDER BY created_at ASC, repo_id ASC
`

// Lists all repos associated with a run, ordered by creation time.
func (q *Queries) ListRunReposByRun(ctx context.Context, runID types.RunID) ([]RunRepo, error) {
	rows, err := q.db.Query(ctx, listRunReposByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunRepo{}
	for rows.Next() {
		var i RunRepo
		if err := rows.Scan(
			&i.MigID,
			&i.RunID,
			&i.RepoID,
			&i.RepoBaseRef,
			&i.RepoTargetRef,
			&i.Status,
			&i.Attempt,
			&i.LastError,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunReposWithURLByRun = `-- name: ListRunReposWithURLByRun :many
SELECT rr.mig_id, rr.run_id, rr.repo_id, rr.repo_base_ref, rr.repo_target_ref,
       rr.status, rr.attempt, rr.last_error, rr.created_at, rr.started_at, rr.finished_at,
       mr.repo_url
FROM run_repos rr
JOIN mig_repos mr ON rr.repo_id = mr.id
WHERE rr.run_id = $1
ORDER BY rr.created_at ASC, rr.repo_id ASC
`

type ListRunReposWithURLByRunRow struct {
	MigID         types.MigID        `json:"mig_id"`
	RunID         types.RunID        `json:"run_id"`
	RepoID        types.MigRepoID    `json:"repo_id"`
	RepoBaseRef   string             `json:"repo_base_ref"`
	RepoTargetRef string             `json:"repo_target_ref"`
	Status        RunRepoStatus      `json:"status"`
	Attempt       int32              `json:"attempt"`
	LastError     *string            `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	RepoUrl       string             `json:"repo_url"`
}

// v1: Lists all run_repos for a run with their repo_url (from mig_repos).
// Used by:
// - GET  /v1/runs/{id}/repos (full repo response without N+1 lookups)
// - POST /v1/runs/{run_id}/pull (repo resolution by normalized URL)
func (q *Queries) ListRunReposWithURLByRun(ctx context.Context, runID types.RunID) ([]ListRunReposWithURLByRunRow, error) {
	rows, err := q.db.Query(ctx, listRunReposWithURLByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunReposWithURLByRunRow{}
	for rows.Next() {
		var i ListRunReposWithURLByRunRow
		if err := rows.Scan(
			&i.MigID,
			&i.RunID,
			&i.RepoID,
			&i.RepoBaseRef,
			&i.RepoTargetRef,
			&i.Status,
			&i.Attempt,
			&i.LastError,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RepoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsForRepo = `-- name: ListRunsForRepo :many
SELECT
  r.id AS run_id,
  r.mig_id,
  r.status AS run_status,
  rr.status AS repo_status,
  rr.repo_base_ref,
  rr.repo_target_ref,
  rr.attempt,
  rr.started_at,
  rr.finished_at
FROM run_repos rr
JOIN runs r ON rr.run_id = r.id
WHERE rr.repo_id = $1
ORDER BY rr.created_at DESC, rr.run_id DESC
LIMIT $2 OFFSET $3
`

type ListRunsForRepoParams struct {
	RepoID types.MigRepoID `json:"repo_id"`
	Limit  int32           `json:"limit"`
	Offset int32           `json:"offset"`
}

type ListRunsForRepoRow struct {
	RunID         types.RunID        `json:"run_id"`
	MigID         types.MigID        `json:"mig_id"`
	RunStatus     RunStatus          `json:"run_status"`
	RepoStatus    RunRepoStatus      `json:"repo_status"`
	RepoBaseRef   string             `json:"repo_base_ref"`
	RepoTargetRef string             `json:"repo_target_ref"`
	Attempt       int32              `json:"attempt"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}

// Lists runs for a given repo_id (mig_repos.id).
func (q *Queries) ListRunsForRepo(ctx context.Context, arg ListRunsForRepoParams) ([]ListRunsForRepoRow, error) {
	rows, err := q.db.Query(ctx, listRunsForRepo, arg.RepoID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunsForRepoRow{}
	for rows.Next() {
		var i ListRunsForRepoRow
		if err := rows.Scan(
			&i.RunID,
			&i.MigID,
			&i.RunStatus,
			&i.RepoStatus,
			&i.RepoBaseRef,
			&i.RepoTargetRef,
			&i.Attempt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsWithQueuedRepos = `-- name: ListRunsWithQueuedRepos :many
SELECT DISTINCT r.id
FROM runs r
JOIN run_repos rr ON r.id = rr.run_id
WHERE r.status = 'Started'
  AND rr.status = 'Queued'
ORDER BY r.id
`

// Lists runs that have queued work (at least one Queued run_repos row).
func (q *Queries) ListRunsWithQueuedRepos(ctx context.Context) ([]types.RunID, error) {
	rows, err := q.db.Query(ctx, listRunsWithQueuedRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []types.RunID{}
	for rows.Next() {
		var id types.RunID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunRepoError = `-- name: UpdateRunRepoError :exec
UPDATE run_repos
SET last_error = $3
WHERE run_id = $1 AND repo_id = $2
`

type UpdateRunRepoErrorParams struct {
	RunID     types.RunID     `json:"run_id"`
	RepoID    types.MigRepoID `json:"repo_id"`
	LastError *string         `json:"last_error"`
}

func (q *Queries) UpdateRunRepoError(ctx context.Context, arg UpdateRunRepoErrorParams) error {
	_, err := q.db.Exec(ctx, updateRunRepoError, arg.RunID, arg.RepoID, arg.LastError)
	return err
}

const updateRunRepoRefs = `-- name: UpdateRunRepoRefs :exec
UPDATE run_repos
SET repo_base_ref = $3,
    repo_target_ref = $4
WHERE run_id = $1 AND repo_id = $2
`

type UpdateRunRepoRefsParams struct {
	RunID         types.RunID     `json:"run_id"`
	RepoID        types.MigRepoID `json:"repo_id"`
	RepoBaseRef   string          `json:"repo_base_ref"`
	RepoTargetRef string          `json:"repo_target_ref"`
}

// Updates snapshot refs for the run repo (used when restarting with new refs).
func (q *Queries) UpdateRunRepoRefs(ctx context.Context, arg UpdateRunRepoRefsParams) error {
	_, err := q.db.Exec(ctx, updateRunRepoRefs,
		arg.RunID,
		arg.RepoID,
		arg.RepoBaseRef,
		arg.RepoTargetRef,
	)
	return err
}

const updateRunRepoStatus = `-- name: UpdateRunRepoStatus :exec
UPDATE run_repos
SET status = $3,
    started_at = CASE WHEN $3 = 'Running'::run_repo_status AND started_at IS NULL THEN now() ELSE started_at END,
    finished_at = CASE WHEN $3 IN ('Success'::run_repo_status, 'Fail'::run_repo_status, 'Cancelled'::run_repo_status) THEN COALESCE(finished_at, now()) ELSE finished_at END
WHERE run_id = $1 AND repo_id = $2
`

type UpdateRunRepoStatusParams struct {
	RunID  types.RunID     `json:"run_id"`
	RepoID types.MigRepoID `json:"repo_id"`
	Status RunRepoStatus   `json:"status"`
}

// Updates repo status + timing fields.
// started_at: set when transitioning to Running.
// finished_at: set when transitioning to a terminal status.
func (q *Queries) UpdateRunRepoStatus(ctx context.Context, arg UpdateRunRepoStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunRepoStatus, arg.RunID, arg.RepoID, arg.Status)
	return err
}
