// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const createRun = `-- name: CreateRun :one
INSERT INTO runs (id, mig_id, spec_id, created_by, status, started_at)
VALUES ($1, $2, $3, $4, 'Started', now())
RETURNING id, mig_id, spec_id, created_by, status, created_at, started_at, finished_at, stats
`

type CreateRunParams struct {
	ID        types.RunID  `json:"id"`
	MigID     types.MigID  `json:"mig_id"`
	SpecID    types.SpecID `json:"spec_id"`
	CreatedBy *string      `json:"created_by"`
}

// v1: Creates a new run for a mod + spec snapshot. Runs are created in Started state.
// Note: `id` is a required TEXT parameter (KSUID-backed); caller generates via types.NewRunID().
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.ID,
		arg.MigID,
		arg.SpecID,
		arg.CreatedBy,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.SpecID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Stats,
	)
	return i, err
}

const deleteRun = `-- name: DeleteRun :exec
DELETE FROM runs
WHERE id = $1
`

func (q *Queries) DeleteRun(ctx context.Context, id types.RunID) error {
	_, err := q.db.Exec(ctx, deleteRun, id)
	return err
}

const getRun = `-- name: GetRun :one
SELECT id, mig_id, spec_id, created_by, status, created_at, started_at, finished_at, stats
FROM runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id types.RunID) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.SpecID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Stats,
	)
	return i, err
}

const getRunTiming = `-- name: GetRunTiming :one
SELECT id,
       COALESCE(queue_ms, 0) AS queue_ms,
       COALESCE(run_ms, 0)   AS run_ms
FROM runs_timing
WHERE id = $1
`

func (q *Queries) GetRunTiming(ctx context.Context, id types.RunID) (RunsTiming, error) {
	row := q.db.QueryRow(ctx, getRunTiming, id)
	var i RunsTiming
	err := row.Scan(&i.ID, &i.QueueMs, &i.RunMs)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT id, mig_id, spec_id, created_by, status, created_at, started_at, finished_at, stats
FROM runs
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListRunsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.MigID,
			&i.SpecID,
			&i.CreatedBy,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsTimings = `-- name: ListRunsTimings :many
SELECT id,
       COALESCE(queue_ms, 0) AS queue_ms,
       COALESCE(run_ms, 0)   AS run_ms
FROM runs_timing
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListRunsTimingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRunsTimings(ctx context.Context, arg ListRunsTimingsParams) ([]RunsTiming, error) {
	rows, err := q.db.Query(ctx, listRunsTimings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunsTiming{}
	for rows.Next() {
		var i RunsTiming
		if err := rows.Scan(&i.ID, &i.QueueMs, &i.RunMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunCompletion = `-- name: UpdateRunCompletion :exec
UPDATE runs
SET status = $2, finished_at = now(), stats = $3
WHERE id = $1
`

type UpdateRunCompletionParams struct {
	ID     types.RunID `json:"id"`
	Status RunStatus   `json:"status"`
	Stats  []byte      `json:"stats"`
}

func (q *Queries) UpdateRunCompletion(ctx context.Context, arg UpdateRunCompletionParams) error {
	_, err := q.db.Exec(ctx, updateRunCompletion, arg.ID, arg.Status, arg.Stats)
	return err
}

const updateRunResume = `-- name: UpdateRunResume :exec
UPDATE runs
SET stats = stats || jsonb_build_object(
    'resume_count', COALESCE((stats->>'resume_count')::int, 0) + 1,
    'last_resumed_at', to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
)
WHERE id = $1
`

// Increments resume_count and updates last_resumed_at timestamp in runs.stats.
// Uses JSONB merge (||) to preserve existing stats while adding resume metadata.
func (q *Queries) UpdateRunResume(ctx context.Context, id types.RunID) error {
	_, err := q.db.Exec(ctx, updateRunResume, id)
	return err
}

const updateRunStatsMRURL = `-- name: UpdateRunStatsMRURL :exec
	UPDATE runs
	SET stats = COALESCE(stats, '{}'::jsonb) || jsonb_build_object(
	    'metadata',
	    COALESCE(stats->'metadata', '{}'::jsonb) || jsonb_build_object('mr_url', $2)
	)
	WHERE id = $1
`

type UpdateRunStatsMRURLParams struct {
	ID    types.RunID `json:"id"`
	MrUrl interface{} `json:"mr_url"`
}

// Merge an MR URL into runs.stats.metadata.mr_url without altering other fields.
// Preserves existing stats and metadata keys via JSONB merge.
func (q *Queries) UpdateRunStatsMRURL(ctx context.Context, arg UpdateRunStatsMRURLParams) error {
	_, err := q.db.Exec(ctx, updateRunStatsMRURL, arg.ID, arg.MrUrl)
	return err
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE runs
SET status = $2,
    finished_at = CASE
      WHEN $2 IN ('Cancelled'::run_status, 'Finished'::run_status) THEN COALESCE(finished_at, now())
      ELSE NULL
    END
WHERE id = $1
`

type UpdateRunStatusParams struct {
	ID     types.RunID `json:"id"`
	Status RunStatus   `json:"status"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateRunStatus, arg.ID, arg.Status)
	return err
}
