// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sboms_compat.sql

package store

import (
	"context"
)

const hasSBOMEvidenceForStack = `-- name: HasSBOMEvidenceForStack :one
WITH sbom_rows_with_stack AS (
  SELECT
    st.lang,
    st.release,
    COALESCE(st.tool, '') AS tool
  FROM sboms s
  JOIN jobs j ON j.id = s.job_id
  JOIN gates g ON g.job_id = CASE
    WHEN j.job_type = 'sbom' THEN (
      SELECT gj.id
      FROM jobs gj
      WHERE gj.run_id = j.run_id
        AND gj.repo_id = j.repo_id
        AND gj.attempt = j.attempt
        AND gj.name = regexp_replace(j.name, '-sbom$', '')
        AND gj.job_type IN ('pre_gate', 'post_gate', 're_gate')
      LIMIT 1
    )
    ELSE j.id
  END
  JOIN gate_profiles gp ON gp.id = g.profile_id
  JOIN stacks st ON st.id = gp.stack_id
  WHERE j.status = 'Success'
    AND j.job_type IN ('pre_gate', 'post_gate', 're_gate', 'sbom')
)
SELECT EXISTS(
  SELECT 1
  FROM sbom_rows_with_stack s
  WHERE s.lang = $1::text
    AND s.release = $2::text
    AND s.tool = $3::text
) AS has_evidence
`

type HasSBOMEvidenceForStackParams struct {
	Lang    string `json:"lang"`
	Release string `json:"release"`
	Tool    string `json:"tool"`
}

func (q *Queries) HasSBOMEvidenceForStack(ctx context.Context, arg HasSBOMEvidenceForStackParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSBOMEvidenceForStack, arg.Lang, arg.Release, arg.Tool)
	var has_evidence bool
	err := row.Scan(&has_evidence)
	return has_evidence, err
}

const listSBOMCompatRows = `-- name: ListSBOMCompatRows :many
WITH sbom_rows_with_stack AS (
  SELECT
    s.lib,
    s.ver,
    st.lang,
    st.release,
    COALESCE(st.tool, '') AS tool
  FROM sboms s
  JOIN jobs j ON j.id = s.job_id
  JOIN gates g ON g.job_id = CASE
    WHEN j.job_type = 'sbom' THEN (
      SELECT gj.id
      FROM jobs gj
      WHERE gj.run_id = j.run_id
        AND gj.repo_id = j.repo_id
        AND gj.attempt = j.attempt
        AND gj.name = regexp_replace(j.name, '-sbom$', '')
        AND gj.job_type IN ('pre_gate', 'post_gate', 're_gate')
      LIMIT 1
    )
    ELSE j.id
  END
  JOIN gate_profiles gp ON gp.id = g.profile_id
  JOIN stacks st ON st.id = gp.stack_id
  WHERE j.status = 'Success'
    AND j.job_type IN ('pre_gate', 'post_gate', 're_gate', 'sbom')
)
SELECT s.lib, s.ver
FROM sbom_rows_with_stack s
WHERE s.lang = $1::text
  AND s.release = $2::text
  AND s.tool = $3::text
  AND s.lib = ANY($4::text[])
GROUP BY s.lib, s.ver
ORDER BY s.lib ASC, s.ver ASC
`

type ListSBOMCompatRowsParams struct {
	Lang    string   `json:"lang"`
	Release string   `json:"release"`
	Tool    string   `json:"tool"`
	Libs    []string `json:"libs"`
}

type ListSBOMCompatRowsRow struct {
	Lib string `json:"lib"`
	Ver string `json:"ver"`
}

func (q *Queries) ListSBOMCompatRows(ctx context.Context, arg ListSBOMCompatRowsParams) ([]ListSBOMCompatRowsRow, error) {
	rows, err := q.db.Query(ctx, listSBOMCompatRows,
		arg.Lang,
		arg.Release,
		arg.Tool,
		arg.Libs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSBOMCompatRowsRow{}
	for rows.Next() {
		var i ListSBOMCompatRowsRow
		if err := rows.Scan(&i.Lib, &i.Ver); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
