// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sboms.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const deleteSBOMRowsByJob = `-- name: DeleteSBOMRowsByJob :exec
DELETE FROM sboms
WHERE job_id = $1
`

func (q *Queries) DeleteSBOMRowsByJob(ctx context.Context, jobID types.JobID) error {
	_, err := q.db.Exec(ctx, deleteSBOMRowsByJob, jobID)
	return err
}

const listRunSBOMRowsByJobType = `-- name: ListRunSBOMRowsByJobType :many
SELECT DISTINCT s.lib, s.ver
FROM sboms s
JOIN jobs j ON j.id = s.job_id
JOIN runs r ON r.id = j.run_id
WHERE j.run_id = $1
  AND j.attempt = r.attempt
  AND j.job_type = $2
ORDER BY s.lib ASC, s.ver ASC
`

type ListRunSBOMRowsByJobTypeParams struct {
	RunID   types.RunID   `json:"run_id"`
	JobType types.JobType `json:"job_type"`
}

type ListRunSBOMRowsByJobTypeRow struct {
	Lib string `json:"lib"`
	Ver string `json:"ver"`
}

func (q *Queries) ListRunSBOMRowsByJobType(ctx context.Context, arg ListRunSBOMRowsByJobTypeParams) ([]ListRunSBOMRowsByJobTypeRow, error) {
	rows, err := q.db.Query(ctx, listRunSBOMRowsByJobType, arg.RunID, arg.JobType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRunSBOMRowsByJobTypeRow{}
	for rows.Next() {
		var i ListRunSBOMRowsByJobTypeRow
		if err := rows.Scan(&i.Lib, &i.Ver); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSBOMRow = `-- name: UpsertSBOMRow :exec
INSERT INTO sboms (job_id, repo_id, lib, ver)
VALUES ($1, $2, $3, $4)
ON CONFLICT (job_id, repo_id, lib, ver) DO NOTHING
`

type UpsertSBOMRowParams struct {
	JobID  types.JobID  `json:"job_id"`
	RepoID types.RepoID `json:"repo_id"`
	Lib    string       `json:"lib"`
	Ver    string       `json:"ver"`
}

func (q *Queries) UpsertSBOMRow(ctx context.Context, arg UpsertSBOMRowParams) error {
	_, err := q.db.Exec(ctx, upsertSBOMRow,
		arg.JobID,
		arg.RepoID,
		arg.Lib,
		arg.Ver,
	)
	return err
}
