// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sboms_compat.sql

package store

import (
	"context"
)

const hasSBOMEvidenceForStack = `-- name: HasSBOMEvidenceForStack :one
SELECT EXISTS(
  SELECT 1
  FROM sboms s
  JOIN jobs j ON j.id = s.job_id
  JOIN gates g ON g.job_id = s.job_id
  JOIN gate_profiles gp ON gp.id = g.profile_id
  JOIN stacks st ON st.id = gp.stack_id
  WHERE j.status = 'Success'
    AND j.job_type IN ('pre_gate', 'post_gate', 're_gate')
    AND st.lang = $1::text
    AND st.release = $2::text
    AND COALESCE(st.tool, '') = $3::text
) AS has_evidence
`

type HasSBOMEvidenceForStackParams struct {
	Lang    string `json:"lang"`
	Release string `json:"release"`
	Tool    string `json:"tool"`
}

func (q *Queries) HasSBOMEvidenceForStack(ctx context.Context, arg HasSBOMEvidenceForStackParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSBOMEvidenceForStack, arg.Lang, arg.Release, arg.Tool)
	var has_evidence bool
	err := row.Scan(&has_evidence)
	return has_evidence, err
}

const listSBOMCompatRows = `-- name: ListSBOMCompatRows :many
SELECT s.lib, s.ver
FROM sboms s
JOIN jobs j ON j.id = s.job_id
JOIN gates g ON g.job_id = s.job_id
JOIN gate_profiles gp ON gp.id = g.profile_id
JOIN stacks st ON st.id = gp.stack_id
WHERE j.status = 'Success'
  AND j.job_type IN ('pre_gate', 'post_gate', 're_gate')
  AND st.lang = $1::text
  AND st.release = $2::text
  AND COALESCE(st.tool, '') = $3::text
  AND s.lib = ANY($4::text[])
GROUP BY s.lib, s.ver
ORDER BY s.lib ASC, s.ver ASC
`

type ListSBOMCompatRowsParams struct {
	Lang    string   `json:"lang"`
	Release string   `json:"release"`
	Tool    string   `json:"tool"`
	Libs    []string `json:"libs"`
}

type ListSBOMCompatRowsRow struct {
	Lib string `json:"lib"`
	Ver string `json:"ver"`
}

func (q *Queries) ListSBOMCompatRows(ctx context.Context, arg ListSBOMCompatRowsParams) ([]ListSBOMCompatRowsRow, error) {
	rows, err := q.db.Query(ctx, listSBOMCompatRows,
		arg.Lang,
		arg.Release,
		arg.Tool,
		arg.Libs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSBOMCompatRowsRow{}
	for rows.Next() {
		var i ListSBOMCompatRowsRow
		if err := rows.Scan(&i.Lib, &i.Ver); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
