// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sboms.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const deleteSBOMRowsByJob = `-- name: DeleteSBOMRowsByJob :exec
DELETE FROM sboms
WHERE job_id = $1
`

func (q *Queries) DeleteSBOMRowsByJob(ctx context.Context, jobID types.JobID) error {
	_, err := q.db.Exec(ctx, deleteSBOMRowsByJob, jobID)
	return err
}

const listSBOMRowsByJob = `-- name: ListSBOMRowsByJob :many
SELECT job_id, repo_id, lib, ver, created_at
FROM sboms
WHERE job_id = $1
ORDER BY lib ASC, ver ASC
`

func (q *Queries) ListSBOMRowsByJob(ctx context.Context, jobID types.JobID) ([]Sbom, error) {
	rows, err := q.db.Query(ctx, listSBOMRowsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sbom{}
	for rows.Next() {
		var i Sbom
		if err := rows.Scan(
			&i.JobID,
			&i.RepoID,
			&i.Lib,
			&i.Ver,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSBOMRow = `-- name: UpsertSBOMRow :exec
INSERT INTO sboms (job_id, repo_id, lib, ver)
VALUES ($1, $2, $3, $4)
ON CONFLICT (job_id, repo_id, lib, ver) DO NOTHING
`

type UpsertSBOMRowParams struct {
	JobID  types.JobID  `json:"job_id"`
	RepoID types.RepoID `json:"repo_id"`
	Lib    string       `json:"lib"`
	Ver    string       `json:"ver"`
}

func (q *Queries) UpsertSBOMRow(ctx context.Context, arg UpsertSBOMRowParams) error {
	_, err := q.db.Exec(ctx, upsertSBOMRow,
		arg.JobID,
		arg.RepoID,
		arg.Lib,
		arg.Ver,
	)
	return err
}
