// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sboms.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const deleteSBOMRowsByJob = `-- name: DeleteSBOMRowsByJob :exec
DELETE FROM sboms
WHERE job_id = $1
`

func (q *Queries) DeleteSBOMRowsByJob(ctx context.Context, jobID types.JobID) error {
	_, err := q.db.Exec(ctx, deleteSBOMRowsByJob, jobID)
	return err
}

const upsertSBOMRow = `-- name: UpsertSBOMRow :exec
INSERT INTO sboms (job_id, repo_id, lib, ver)
VALUES ($1, $2, $3, $4)
ON CONFLICT (job_id, repo_id, lib, ver) DO NOTHING
`

type UpsertSBOMRowParams struct {
	JobID  types.JobID  `json:"job_id"`
	RepoID types.RepoID `json:"repo_id"`
	Lib    string       `json:"lib"`
	Ver    string       `json:"ver"`
}

func (q *Queries) UpsertSBOMRow(ctx context.Context, arg UpsertSBOMRowParams) error {
	_, err := q.db.Exec(ctx, upsertSBOMRow,
		arg.JobID,
		arg.RepoID,
		arg.Lib,
		arg.Ver,
	)
	return err
}
