// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: specs.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGitSpecSnapshot = `-- name: CreateGitSpecSnapshot :one
INSERT INTO specs (id, name, description, source, sha, source_committed_at, spec, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, source, sha, source_committed_at, spec, created_by, created_at
`

type CreateGitSpecSnapshotParams struct {
	ID                types.SpecID       `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	Source            []byte             `json:"source"`
	Sha               string             `json:"sha"`
	SourceCommittedAt pgtype.Timestamptz `json:"source_committed_at"`
	Spec              []byte             `json:"spec"`
	CreatedBy         *string            `json:"created_by"`
}

func (q *Queries) CreateGitSpecSnapshot(ctx context.Context, arg CreateGitSpecSnapshotParams) (Spec, error) {
	row := q.db.QueryRow(ctx, createGitSpecSnapshot,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Source,
		arg.Sha,
		arg.SourceCommittedAt,
		arg.Spec,
		arg.CreatedBy,
	)
	var i Spec
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.Sha,
		&i.SourceCommittedAt,
		&i.Spec,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSpec = `-- name: CreateSpec :one
INSERT INTO specs (id, name, spec, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, source, sha, source_committed_at, spec, created_by, created_at
`

type CreateSpecParams struct {
	ID        types.SpecID `json:"id"`
	Name      string       `json:"name"`
	Spec      []byte       `json:"spec"`
	CreatedBy *string      `json:"created_by"`
}

func (q *Queries) CreateSpec(ctx context.Context, arg CreateSpecParams) (Spec, error) {
	row := q.db.QueryRow(ctx, createSpec,
		arg.ID,
		arg.Name,
		arg.Spec,
		arg.CreatedBy,
	)
	var i Spec
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.Sha,
		&i.SourceCommittedAt,
		&i.Spec,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGitSpecSnapshot = `-- name: GetGitSpecSnapshot :one
SELECT id, name, description, source, sha, source_committed_at, spec, created_by, created_at
FROM specs
WHERE name = $1::text
  AND source->>'domain' = $2::text
  AND source->>'repo' = $3::text
  AND COALESCE(source->>'path', '') = $4::text
  AND sha = $5::text
  AND sha <> ''
  AND spec = $6::jsonb
ORDER BY created_at, id
LIMIT 1
`

type GetGitSpecSnapshotParams struct {
	Name   string `json:"name"`
	Domain string `json:"domain"`
	Repo   string `json:"repo"`
	Path   string `json:"path"`
	Sha    string `json:"sha"`
	Spec   []byte `json:"spec"`
}

func (q *Queries) GetGitSpecSnapshot(ctx context.Context, arg GetGitSpecSnapshotParams) (Spec, error) {
	row := q.db.QueryRow(ctx, getGitSpecSnapshot,
		arg.Name,
		arg.Domain,
		arg.Repo,
		arg.Path,
		arg.Sha,
		arg.Spec,
	)
	var i Spec
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.Sha,
		&i.SourceCommittedAt,
		&i.Spec,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSpec = `-- name: GetSpec :one
SELECT id, name, description, source, sha, source_committed_at, spec, created_by, created_at
FROM specs
WHERE id = $1
`

func (q *Queries) GetSpec(ctx context.Context, id types.SpecID) (Spec, error) {
	row := q.db.QueryRow(ctx, getSpec, id)
	var i Spec
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Source,
		&i.Sha,
		&i.SourceCommittedAt,
		&i.Spec,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listSpecs = `-- name: ListSpecs :many
SELECT id, name, description, source, sha, source_committed_at, spec, created_by, created_at
FROM specs
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListSpecsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Lists specs ordered by created_at descending (most recent first).
// There is an index on created_at to optimize this query.
func (q *Queries) ListSpecs(ctx context.Context, arg ListSpecsParams) ([]Spec, error) {
	rows, err := q.db.Query(ctx, listSpecs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spec{}
	for rows.Next() {
		var i Spec
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Source,
			&i.Sha,
			&i.SourceCommittedAt,
			&i.Spec,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
