// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spec_bundles.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSpecBundle = `-- name: CreateSpecBundle :one
INSERT INTO spec_bundles (id, cid, digest, size, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, cid, digest, size, object_key, created_by, created_at, last_ref_at
`

type CreateSpecBundleParams struct {
	ID        types.SpecBundleID `json:"id"`
	Cid       string             `json:"cid"`
	Digest    string             `json:"digest"`
	Size      int64              `json:"size"`
	CreatedBy *string            `json:"created_by"`
}

// Creates a new spec bundle metadata row. Blob data is stored in object storage.
// The returned id becomes the bundle_id field in TmpBundleRef.
func (q *Queries) CreateSpecBundle(ctx context.Context, arg CreateSpecBundleParams) (SpecBundle, error) {
	row := q.db.QueryRow(ctx, createSpecBundle,
		arg.ID,
		arg.Cid,
		arg.Digest,
		arg.Size,
		arg.CreatedBy,
	)
	var i SpecBundle
	err := row.Scan(
		&i.ID,
		&i.Cid,
		&i.Digest,
		&i.Size,
		&i.ObjectKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastRefAt,
	)
	return i, err
}

const getSpecBundle = `-- name: GetSpecBundle :one
SELECT id, cid, digest, size, object_key, created_by, created_at, last_ref_at
FROM spec_bundles
WHERE id = $1
`

// Returns spec bundle metadata including object_key for object-storage retrieval.
func (q *Queries) GetSpecBundle(ctx context.Context, id types.SpecBundleID) (SpecBundle, error) {
	row := q.db.QueryRow(ctx, getSpecBundle, id)
	var i SpecBundle
	err := row.Scan(
		&i.ID,
		&i.Cid,
		&i.Digest,
		&i.Size,
		&i.ObjectKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastRefAt,
	)
	return i, err
}

const getSpecBundleByCID = `-- name: GetSpecBundleByCID :one
SELECT id, cid, digest, size, object_key, created_by, created_at, last_ref_at
FROM spec_bundles
WHERE cid = $1
ORDER BY created_at DESC
LIMIT 1
`

// Returns the most recently created spec bundle for a given cid.
// Used for deduplication: callers should check by CID before uploading.
func (q *Queries) GetSpecBundleByCID(ctx context.Context, cid string) (SpecBundle, error) {
	row := q.db.QueryRow(ctx, getSpecBundleByCID, cid)
	var i SpecBundle
	err := row.Scan(
		&i.ID,
		&i.Cid,
		&i.Digest,
		&i.Size,
		&i.ObjectKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastRefAt,
	)
	return i, err
}

const listSpecBundles = `-- name: ListSpecBundles :many
SELECT id, cid, digest, size, object_key, created_by, created_at, last_ref_at
FROM spec_bundles
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListSpecBundlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Lists spec bundles ordered by created_at descending (most recent first).
func (q *Queries) ListSpecBundles(ctx context.Context, arg ListSpecBundlesParams) ([]SpecBundle, error) {
	rows, err := q.db.Query(ctx, listSpecBundles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpecBundle{}
	for rows.Next() {
		var i SpecBundle
		if err := rows.Scan(
			&i.ID,
			&i.Cid,
			&i.Digest,
			&i.Size,
			&i.ObjectKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastRefAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpecBundleLastRefAt = `-- name: UpdateSpecBundleLastRefAt :exec
UPDATE spec_bundles
SET last_ref_at = now()
WHERE id = $1
`

// Updates last_ref_at to now() for the given spec bundle.
// Call this whenever a spec or run references the bundle to keep GC metadata fresh.
func (q *Queries) UpdateSpecBundleLastRefAt(ctx context.Context, id types.SpecBundleID) error {
	_, err := q.db.Exec(ctx, updateSpecBundleLastRefAt, id)
	return err
}

const deleteSpecBundle = `-- name: DeleteSpecBundle :exec
DELETE FROM spec_bundles WHERE id = $1
`

// Deletes a spec bundle metadata row by ID.
// Called by blobpersist as rollback when object storage upload fails.
func (q *Queries) DeleteSpecBundle(ctx context.Context, id types.SpecBundleID) error {
	_, err := q.db.Exec(ctx, deleteSpecBundle, id)
	return err
}

const listSpecBundlesUnreferencedBefore = `-- name: ListSpecBundlesUnreferencedBefore :many
SELECT id, cid, digest, size, object_key, created_by, created_at, last_ref_at
FROM spec_bundles
WHERE last_ref_at < $1
ORDER BY last_ref_at ASC
`

// Lists spec bundles whose last_ref_at is before the given threshold.
// Used by GC to find bundles eligible for deletion.
func (q *Queries) ListSpecBundlesUnreferencedBefore(ctx context.Context, lastRefAt pgtype.Timestamptz) ([]SpecBundle, error) {
	rows, err := q.db.Query(ctx, listSpecBundlesUnreferencedBefore, lastRefAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpecBundle{}
	for rows.Next() {
		var i SpecBundle
		if err := rows.Scan(
			&i.ID,
			&i.Cid,
			&i.Digest,
			&i.Size,
			&i.ObjectKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastRefAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
