// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: specs.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const createSpec = `-- name: CreateSpec :one
INSERT INTO specs (id, name, spec, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, spec, created_by, created_at, archived_at
`

type CreateSpecParams struct {
	ID        types.SpecID `json:"id"`
	Name      string       `json:"name"`
	Spec      []byte       `json:"spec"`
	CreatedBy *string      `json:"created_by"`
}

func (q *Queries) CreateSpec(ctx context.Context, arg CreateSpecParams) (Spec, error) {
	row := q.db.QueryRow(ctx, createSpec,
		arg.ID,
		arg.Name,
		arg.Spec,
		arg.CreatedBy,
	)
	var i Spec
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Spec,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getSpec = `-- name: GetSpec :one
SELECT id, name, spec, created_by, created_at, archived_at
FROM specs
WHERE id = $1
`

func (q *Queries) GetSpec(ctx context.Context, id types.SpecID) (Spec, error) {
	row := q.db.QueryRow(ctx, getSpec, id)
	var i Spec
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Spec,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listSpecs = `-- name: ListSpecs :many
SELECT id, name, spec, created_by, created_at, archived_at
FROM specs
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListSpecsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Lists specs ordered by created_at descending (most recent first).
// There is an index on created_at to optimize this query.
func (q *Queries) ListSpecs(ctx context.Context, arg ListSpecsParams) ([]Spec, error) {
	rows, err := q.db.Query(ctx, listSpecs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Spec{}
	for rows.Next() {
		var i Spec
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Spec,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
