// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStage = `-- name: CreateStage :one
INSERT INTO stages (run_id, name, status, meta)
VALUES ($1, $2, $3, $4)
RETURNING id, run_id, name, status, started_at, finished_at, duration_ms, meta
`

type CreateStageParams struct {
	RunID  pgtype.UUID `json:"run_id"`
	Name   string      `json:"name"`
	Status StageStatus `json:"status"`
	Meta   []byte      `json:"meta"`
}

func (q *Queries) CreateStage(ctx context.Context, arg CreateStageParams) (Stage, error) {
	row := q.db.QueryRow(ctx, createStage,
		arg.RunID,
		arg.Name,
		arg.Status,
		arg.Meta,
	)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
	)
	return i, err
}

const deleteStage = `-- name: DeleteStage :exec
DELETE FROM stages
WHERE id = $1
`

func (q *Queries) DeleteStage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStage, id)
	return err
}

const getStage = `-- name: GetStage :one
SELECT id, run_id, name, status, started_at, finished_at, duration_ms, meta FROM stages
WHERE id = $1
`

func (q *Queries) GetStage(ctx context.Context, id pgtype.UUID) (Stage, error) {
	row := q.db.QueryRow(ctx, getStage, id)
	var i Stage
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.Meta,
	)
	return i, err
}

const listStagesByRun = `-- name: ListStagesByRun :many
SELECT id, run_id, name, status, started_at, finished_at, duration_ms, meta FROM stages
WHERE run_id = $1
ORDER BY name ASC
`

func (q *Queries) ListStagesByRun(ctx context.Context, runID pgtype.UUID) ([]Stage, error) {
	rows, err := q.db.Query(ctx, listStagesByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stage{}
	for rows.Next() {
		var i Stage
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.Meta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStageStatus = `-- name: UpdateStageStatus :exec
UPDATE stages
SET status = $2, started_at = $3, finished_at = $4, duration_ms = $5
WHERE id = $1
`

type UpdateStageStatusParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     StageStatus        `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	DurationMs int64              `json:"duration_ms"`
}

func (q *Queries) UpdateStageStatus(ctx context.Context, arg UpdateStageStatusParams) error {
	_, err := q.db.Exec(ctx, updateStageStatus,
		arg.ID,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.DurationMs,
	)
	return err
}
