// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: steps.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const getStepByJob = `-- name: GetStepByJob :one
SELECT job_id, ops, hash, ref_job_id, created_at
FROM steps
WHERE job_id = $1
`

func (q *Queries) GetStepByJob(ctx context.Context, jobID string) (Step, error) {
	row := q.db.QueryRow(ctx, getStepByJob, jobID)
	var i Step
	err := row.Scan(
		&i.JobID,
		&i.Ops,
		&i.Hash,
		&i.RefJobID,
		&i.CreatedAt,
	)
	return i, err
}

const resolveReusableStepByHash = `-- name: ResolveReusableStepByHash :one
SELECT
  j.id AS ref_job_id,
  j.repo_sha_out AS ref_repo_sha_out
FROM steps s
JOIN jobs j ON j.id = s.job_id
WHERE j.repo_id = $1
  AND j.repo_sha_in = $2
  AND j.job_type = 'mig'
  AND j.status = 'Success'
  AND j.repo_sha_out ~ '^[0-9a-f]{40}$'
  AND s.hash = $3
ORDER BY j.finished_at DESC NULLS LAST, j.id DESC
LIMIT 1
`

type ResolveReusableStepByHashParams struct {
	RepoID    types.RepoID `json:"repo_id"`
	RepoShaIn string       `json:"repo_sha_in"`
	Hash      string       `json:"hash"`
}

type ResolveReusableStepByHashRow struct {
	RefJobID      types.JobID `json:"ref_job_id"`
	RefRepoShaOut string      `json:"ref_repo_sha_out"`
}

func (q *Queries) ResolveReusableStepByHash(ctx context.Context, arg ResolveReusableStepByHashParams) (ResolveReusableStepByHashRow, error) {
	row := q.db.QueryRow(ctx, resolveReusableStepByHash, arg.RepoID, arg.RepoShaIn, arg.Hash)
	var i ResolveReusableStepByHashRow
	err := row.Scan(&i.RefJobID, &i.RefRepoShaOut)
	return i, err
}

const upsertStep = `-- name: UpsertStep :exec
INSERT INTO steps (job_id, ops, hash, ref_job_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (job_id)
DO UPDATE SET
  ops = EXCLUDED.ops,
  hash = EXCLUDED.hash,
  ref_job_id = EXCLUDED.ref_job_id
`

type UpsertStepParams struct {
	JobID    string  `json:"job_id"`
	Ops      []byte  `json:"ops"`
	Hash     string  `json:"hash"`
	RefJobID *string `json:"ref_job_id"`
}

func (q *Queries) UpsertStep(ctx context.Context, arg UpsertStepParams) error {
	_, err := q.db.Exec(ctx, upsertStep,
		arg.JobID,
		arg.Ops,
		arg.Hash,
		arg.RefJobID,
	)
	return err
}
