// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAPITokenRevoked = `-- name: CheckAPITokenRevoked :one
SELECT revoked_at FROM api_tokens
WHERE token_id = $1 AND revoked_at IS NOT NULL
LIMIT 1
`

func (q *Queries) CheckAPITokenRevoked(ctx context.Context, tokenID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, checkAPITokenRevoked, tokenID)
	var revoked_at pgtype.Timestamptz
	err := row.Scan(&revoked_at)
	return revoked_at, err
}

const checkBootstrapTokenRevoked = `-- name: CheckBootstrapTokenRevoked :one
SELECT revoked_at FROM bootstrap_tokens
WHERE token_id = $1 AND revoked_at IS NOT NULL
LIMIT 1
`

func (q *Queries) CheckBootstrapTokenRevoked(ctx context.Context, tokenID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, checkBootstrapTokenRevoked, tokenID)
	var revoked_at pgtype.Timestamptz
	err := row.Scan(&revoked_at)
	return revoked_at, err
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :exec
UPDATE api_tokens
SET last_used_at = NOW()
WHERE token_id = $1
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, tokenID string) error {
	_, err := q.db.Exec(ctx, updateAPITokenLastUsed, tokenID)
	return err
}

const updateBootstrapTokenLastUsed = `-- name: UpdateBootstrapTokenLastUsed :exec
UPDATE bootstrap_tokens
SET used_at = NOW()
WHERE token_id = $1 AND used_at IS NULL
`

func (q *Queries) UpdateBootstrapTokenLastUsed(ctx context.Context, tokenID string) error {
	_, err := q.db.Exec(ctx, updateBootstrapTokenLastUsed, tokenID)
	return err
}
