// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ttl.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredArtifactBundles = `-- name: DeleteExpiredArtifactBundles :execrows
DELETE FROM artifact_bundles
WHERE created_at < $1
`

// DeleteExpiredArtifactBundles removes artifact bundle rows older than the specified timestamp.
func (q *Queries) DeleteExpiredArtifactBundles(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredArtifactBundles, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredDiffs = `-- name: DeleteExpiredDiffs :execrows
DELETE FROM diffs
WHERE created_at < $1
`

// DeleteExpiredDiffs removes diff rows older than the specified timestamp.
func (q *Queries) DeleteExpiredDiffs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDiffs, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredEvents = `-- name: DeleteExpiredEvents :execrows
DELETE FROM events
WHERE time < $1
`

// DeleteExpiredEvents removes event rows older than the specified timestamp.
func (q *Queries) DeleteExpiredEvents(ctx context.Context, time pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEvents, time)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredLogs = `-- name: DeleteExpiredLogs :execrows
DELETE FROM logs
WHERE created_at < $1
`

// DeleteExpiredLogs removes log rows older than the specified timestamp.
func (q *Queries) DeleteExpiredLogs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLogs, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
