// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ttl.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredArtifactBundles = `-- name: DeleteExpiredArtifactBundles :execrows
DELETE FROM artifact_bundles
WHERE created_at < $1
`

// DeleteExpiredArtifactBundles removes artifact bundle rows older than the specified timestamp.
func (q *Queries) DeleteExpiredArtifactBundles(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredArtifactBundles, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredDiffs = `-- name: DeleteExpiredDiffs :execrows
DELETE FROM diffs
WHERE created_at < $1
`

// DeleteExpiredDiffs removes diff rows older than the specified timestamp.
func (q *Queries) DeleteExpiredDiffs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDiffs, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredEvents = `-- name: DeleteExpiredEvents :execrows
DELETE FROM events
WHERE time < $1
`

// DeleteExpiredEvents removes event rows older than the specified timestamp.
func (q *Queries) DeleteExpiredEvents(ctx context.Context, time pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredEvents, time)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredLogs = `-- name: DeleteExpiredLogs :execrows
DELETE FROM logs
WHERE created_at < $1
`

// DeleteExpiredLogs removes log rows older than the specified timestamp.
func (q *Queries) DeleteExpiredLogs(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredLogs, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listArtifactBundlePartitions = `-- name: ListArtifactBundlePartitions :many
SELECT inhrelid::regclass::text AS partition_name
FROM pg_catalog.pg_inherits
WHERE inhparent = 'ploy.artifact_bundles'::regclass
`

// ListArtifactBundlePartitions retrieves all partition names for the artifact_bundles table.
func (q *Queries) ListArtifactBundlePartitions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listArtifactBundlePartitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var partition_name string
		if err := rows.Scan(&partition_name); err != nil {
			return nil, err
		}
		items = append(items, partition_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventPartitions = `-- name: ListEventPartitions :many
SELECT inhrelid::regclass::text AS partition_name
FROM pg_catalog.pg_inherits
WHERE inhparent = 'ploy.events'::regclass
`

// ListEventPartitions retrieves all partition names for the events table.
func (q *Queries) ListEventPartitions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listEventPartitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var partition_name string
		if err := rows.Scan(&partition_name); err != nil {
			return nil, err
		}
		items = append(items, partition_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogPartitions = `-- name: ListLogPartitions :many
SELECT inhrelid::regclass::text AS partition_name
FROM pg_catalog.pg_inherits
WHERE inhparent = 'ploy.logs'::regclass
`

// ListLogPartitions retrieves all partition names for the logs table.
func (q *Queries) ListLogPartitions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listLogPartitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var partition_name string
		if err := rows.Scan(&partition_name); err != nil {
			return nil, err
		}
		items = append(items, partition_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeMetricsPartitions = `-- name: ListNodeMetricsPartitions :many
SELECT inhrelid::regclass::text AS partition_name
FROM pg_catalog.pg_inherits
WHERE inhparent = 'ploy.node_metrics'::regclass
`

// ListNodeMetricsPartitions retrieves all partition names for the node_metrics table.
func (q *Queries) ListNodeMetricsPartitions(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listNodeMetricsPartitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var partition_name string
		if err := rows.Scan(&partition_name); err != nil {
			return nil, err
		}
		items = append(items, partition_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
