// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waves.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const createWave = `-- name: CreateWave :one
INSERT INTO waves (id, mig_id, spec_id, created_by, status, started_at)
VALUES ($1, $2, $3, $4, 'Started', now())
RETURNING id, mig_id, spec_id, created_by, status, created_at, started_at, finished_at, stats
`

type CreateWaveParams struct {
	ID        types.WaveID `json:"id"`
	MigID     types.MigID  `json:"mig_id"`
	SpecID    types.SpecID `json:"spec_id"`
	CreatedBy *string      `json:"created_by"`
}

func (q *Queries) CreateWave(ctx context.Context, arg CreateWaveParams) (Wave, error) {
	row := q.db.QueryRow(ctx, createWave,
		arg.ID,
		arg.MigID,
		arg.SpecID,
		arg.CreatedBy,
	)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.SpecID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Stats,
	)
	return i, err
}

const deleteWave = `-- name: DeleteWave :exec
DELETE FROM waves
WHERE id = $1
`

func (q *Queries) DeleteWave(ctx context.Context, id types.WaveID) error {
	_, err := q.db.Exec(ctx, deleteWave, id)
	return err
}

const getWave = `-- name: GetWave :one
SELECT id, mig_id, spec_id, created_by, status, created_at, started_at, finished_at, stats
FROM waves
WHERE id = $1
`

func (q *Queries) GetWave(ctx context.Context, id types.WaveID) (Wave, error) {
	row := q.db.QueryRow(ctx, getWave, id)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.SpecID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Stats,
	)
	return i, err
}

const listWaves = `-- name: ListWaves :many
SELECT id, mig_id, spec_id, created_by, status, created_at, started_at, finished_at, stats
FROM waves
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListWavesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListWaves(ctx context.Context, arg ListWavesParams) ([]Wave, error) {
	rows, err := q.db.Query(ctx, listWaves, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wave{}
	for rows.Next() {
		var i Wave
		if err := rows.Scan(
			&i.ID,
			&i.MigID,
			&i.SpecID,
			&i.CreatedBy,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWavesByMig = `-- name: ListWavesByMig :many
SELECT id, mig_id, spec_id, created_by, status, created_at, started_at, finished_at, stats
FROM waves
WHERE mig_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListWavesByMigParams struct {
	MigID  types.MigID `json:"mig_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListWavesByMig(ctx context.Context, arg ListWavesByMigParams) ([]Wave, error) {
	rows, err := q.db.Query(ctx, listWavesByMig, arg.MigID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wave{}
	for rows.Next() {
		var i Wave
		if err := rows.Scan(
			&i.ID,
			&i.MigID,
			&i.SpecID,
			&i.CreatedBy,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWaveCompletion = `-- name: UpdateWaveCompletion :exec
UPDATE waves
SET status = $2, finished_at = now(), stats = $3
WHERE id = $1
`

type UpdateWaveCompletionParams struct {
	ID     types.WaveID     `json:"id"`
	Status types.WaveStatus `json:"status"`
	Stats  []byte           `json:"stats"`
}

func (q *Queries) UpdateWaveCompletion(ctx context.Context, arg UpdateWaveCompletionParams) error {
	_, err := q.db.Exec(ctx, updateWaveCompletion, arg.ID, arg.Status, arg.Stats)
	return err
}

const updateWaveStatus = `-- name: UpdateWaveStatus :exec
UPDATE waves
SET status = $2,
    finished_at = CASE
      WHEN $2 IN ('Cancelled'::wave_status, 'Finished'::wave_status) THEN COALESCE(finished_at, now())
      ELSE NULL
    END
WHERE id = $1
`

type UpdateWaveStatusParams struct {
	ID     types.WaveID     `json:"id"`
	Status types.WaveStatus `json:"status"`
}

func (q *Queries) UpdateWaveStatus(ctx context.Context, arg UpdateWaveStatusParams) error {
	_, err := q.db.Exec(ctx, updateWaveStatus, arg.ID, arg.Status)
	return err
}
