// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: waves.sql

package store

import (
	"context"

	"github.com/iw2rmb/ploy/internal/domain/types"
)

const createWave = `-- name: CreateWave :one
INSERT INTO waves (id, mig_id, spec_id, created_by, status, started_at)
VALUES ($1, $2, $3, $4, 'Started', now())
RETURNING id, mig_id, spec_id, created_by, status, created_at, started_at, finished_at, stats
`

type CreateWaveParams struct {
	ID        types.WaveID `json:"id"`
	MigID     types.MigID  `json:"mig_id"`
	SpecID    types.SpecID `json:"spec_id"`
	CreatedBy *string      `json:"created_by"`
}

func (q *Queries) CreateWave(ctx context.Context, arg CreateWaveParams) (Wave, error) {
	row := q.db.QueryRow(ctx, createWave,
		arg.ID,
		arg.MigID,
		arg.SpecID,
		arg.CreatedBy,
	)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.SpecID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Stats,
	)
	return i, err
}

const getWave = `-- name: GetWave :one
SELECT id, mig_id, spec_id, created_by, status, created_at, started_at, finished_at, stats
FROM waves
WHERE id = $1
`

func (q *Queries) GetWave(ctx context.Context, id types.WaveID) (Wave, error) {
	row := q.db.QueryRow(ctx, getWave, id)
	var i Wave
	err := row.Scan(
		&i.ID,
		&i.MigID,
		&i.SpecID,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Stats,
	)
	return i, err
}

const updateWaveCompletion = `-- name: UpdateWaveCompletion :exec
UPDATE waves
SET status = $2, finished_at = now(), stats = $3
WHERE id = $1
`

type UpdateWaveCompletionParams struct {
	ID     types.WaveID     `json:"id"`
	Status types.WaveStatus `json:"status"`
	Stats  []byte           `json:"stats"`
}

func (q *Queries) UpdateWaveCompletion(ctx context.Context, arg UpdateWaveCompletionParams) error {
	_, err := q.db.Exec(ctx, updateWaveCompletion, arg.ID, arg.Status, arg.Stats)
	return err
}

const updateWaveStatus = `-- name: UpdateWaveStatus :exec
UPDATE waves
SET status = $2,
    finished_at = CASE
      WHEN $2 IN ('Cancelled'::wave_status, 'Finished'::wave_status) THEN COALESCE(finished_at, now())
      ELSE NULL
    END
WHERE id = $1
`

type UpdateWaveStatusParams struct {
	ID     types.WaveID     `json:"id"`
	Status types.WaveStatus `json:"status"`
}

func (q *Queries) UpdateWaveStatus(ctx context.Context, arg UpdateWaveStatusParams) error {
	_, err := q.db.Exec(ctx, updateWaveStatus, arg.ID, arg.Status)
	return err
}
